//! Typed schema for `mail-rules.json` (generated by `_shared/lib/mail-rules.nix`).
//!
//! The Python sorter read this file with `rules.get("filters") or {}` at every
//! access, so a renamed or misspelled key degraded to "feature absent" and the
//! container kept reporting healthy while quietly doing nothing. Every silent
//! mail-filing failure this session started that way.
//!
//! Here the schema is declared once and parsed once, at startup:
//!   * a missing required key is a startup error, not an empty default;
//!   * an unknown `predicate.type` is a startup error (see [`Predicate`]),
//!     where the Python returned `False` and produced a permanently empty
//!     filter folder that is indistinguishable from a working one;
//!   * keys the sorter does not consume (`routing`, `sieve_require`, ...) are
//!     ignored, because routing is owned by the native Sieve.

use serde::Deserialize;
use std::collections::BTreeMap;

/// Deserialize `null` as `T::default()`, not as an error.
///
/// JMAP peers and the rules generator both emit explicit `null` for "absent",
/// which plain `#[serde(default)]` (missing-key only) rejects.
pub fn null_default<'de, D, T>(d: D) -> Result<T, D::Error>
where
    D: serde::Deserializer<'de>,
    T: Default + Deserialize<'de>,
{
    Ok(Option::deserialize(d)?.unwrap_or_default())
}

#[derive(Debug, Deserialize)]
pub struct Rules {
    /// Mail account the sorter authenticates as. Required — without it there
    /// is nothing to log into, so failing here beats failing per-request.
    pub account: String,

    /// Routing targets, `key -> folder name`. Owned by the Sieve; the sorter
    /// only ensures the mailboxes exist and treats the names as valid.
    ///
    /// BTreeMap, not HashMap: iteration order decides the `sortOrder` handed to
    /// newly created mailboxes. Python dicts preserve JSON order, so the Python
    /// sorter was deterministic for free; a HashMap would hand a different
    /// sortOrder to every folder created after each container restart.
    pub folders: BTreeMap<String, String>,

    /// Two-level folder groups (e.g. "31 Cloud - Reports & CI" with real
    /// children GH Workflows / Cloud Reports / Rss Notifications) — unlike
    /// `folders` above, which is flat ROOT-only. A rule's `copy_to` targets
    /// a child by its own key; the child's simple name (not a path string)
    /// is what Sieve's `fileinto` and this sorter's own membership checks
    /// use, since JMAP mailbox names only need to be unique per parent, and
    /// none of these child names collide with anything else in the account.
    #[serde(default, deserialize_with = "null_default")]
    pub folder_groups: Vec<FolderGroup>,

    /// Visual section-header folders — flat ROOT siblings, not parents.
    #[serde(default, deserialize_with = "null_default")]
    pub folders_ui: Vec<String>,

    #[serde(default, deserialize_with = "null_default")]
    pub filters: Filters,

    #[serde(default, deserialize_with = "null_default")]
    pub folder_renames: FolderRenames,

    /// Per-folder client-visibility options. See [`FolderOptions`].
    #[serde(default, deserialize_with = "null_default")]
    pub folder_options: FolderOptions,
}

/// Controls how the mailboxes this sorter manages present themselves to mail
/// clients. `default` applies to every managed folder; `overrides` is keyed by
/// the folder's display name and wins where present.
///
/// Only `subscribed` today, because it is the only one of these that JMAP
/// actually models: `isSubscribed` is the IMAP LSUB bit, i.e. whether a
/// client shows the folder in its normal folder list at all. Stalwart creates
/// mailboxes UNSUBSCRIBED, so every folder this sorter ever made was hidden
/// in clients that only list subscribed folders (measured on oci-mail: 53 of
/// 60 unsubscribed — everything except the 7 built-in system folders).
///
/// Deliberately NOT modelled here: per-folder "notify me". JMAP has no such
/// mailbox property, and inventing one in this file would be a setting that
/// silently does nothing. Client notification behaviour is driven by
/// subscription plus the folder's `role`, both of which are real.
#[derive(Debug, Default, Deserialize)]
pub struct FolderOptions {
    #[serde(default, deserialize_with = "null_default")]
    pub default: FolderOption,
    /// folder display name -> option overrides.
    #[serde(default, deserialize_with = "null_default")]
    pub overrides: BTreeMap<String, FolderOption>,
}

#[derive(Debug, Clone, Default, Deserialize)]
pub struct FolderOption {
    /// `None` means "inherit" (override falls back to default; default falls
    /// back to true — a managed folder you cannot see is not useful).
    #[serde(default, deserialize_with = "null_default")]
    pub subscribed: Option<bool>,
}

impl FolderOptions {
    /// Should `name` appear in a client's folder list? Override, else
    /// default, else true.
    pub fn subscribed_for(&self, name: &str) -> bool {
        self.overrides
            .get(name)
            .and_then(|o| o.subscribed)
            .or(self.default.subscribed)
            .unwrap_or(true)
    }
}

#[derive(Debug, Deserialize)]
pub struct FolderGroup {
    #[allow(dead_code)] // not consumed directly; present for schema fidelity / future use
    pub key: String,
    pub name: String,
    /// child key -> child display name. BTreeMap for the same determinism
    /// reason as [`Rules::folders`] — iteration order decides sortOrder.
    pub children: BTreeMap<String, String>,
}

#[derive(Debug, Default, Deserialize)]
pub struct FolderRenames {
    /// `old name -> new name`, applied in place so the mailbox keeps its mail.
    /// BTreeMap for the same determinism reason as [`Rules::folders`] — renames
    /// are applied in iteration order and a chain must not reorder per run.
    #[serde(default, deserialize_with = "null_default")]
    pub map: BTreeMap<String, String>,
}

#[derive(Debug, Default, Deserialize)]
pub struct Filters {
    #[serde(default, deserialize_with = "null_default")]
    pub views: Vec<View>,

    #[serde(default, deserialize_with = "null_default")]
    pub section_headers: Vec<String>,

    /// Which mailbox names hold the messages the views range over. The Sieve
    /// files every inbound message into exactly one numeric `1*`-`9*` folder.
    #[serde(default = "default_source_regex")]
    pub source_folder_regex: String,

    /// Axis whose views tile their range exactly once (every message lands in
    /// exactly one bucket). Asserted in CI by
    /// 9_others/test/test_mail_filter_views_partition.sh.
    ///
    /// This binary no longer reads it: it used to drive a "static views
    /// already computed" skip in `filters.rs` that silently starved every
    /// newly-added static view of pre-existing messages. The invariant is
    /// still worth declaring and testing, so the field stays.
    #[allow(dead_code)]
    #[serde(default, deserialize_with = "null_default")]
    pub partition_axis: Option<String>,
}

fn default_source_regex() -> String {
    "^[0-9]".to_string()
}

#[derive(Debug, Deserialize)]
pub struct View {
    pub folder: String,
    pub predicate: PredicateNode,

    /// Time- and read-state windows go stale on their own; size, attachment
    /// and sender views are properties of the message and never change.
    ///
    /// Documentation only — `filters.rs` evaluates every view on every poll
    /// regardless. It used to skip non-volatile views for messages already
    /// carrying a `partition_axis` sentinel, which silently starved any
    /// NEWLY-ADDED static view of every pre-existing message (see the long
    /// comment in `filters::maintain_filters`). Kept in the schema because
    /// the rules data declares it and CI asserts it
    /// (9_others/test/test_mail_filter_views_partition.sh).
    #[allow(dead_code)]
    #[serde(default)]
    pub volatile: bool,

    /// Which axis this view belongs to (`size`, `time`, `state`, `attach`,
    /// `priority`, `sender`). Consumed by the CI partition test and by
    /// `toMaddyJson` (which selects `axis == "sender"`), not by this binary.
    #[allow(dead_code)]
    #[serde(default, deserialize_with = "null_default")]
    pub axis: Option<String>,
}

/// A filter-view predicate.
///
/// Internally tagged on `type`, so an unrecognised type fails at startup with
/// the offending value named. That is a deliberate behaviour change: the
/// Python fell through to `return False`, which turned one typo into a folder
/// that stays empty forever and looks exactly like a filter with no matches.
/// Adding a predicate to the JSON now requires adding it here — the cost of
/// making the failure impossible to miss.
#[derive(Debug, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Predicate {
    /// `size >= bytes`
    SizeMin { bytes: u64 },
    /// `size < bytes`
    SizeMax { bytes: u64 },
    /// Half-open `[min, max)`. Closed ranges double-filed a message of
    /// exactly `max` bytes into both this bucket and the next one up.
    SizeRange { min: u64, max: u64 },
    /// Received within the last `hours`.
    NewerThanHours { hours: f64 },
    /// Received longer than `hours` ago. Exact complement of
    /// `NewerThanHours` at the same `hours` value (strict `>`, so a message
    /// at exactly the boundary matches `NewerThanHours` — its `<=` — and not
    /// this one, keeping the pair from double-matching on the boundary).
    OlderThanHours { hours: f64 },
    /// `$seen` keyword absent.
    Unread,
    /// `$seen` keyword present. Exact complement of `Unread`.
    Read,
    /// Has a real (non-inline) attachment.
    HasAttachment,
    /// No real (non-inline) attachment. Exact complement of `HasAttachment`.
    NoAttachment,
    /// Attachment MIME type is one of `values` (compared lowercase).
    AttachType {
        #[serde(default, deserialize_with = "null_default")]
        values: Vec<String>,
    },
    /// Any of `values` (case-insensitive substring) appears in header
    /// `header`. Mirrors the route DSL's `header_contains` atom
    /// (`_shared/lib/mail-rules.nix::sieveAtom`) one-for-one, so a view's
    /// predicate can be copy-pasted verbatim from a route rule's `when`.
    HeaderContains {
        header: String,
        #[serde(default, deserialize_with = "null_default")]
        values: Vec<String>,
    },
    /// Sender's address domain is exactly one of `values` (case-insensitive).
    /// Mirrors the route DSL's `from_domain` atom one-for-one.
    FromDomain {
        #[serde(default, deserialize_with = "null_default")]
        values: Vec<String>,
    },
    /// Sender's address domain ends with one of `values`. Mirrors the route
    /// DSL's `from_domain_suffix` atom one-for-one.
    FromDomainSuffix {
        #[serde(default, deserialize_with = "null_default")]
        values: Vec<String>,
    },
    /// JMAP keyword `flag` is present. Only meaningful for flags the Sieve
    /// side actually emits — see `engines.stalwart` in mail-rules-general.json;
    /// a flag whose only emitting rule is "drop"/"route_only" never appears
    /// in `keywords` and this predicate silently never matches, same as any
    /// other view over data that was never computed.
    HasFlag { flag: String },
}

/// A predicate tree: `Atom` is a leaf [`Predicate`]; `AnyOf`/`AllOf`/`Not`
/// combine child trees. Combinators are NOT part of the `Predicate` tagged
/// enum (no `type` field distinguishes them in the JSON — the route DSL uses
/// the same untagged `{"any_of": [...]}` shape) so they get a hand-rolled
/// `Deserialize`: try each combinator key in turn, fall back to a `Predicate`
/// atom, and surface serde's own "unknown predicate.type" error unchanged
/// when even that fails — preserving the same fail-loud guarantee as a bare
/// `Predicate` for the common (atom, no combinator) case.
#[derive(Debug)]
pub enum PredicateNode {
    AnyOf(Vec<PredicateNode>),
    AllOf(Vec<PredicateNode>),
    Not(Box<PredicateNode>),
    Atom(Predicate),
}

impl<'de> Deserialize<'de> for PredicateNode {
    fn deserialize<D>(d: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = serde_json::Value::deserialize(d)?;
        Self::from_value(value).map_err(serde::de::Error::custom)
    }
}

impl PredicateNode {
    fn from_value(value: serde_json::Value) -> Result<Self, String> {
        let obj = value
            .as_object()
            .ok_or_else(|| format!("predicate must be a JSON object, got {value}"))?;
        if let Some(v) = obj.get("any_of") {
            let items = v.as_array().ok_or("any_of must be an array")?;
            return Ok(PredicateNode::AnyOf(
                items.iter().cloned().map(Self::from_value).collect::<Result<_, _>>()?,
            ));
        }
        if let Some(v) = obj.get("all_of") {
            let items = v.as_array().ok_or("all_of must be an array")?;
            return Ok(PredicateNode::AllOf(
                items.iter().cloned().map(Self::from_value).collect::<Result<_, _>>()?,
            ));
        }
        if let Some(v) = obj.get("not") {
            return Ok(PredicateNode::Not(Box::new(Self::from_value(v.clone())?)));
        }
        let atom: Predicate = serde_json::from_value(value).map_err(|e| e.to_string())?;
        Ok(PredicateNode::Atom(atom))
    }
}

impl Rules {
    pub fn load(path: &str) -> anyhow::Result<Self> {
        let raw = std::fs::read_to_string(path)
            .map_err(|e| anyhow::anyhow!("cannot read rules at {path}: {e}"))?;
        serde_json::from_str(&raw)
            .map_err(|e| anyhow::anyhow!("cannot parse rules at {path}: {e}"))
    }
}
