//! Typed schema for `mail-rules.json` (generated by `_shared/lib/mail-rules.nix`).
//!
//! The Python sorter read this file with `rules.get("filters") or {}` at every
//! access, so a renamed or misspelled key degraded to "feature absent" and the
//! container kept reporting healthy while quietly doing nothing. Every silent
//! mail-filing failure this session started that way.
//!
//! Here the schema is declared once and parsed once, at startup:
//!   * a missing required key is a startup error, not an empty default;
//!   * an unknown `predicate.type` is a startup error (see [`Predicate`]),
//!     where the Python returned `False` and produced a permanently empty
//!     filter folder that is indistinguishable from a working one;
//!   * keys the sorter does not consume (`routing`, `sieve_require`, ...) are
//!     ignored, because routing is owned by the native Sieve.

use serde::Deserialize;
use std::collections::BTreeMap;

/// Deserialize `null` as `T::default()`, not as an error.
///
/// JMAP peers and the rules generator both emit explicit `null` for "absent",
/// which plain `#[serde(default)]` (missing-key only) rejects.
pub fn null_default<'de, D, T>(d: D) -> Result<T, D::Error>
where
    D: serde::Deserializer<'de>,
    T: Default + Deserialize<'de>,
{
    Ok(Option::deserialize(d)?.unwrap_or_default())
}

#[derive(Debug, Deserialize)]
pub struct Rules {
    /// Mail account the sorter authenticates as. Required — without it there
    /// is nothing to log into, so failing here beats failing per-request.
    pub account: String,

    /// Routing targets, `key -> folder name`. Owned by the Sieve; the sorter
    /// only ensures the mailboxes exist and treats the names as valid.
    ///
    /// BTreeMap, not HashMap: iteration order decides the `sortOrder` handed to
    /// newly created mailboxes. Python dicts preserve JSON order, so the Python
    /// sorter was deterministic for free; a HashMap would hand a different
    /// sortOrder to every folder created after each container restart.
    pub folders: BTreeMap<String, String>,

    /// Visual section-header folders — flat ROOT siblings, not parents.
    #[serde(default, deserialize_with = "null_default")]
    pub folders_ui: Vec<String>,

    #[serde(default, deserialize_with = "null_default")]
    pub tags: Vec<TagGroup>,

    #[serde(default, deserialize_with = "null_default")]
    pub filters: Filters,

    #[serde(default, deserialize_with = "null_default")]
    pub folder_renames: FolderRenames,
}

#[derive(Debug, Deserialize)]
pub struct TagGroup {
    pub name: String,
    #[serde(default, deserialize_with = "null_default")]
    pub rules: Vec<TagRule>,
}

#[derive(Debug, Deserialize)]
pub struct TagRule {
    pub flag: String,
}

#[derive(Debug, Default, Deserialize)]
pub struct FolderRenames {
    /// `old name -> new name`, applied in place so the mailbox keeps its mail.
    /// BTreeMap for the same determinism reason as [`Rules::folders`] — renames
    /// are applied in iteration order and a chain must not reorder per run.
    #[serde(default, deserialize_with = "null_default")]
    pub map: BTreeMap<String, String>,
}

#[derive(Debug, Default, Deserialize)]
pub struct Filters {
    #[serde(default, deserialize_with = "null_default")]
    pub views: Vec<View>,

    #[serde(default, deserialize_with = "null_default")]
    pub section_headers: Vec<String>,

    /// Which mailbox names hold the messages the views range over. The Sieve
    /// files every inbound message into exactly one numeric `1*`-`9*` folder.
    #[serde(default = "default_source_regex")]
    pub source_folder_regex: String,

    /// Axis whose views tile their range exactly once, so membership in it is
    /// a reliable "static views already computed" sentinel. `None` disables
    /// the optimisation and every view is recomputed each poll.
    #[serde(default, deserialize_with = "null_default")]
    pub partition_axis: Option<String>,
}

fn default_source_regex() -> String {
    "^[0-9]".to_string()
}

#[derive(Debug, Deserialize)]
pub struct View {
    pub folder: String,
    pub predicate: Predicate,

    /// Time- and read-state windows go stale on their own and must be
    /// recomputed every poll; size and attachment views are properties of the
    /// message and never change.
    #[serde(default)]
    pub volatile: bool,

    #[serde(default, deserialize_with = "null_default")]
    pub axis: Option<String>,
}

/// A filter-view predicate.
///
/// Internally tagged on `type`, so an unrecognised type fails at startup with
/// the offending value named. That is a deliberate behaviour change: the
/// Python fell through to `return False`, which turned one typo into a folder
/// that stays empty forever and looks exactly like a filter with no matches.
/// Adding a predicate to the JSON now requires adding it here — the cost of
/// making the failure impossible to miss.
#[derive(Debug, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Predicate {
    /// `size >= bytes`
    SizeMin { bytes: u64 },
    /// `size < bytes`
    SizeMax { bytes: u64 },
    /// Half-open `[min, max)`. Closed ranges double-filed a message of
    /// exactly `max` bytes into both this bucket and the next one up.
    SizeRange { min: u64, max: u64 },
    /// Received within the last `hours`.
    NewerThanHours { hours: f64 },
    /// Received longer than `hours` ago. Exact complement of
    /// `NewerThanHours` at the same `hours` value (strict `>`, so a message
    /// at exactly the boundary matches `NewerThanHours` — its `<=` — and not
    /// this one, keeping the pair from double-matching on the boundary).
    OlderThanHours { hours: f64 },
    /// `$seen` keyword absent.
    Unread,
    /// `$seen` keyword present. Exact complement of `Unread`.
    Read,
    /// Has a real (non-inline) attachment.
    HasAttachment,
    /// No real (non-inline) attachment. Exact complement of `HasAttachment`.
    NoAttachment,
    /// Attachment MIME type is one of `values` (compared lowercase).
    AttachType {
        #[serde(default, deserialize_with = "null_default")]
        values: Vec<String>,
    },
}

impl Rules {
    pub fn load(path: &str) -> anyhow::Result<Self> {
        let raw = std::fs::read_to_string(path)
            .map_err(|e| anyhow::anyhow!("cannot read rules at {path}: {e}"))?;
        serde_json::from_str(&raw)
            .map_err(|e| anyhow::anyhow!("cannot parse rules at {path}: {e}"))
    }
}
