# AUTO-GENERATED by sync-topics.sh — do not edit manually
# Source: bc-obs_ntfy/src/topic-scanner.py CONFIGURED_TOPICS
[
  "vcs_commits"
  "vcs_pull-requests"
  "vcs_issues-releases"
  "cicd_deploy-digest"
  "infra_mesh-health"
  "infra_endpoints"
  "infra_dns"
  "infra_resources"
  "infra_containers"
  "ops_summary"
  "ops_backups"
  "ops_cron"
  "security_audit"
  "security_tls"
  "security_connections"
  "security_yara"
]
