#!/bin/sh
# Scrapes CONFIGURED_TOPICS from ntfy topic-scanner.py and generates ntfy-topics.nix
# Run this whenever ntfy topics change: ./sync-topics.sh
SCANNER="../../bc-obs_ntfy/src/topic-scanner.py"
OUT="ntfy-topics.nix"

if [ ! -f "$SCANNER" ]; then
  echo "ERROR: $SCANNER not found" >&2
  exit 1
fi

echo "# AUTO-GENERATED by sync-topics.sh — do not edit manually" > "$OUT"
echo "# Source: bc-obs_ntfy/src/topic-scanner.py CONFIGURED_TOPICS" >> "$OUT"
echo "[" >> "$OUT"
python3 -c "
import re, ast
src = open('$SCANNER').read()
m = re.search(r'CONFIGURED_TOPICS\s*=\s*\[(.*?)\]', src, re.DOTALL)
items = ast.literal_eval('[' + m.group(1) + ']')
for t in items:
    print(f'  \"{t}\"')
" >> "$OUT"
echo "]" >> "$OUT"
echo "Wrote $OUT with $(grep -c '\"' "$OUT") topics"
