#!/usr/bin/env bash
# ============================================================================
# test-mcp-contract.sh — hermes-agent must offer cloud-infra-mcp and
# cloud-cgc-pub-mcp to its model (#346).
#
# Hermes reads mcp_servers from configs/config.yaml (bind-mounted read-only at
# /opt/data/config.yaml). The block is a marked REGION generated by cloud-u-linux
# da_my-ai/data/claude/gen-mcp-tpl.sh from cloud-infra's derived server list,
# filtered by mcp-policy.json's container-hermes platform to cloud-cgc-pub-mcp
# + cloud-infra-mcp — the defect #184 found in the claude runner was a
# hand-written list whose names and urls drifted from the fleet's own
# declaration; a hand edit here now fails the generator-equality assertion
# below before any live probe runs. A wrong port still does not error at
# deploy time — the gateway starts, the server never connects, and the agent
# reasons blind — so the URL equality + live handshake checks stay.
#
# Declaring a server is also not the same as offering it. Hermes filters tools
# per platform: a platform_toolsets list that names no MCP server inherits every
# enabled one, but `no_mcp` removes them all and naming one server makes the
# list an allowlist that silently drops the other (hermes_cli/tools_config.py
# _merge_mcp_servers, Hermes Agent v0.21.2).
#
#   static  (always)            — both servers declared and not disabled, not
#                                 narrowed out of any platform, each URL
#                                 equals the fleet declaration (ip + container
#                                 port) when cloud-infra is checked out beside,
#                                 and the MCP region is EXACTLY what
#                                 gen-mcp-tpl.sh produces
#   live    (endpoint reachable) — each declared URL completes an MCP
#                                 initialize and lists tools
#
# Usage: src/test-mcp-contract.sh
# ============================================================================
set -uo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
INFRA="${CLOUD_INFRA_DIR:-$HERE/../../../cloud-infra}"

echo "== static: MCP region equals the generated MCP list =="
GEN="${CLAUDE_SOT_DIR:-$HERE/../../../cloud-u-linux/da_my-ai/data/claude}/gen-mcp-tpl.sh"
if [ -x "$GEN" ] && [ -f "$INFRA/1_cloud-configs/dist/mcp.json" ]; then
  if out=$(CLOUD_INFRA_DIR="$INFRA" GIT_BASE="$HERE/../../.." "$GEN" --check 2>&1); then
    printf '  ok   %s\n' "$(printf '%s' "$out" | tail -1)"
  else
    echo "  FAIL committed config has drifted from the generated MCP list"
    printf '%s\n' "$out" | sed 's/^/       /'
    exit 1
  fi
else
  echo "  (cloud-u-linux SoT or cloud-infra dist/ not checked out beside this repo — skipping)"
fi

python3 - "$HERE/configs/config.yaml" "$HERE/../build.json" "$INFRA/1_cloud-configs/dist" <<'PY'
import json, os, sys, urllib.request, yaml

config_path, build_path, dist_dir = sys.argv[1], sys.argv[2], sys.argv[3]
REQUIRED = ["cloud-infra-mcp", "cloud-cgc-pub-mcp"]
failed = False

def ok(message):
    print(f"  ok   {message}")

def bad(message):
    global failed
    failed = True
    print(f"  FAIL {message}")

# The committed file is a TEMPLATE: its model line reads @HERMES_MODEL@, filled
# at emission by flake.nix from build.json's runtime.model (#434). safe_load the
# text AFTER applying the same substitution, so this test asserts the file the
# container actually runs rather than crashing on the placeholder (which is
# exactly the "second declaration drifted" bug #434 removed).
config_text = open(config_path).read()
try:
    config = yaml.safe_load(config_text.replace("@HERMES_MODEL@", json.load(open(build_path))["runtime"]["model"]))
except Exception as error:
    bad(f"config could not be parsed after model substitution: {error}")
    print("FAIL")
    sys.exit(1)
servers = config.get("mcp_servers") or {}

print("== static: declaration ==")
for name in REQUIRED:
    entry = servers.get(name)
    if not entry:
        bad(f"{name}: not declared in mcp_servers")
    elif entry.get("enabled", True) is False:
        bad(f"{name}: declared but enabled: false")
    else:
        ok(f"{name}: declared -> {entry.get('url')}")

for platform, toolsets in (config.get("platform_toolsets") or {}).items():
    names = [str(toolset) for toolset in toolsets or []]
    listed = [name for name in names if name in servers]
    if "no_mcp" in names:
        bad(f"platform {platform}: no_mcp removes every MCP server")
    elif listed and set(REQUIRED) - set(listed):
        bad(f"platform {platform}: lists {listed}, an allowlist that drops {sorted(set(REQUIRED) - set(listed))}")
    else:
        ok(f"platform {platform}: inherits every enabled MCP server")

print("== static: URL matches the fleet declaration ==")
if not os.path.isdir(dist_dir):
    print(f"  (cloud-infra dist/ not checked out at {dist_dir} — skipping)")
else:
    for name in REQUIRED:
        declaration = json.load(open(os.path.join(dist_dir, f"build-{name}.json")))
        expected = f"http://{declaration['services'][name]['ip']}:{declaration['container']['port']}/mcp"
        actual = (servers.get(name) or {}).get("url")
        if actual == expected:
            ok(f"{name}: {actual}")
        else:
            bad(f"{name}: declared {actual}, fleet declares {expected}")

print("== live: MCP handshake against the declared URLs ==")
def post(url, body, session=None):
    headers = {"Content-Type": "application/json", "Accept": "application/json, text/event-stream"}
    if session:
        headers["Mcp-Session-Id"] = session
    request = urllib.request.Request(url, json.dumps(body).encode(), headers)
    return urllib.request.urlopen(request, timeout=30)

def result_of(response):
    for line in response.read().decode().splitlines():
        line = line.removeprefix("data: ").strip()
        if line.startswith("{"):
            message = json.loads(line)
            if "result" in message:
                return message["result"]
    return {}

for name in REQUIRED:
    url = (servers.get(name) or {}).get("url")
    if not url:
        continue
    try:
        response = post(url, {"jsonrpc": "2.0", "id": 1, "method": "initialize", "params": {
            "protocolVersion": "2025-06-18", "capabilities": {},
            "clientInfo": {"name": "hermes-test-mcp-contract", "version": "1"}}})
    except OSError as error:
        print(f"  (live SKIPPED for {name}: {url} unreachable from here — {error})")
        continue
    session = response.headers.get("Mcp-Session-Id")
    result_of(response)
    if not session:
        bad(f"{name}: initialize returned no Mcp-Session-Id")
        continue
    post(url, {"jsonrpc": "2.0", "method": "notifications/initialized"}, session).read()
    tools = result_of(post(url, {"jsonrpc": "2.0", "id": 2, "method": "tools/list", "params": {}}, session)).get("tools", [])
    if tools:
        ok(f"{name}: handshake + {len(tools)} tools")
    else:
        bad(f"{name}: handshake succeeded but tools/list returned nothing")

print("FAIL" if failed else "PASS")
sys.exit(1 if failed else 0)
PY
