{
  description = "ntfy Push Notifications + syslog-bridge + github-rss — dist layout v2";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.11";

  outputs = { self, nixpkgs }: let
    forAllSystems = nixpkgs.lib.genAttrs [ "x86_64-linux" "aarch64-linux" ];

    # ── Data sources (declarative JSON) ────────────────────────────
    buildJson    = builtins.fromJSON (builtins.readFile ../build.json);
    ntfyJson     = builtins.fromJSON (builtins.readFile ./build-ntfy.json);
    cNtfy        = ntfyJson.container;
    cSyslog      = (builtins.fromJSON (builtins.readFile ./build-syslog-bridge.json)).container;
    cGithubRss   = (builtins.fromJSON (builtins.readFile ./build-github-rss.json)).container;
    cRssGateway  = buildJson.containers."rss-gateway";
    usersJson    = (builtins.fromJSON (builtins.readFile ./users.json)).users;

    # ── profiles-config.json — baked from build.json at flake build time ──
    # Resolves profile.categories → matching topic objects so the rss-gateway
    # sidecar and Cloud Mail app can subscribe to ONE URL per profile group.
    allTopics   = buildJson.topics or [];
    allProfiles = buildJson.profiles or [];
    resolveProfile = p:
      let
        matched = if p ? "topics"
          then builtins.filter (t: builtins.elem t.name p.topics) allTopics
          else builtins.filter (t: builtins.elem t.category (p.categories or [])) allTopics;
      in {
        id       = p.id;
        title    = p.title;
        feed     = "/feed/${p.id}.atom";
        channels = map (t: {
          name = t.name;
          desc = t.desc;
          feed = "/feed/c/${t.name}.atom";
        }) matched;
      };
    profilesConfig = {
      version  = 1;
      base     = "https://${buildJson.domain}/feed";
      profiles = map resolveProfile allProfiles;
      channels = map (t: {
        name     = t.name;
        category = t.category;
        desc     = t.desc;
        feed     = "/feed/c/${t.name}.atom";
      }) allTopics;
    };
    # builtins.toFile: pure eval, no pkgs needed (pkgs is only in scope inside
    # the per-system lambda below). Engine's { name; src; } extraAssets form
    # strips the store-hash prefix so it lands as assets/profiles-config.json.
    profilesConfigAsset = builtins.toFile "profiles-config.json"
      (builtins.toJSON profilesConfig);

    # ── channels-config.json — the hierarchical RSS taxonomy for the Cloud Mail
    # SUPER RSS READER. Generated by 1_configs (build-ntfy-rss-channels.json,
    # symlinked into src/), just re-baked as an asset the gateway serves at
    # /feed/channels.json. Kept separate from profiles-config.json so the legacy
    # /feed/<profile>.atom flow stays byte-for-byte unchanged.
    channelsJson = builtins.fromJSON (builtins.readFile ./build-ntfy-rss-channels.json);
    channelsConfigAsset = builtins.toFile "channels-config.json"
      (builtins.toJSON channelsJson);

    engine = import ../../_shared/engine.nix;
    lib    = nixpkgs.lib;

    # ── users.json → init.sh @USER_BLOCKS@ ─────────────────────────
    # Each user becomes two shell lines: add (idempotent, may fail if
    # exists) + change-pass (updates if present). Role flag only for admins.
    mkUserBlock = u: let
      pw    = "$" + u.password_env;   # literal shell var reference
      role  = if u.role == "admin" then "--role=admin " else "";
    in
      "NTFY_PASSWORD=\"${pw}\" ntfy user add ${role}${u.username} 2>/dev/null || true\n"
      + "NTFY_PASSWORD=\"${pw}\" ntfy user change-pass ${u.username} 2>/dev/null || true";

    userBlocks = lib.concatMapStringsSep "\n" mkUserBlock usersJson;

  in {
    packages = forAllSystems (system: let
      pkgs = nixpkgs.legacyPackages.${system};
    in {
      default = engine {
        inherit pkgs buildJson;
        container = { container = cNtfy; };  # engine expects .container subkey
        srcDir = ./.;
        templates = [
          {
            name = "server.yml";
            vars = {
              DOMAIN = buildJson.domain;
              PORT   = toString buildJson.ports.app;
            };
          }
          {
            name = "init.sh";
            vars = {
              USER_BLOCKS = userBlocks;
            };
          }
        ];
        composeSpec = import ./compose.nix {
          inherit buildJson cNtfy cSyslog cGithubRss cRssGateway;
          # Pass full ntfy container JSON so compose can read svc.<name>.ip
          # for the Tier-3 wg-only bind (cloud-data-driven; never hardcoded).
          containerNtfy = ntfyJson;
        };
        extraAssets = [
          ./code/syslog-to-ntfy.py
          ./code/github-rss-to-ntfy.py
          ./code/topic-scanner.py
          ./code/rss-gateway.py
          # Enterprise notification broker + daily/weekly digest (§4A/§4C).
          # Policy (severity/routing/dedup/flap/escalation/recovery) is data in
          # build-notify.json (symlink → 1_configs/dist/build-notify.json), read
          # by the broker at /app/build-notify.json. Producers POST events to the
          # broker on :8092 instead of the health_resources firehose — see
          # MIGRATION-notify-broker.md for the event contract.
          ./code/notify-broker.py
          ./code/notify-digest.py
          { name = "build-notify.json"; src = ./build-notify.json; }
          { name = "profiles-config.json"; src = profilesConfigAsset; }
          { name = "channels-config.json"; src = channelsConfigAsset; }
        ];
        title = "ntfy Push Notifications + syslog-bridge + github-rss";
      };
    });
  };
}
