#!/usr/bin/env bash
# ╔══════════════════════════════════════════════════════════════════════════╗
# ║ Guard — every live service's src/build-*.json must resolve to a file      ║
# ║ that EXISTS in cloud-infra's 1_cloud-configs/dist.                       ║
# ╚══════════════════════════════════════════════════════════════════════════╝
#
# THE DEFECT (#564, measured 2026-09-24)
#
# A service's src/flake.nix reads its per-container config by NAME:
#
#     container = builtins.fromJSON (builtins.readFile ./build-cloud-agi-claude.json);
#
# and that name is GENERATED by cloud-infra, as `build-${containerName}.json`
# where containerName is `containers.<role>.container_name` falling back to the
# service name (cloud-infra 1_cloud-configs/src/derive/cloud-data-config-derive.ts).
#
# So renaming containers.app.container_name MOVES a filename in cloud-infra's
# dist. It is not a one-field change. #542 renamed three agent containers to
# cloud-agi-* and produced all three possible outcomes:
#
#   LOUD    user-ai_my-ai_claude-api kept the old symlink name. nix reads from
#           git, so the missing target is "Path '...src/build-my-ai_claude-api.json'
#           does not exist in Git repository". Ship run 35995862469 died there.
#   LATENT  user-ai_hermes-agent had the identical dangling symlink and had
#           simply not shipped yet.
#   SILENT  user-ai_my-ai-api was a 52,827-byte REGULAR FILE, not a symlink,
#           whose dist name was also gone. It BUILT — from a frozen pre-rename
#           config — and nothing could report it. Worse than the loud failure.
#
# #542's own naming tester asserted container_name VALUES and went green.
# Nothing asserted the declaration still RESOLVES. That is this file.
#
# WHY THIS GUARD LIVES IN *THIS* REPO TOO
#
# cloud-infra carries the same guard as a registered tester, but cloud-infra's
# lint-pipeline runs on cloud-infra pushes, and the gen-configs commit a
# containers-push produces is tagged [skip ci]. So a rename made HERE would not
# reach that guard until some unrelated cloud-infra push — long after the rename
# landed. The rename happens in this repository, so the check has to run here,
# on this push, which is the whole point of #368/#486: an unregistered guard is
# indistinguishable from no guard.
#
# WHY A NAME MISSING FROM dist IS NOT AUTOMATICALLY A FAILURE
#
# dist is regenerated by cloud-infra's ship-gen-configs, which is dispatched by
# a push here and commits afterwards. On the very push that performs a rename,
# dist still holds the OLD name and not yet the new one. A strict "must be in
# dist" check would go red on every correct rename and green one cycle later —
# noise that teaches people to ignore it. So a name absent from dist passes ONLY
# when the SERVICE'S OWN build.json declares it, i.e. when it is exactly what
# the emitter is about to write. That is lag-immune and still catches #542:
# after the rename nothing declares container_name my-ai_claude-api, so a stale
# symlink fails at the commit that broke it.
#
# Usage: bash .github/scripts/check-build-json-targets.sh            # check the tree
#        bash .github/scripts/check-build-json-targets.sh --self-test # mutation proof
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
INFRA_REPO="${INFRA_REPO:-diegonmarcos/cloud-infra}"
DIST_PATH="1_cloud-configs/dist"

FAIL=0
pass() { printf "  ✓ %s\n" "$1"; }
fail() { printf "  ✗ %s\n" "$1" >&2; FAIL=1; }
note() { printf "  · %s\n" "$1"; }

command -v jq >/dev/null || { echo "::error::jq is required"; exit 1; }

# ── The emitter's own naming rule, applied to ONE build.json ────────────────
# PER-SERVICE on purpose. A first cut unioned these names fleet-wide and BOTH of
# #542's stale spellings passed it, because some unrelated service's `.name`
# collided with the retired name. A service's own readFile target must be a name
# THAT service declares.
emit_expected_names() {
    jq -r '
      (.name // "") as $n
      | (.containers // {}) | to_entries[]
      | ("build-" + (.value.container_name // $n) + ".json"),
        (if (.value.db_engine // "") != "" then "build-" + .value.db_engine + ".json" else empty end)
    ' "$1" 2>/dev/null | grep -v '^build-\.json$' | sort -u
}

# ── The check. Pure over (services tree, dist filename list). ─────────────
# Returns 0 clean, 1 on any violation. Never exits, so --self-test can call it
# repeatedly.
check_tree() {
    local svcroot="$1" distlist="$2" quiet="${3:-}"
    local rc=0 own fleet frozen_unread=0 frozen_read=0 _b
    # The union is for cross-references only: a link into ANOTHER service's
    # generated config is legitimately named after that service.
    fleet="$(for _b in "$svcroot"/*/build.json; do [ -f "$_b" ] && emit_expected_names "$_b"; done | sort -u)"

    _in_dist() { grep -qxF "$1" "$distlist"; }
    _own()     { printf '%s\n' "$own"   | grep -qxF "$1"; }
    _fleet()   { printf '%s\n' "$fleet" | grep -qxF "$1"; }
    _say()     { [ -n "$quiet" ] || printf '%s\n' "$1"; }

    local bj svc flake ref path target base
    for bj in "$svcroot"/*/build.json; do
        [ -f "$bj" ] || continue
        svc="$(basename "$(dirname "$bj")")"
        flake="$svcroot/$svc/src/flake.nix"
        own="$(emit_expected_names "$bj")"

        # ── A) every name a flake.nix actually READS ──────────────────────
        if [ -f "$flake" ]; then
            while IFS= read -r ref; do
                [ -n "$ref" ] || continue
                path="$svcroot/$svc/src/$ref"
                if [ -L "$path" ]; then
                    target="$(readlink "$path")"; base="$(basename "$target")"
                    # -e is useless here: these links point at
                    # ../../../1_cloud-configs/dist/, which resolves only in the
                    # BUILDER layout (this repo checked out AT
                    # cloud-infra/a_solutions/). So they look dangling on a dev
                    # box and in a plain CI checkout, correctly. Compare
                    # BASENAMES against the real dist listing instead.
                    if _in_dist "$base"; then
                        :
                    elif _own "$base"; then
                        _say "  · $svc/src/$ref → $base: not in dist YET, but $svc/build.json declares that container_name (gen-configs lag) — OK"
                    else
                        _say "  ✗ $svc/src/$ref → $base: NOT in cloud-infra dist, and $svc/build.json declares [$(printf '%s' "$own" | tr '\n' ' ')]. flake.nix readFile will fail with \"does not exist in Git repository\". A container rename moved this name." >&2
                        rc=1
                    fi
                elif [ -f "$path" ]; then
                    # A regular file is a FROZEN copy: it cannot fail loudly, so
                    # the only signal that a rename moved past it is that dist no
                    # longer carries its name.
                    if _in_dist "$ref"; then
                        frozen_read=$((frozen_read + 1))
                        _say "  · $svc/src/$ref: regular file, not a symlink — builds from a frozen copy, dist still carries the name (#564, not failed here)"
                    else
                        _say "  ✗ $svc/src/$ref: regular file AND no such name in cloud-infra dist. This service builds from a frozen pre-rename config and cannot fail loudly about it — the user-ai_my-ai-api shape (#564)." >&2
                        rc=1
                    fi
                else
                    _say "  ✗ $svc/src/flake.nix reads ./$ref but no such file exists in the service tree." >&2
                    rc=1
                fi
            done < <(grep -oE 'readFile \./build-[A-Za-z0-9._-]+\.json' "$flake" 2>/dev/null | sed 's|.*\./||' | sort -u)
        fi

        # ── B) every build-*.json SYMLINK under src/, read or not ─────────
        # A dangling one is dead weight that reads as a live cross-reference.
        # Two (build-my-ai_claude-api.json under infra-api_cloud-mattermost-mcp
        # and infra-api_google-workspace-mcp) survived #542 and made the rename
        # look like it had more live consumers than it had.
        while IFS= read -r path; do
            [ -n "$path" ] || continue
            target="$(readlink "$path")"; base="$(basename "$target")"
            _in_dist "$base" && continue
            _fleet "$base" && continue
            _say "  ✗ ${path#$svcroot/}: symlink → $base, which is neither in cloud-infra dist nor declared by any build.json in the fleet." >&2
            rc=1
        done < <(find "$svcroot/$svc/src" -name 'build-*.json' -type l 2>/dev/null | sort)
    done

    # ── C) report-only ───────────────────────────────────────────────────
    frozen_unread=$(find "$svcroot"/*/src -name 'build-*.json' -type f 2>/dev/null | wc -l)
    _say "  · $frozen_unread build-*.json exist as REGULAR FILES across live service src/ trees ($frozen_read of them are a flake readFile target). Reported, not failed: converting a frozen copy to a link can change what a container builds from."

    unset -f _in_dist _own _fleet _say
    return $rc
}

TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT

# ══════════════════════════════════════════════════════════════════════════
# MUTATION PROOF. A guard that only ever sees a clean tree is indistinguishable
# from `exit 0` — the defect shape the fleet keeps rediscovering. Each case
# breaks the tree in exactly one of the ways #542 broke it, plus one asserting
# the guard does NOT fire on a correct rename (a guard that cries wolf on every
# rename gets ignored, and is then not a guard).
self_test() {
    echo "── mutation proof ──"
    local FDIST="$TMP/dist.txt"
    printf 'build-cloud-agi-alpha.json\nbuild-svc-b.json\n' > "$FDIST"

    mk_fixture() {
        local root="$TMP/$1"; rm -rf "$root"; mkdir -p "$root/svc-a/src" "$root/svc-b/src"
        printf '{"name":"svc-a","containers":{"app":{"container_name":"cloud-agi-alpha"}}}\n' > "$root/svc-a/build.json"
        printf '{"name":"svc-b","containers":{"app":{}}}\n'                                  > "$root/svc-b/build.json"
        printf 'container = builtins.fromJSON (builtins.readFile ./build-cloud-agi-alpha.json);\n' > "$root/svc-a/src/flake.nix"
        printf 'container = builtins.fromJSON (builtins.readFile ./build-svc-b.json);\n'           > "$root/svc-b/src/flake.nix"
        ln -s ../../../1_cloud-configs/dist/build-cloud-agi-alpha.json "$root/svc-a/src/build-cloud-agi-alpha.json"
        ln -s ../../../1_cloud-configs/dist/build-svc-b.json           "$root/svc-b/src/build-svc-b.json"
        printf '%s\n' "$root"
    }
    expect() { # expect <0|1> <label> <tree>
        local want="$1" label="$2" tree="$3" got
        check_tree "$tree" "$FDIST" quiet >/dev/null 2>&1; got=$?
        if [ "$got" -eq "$want" ]; then pass "$label (exit $got)"
        else fail "$label — expected exit $want, got $got. This guard does not detect what it claims to."; fi
    }

    # M1 — a clean fixture must pass, or nothing below proves anything.
    expect 0 "clean tree passes" "$(mk_fixture m1)"

    # M2 — the claude-api / hermes shape: symlink kept the pre-rename name.
    local T; T="$(mk_fixture m2)"
    rm "$T/svc-a/src/build-cloud-agi-alpha.json"
    ln -s ../../../1_cloud-configs/dist/build-old-name.json "$T/svc-a/src/build-cloud-agi-alpha.json"
    expect 1 "flake's symlink target missing from dist is caught" "$T"

    # M3 — the my-ai-api shape: readFile target is a REGULAR FILE whose dist
    #      name is gone. Builds fine, silently, from a pre-rename config.
    T="$(mk_fixture m3)"
    rm "$T/svc-a/src/build-cloud-agi-alpha.json"
    printf '{"container":{"container_name":"stale"}}\n' > "$T/svc-a/src/build-gone.json"
    printf 'container = builtins.fromJSON (builtins.readFile ./build-gone.json);\n' > "$T/svc-a/src/flake.nix"
    expect 1 "frozen regular file whose dist name is gone is caught" "$T"

    # M4 — a dangling build-*.json symlink no flake reads: the two vestigial
    #      build-my-ai_claude-api.json cross-references #542 left behind.
    T="$(mk_fixture m4)"
    ln -s ../../../1_cloud-configs/dist/build-retired.json "$T/svc-b/src/build-retired.json"
    expect 1 "dangling symlink that no flake reads is caught" "$T"

    # M5 — a CORRECT rename pushed before gen-configs refreshed dist. Must NOT
    #      fire, or this guard reds every rename once and gets ignored.
    T="$(mk_fixture m5)"
    printf '{"name":"svc-a","containers":{"app":{"container_name":"cloud-agi-renamed"}}}\n' > "$T/svc-a/build.json"
    rm "$T/svc-a/src/build-cloud-agi-alpha.json"
    ln -s ../../../1_cloud-configs/dist/build-cloud-agi-renamed.json "$T/svc-a/src/build-cloud-agi-renamed.json"
    printf 'container = builtins.fromJSON (builtins.readFile ./build-cloud-agi-renamed.json);\n' > "$T/svc-a/src/flake.nix"
    expect 0 "a correct rename not yet in dist does NOT false-red" "$T"

    # M6 — flake reads a name with no file at all.
    T="$(mk_fixture m6)"
    printf 'container = builtins.fromJSON (builtins.readFile ./build-absent.json);\n' > "$T/svc-a/src/flake.nix"
    expect 1 "flake reading a name with no file at all is caught" "$T"
}

if [ "${1:-}" = "--self-test" ]; then
    self_test
    echo ""
    [ "$FAIL" -eq 0 ] && echo "PASS: the guard is proven to detect what it claims to." || echo "FAIL: see ✗ above"
    exit "$FAIL"
fi

# ══════════════════════════════════════════════════════════════════════════
echo "── every live service's src/build-*.json resolves in cloud-infra dist ──"

# The dist LISTING is all this needs — filenames, not contents — so it is one
# API call rather than a second checkout. cloud-infra is public, so the
# workflow's own GITHUB_TOKEN reads it; no cross-repo secret.
DISTLIST="$TMP/dist.txt"
if ! gh api "repos/$INFRA_REPO/contents/$DIST_PATH" \
       --jq '.[] | select(.type == "file") | .name' 2>/dev/null \
     | grep '^build-.*\.json$' | sort > "$DISTLIST"; then
    # Not a skip. A guard that could not read the listing verified nothing, and
    # must never be the reason a run is green (#368).
    echo "::error::could not list $INFRA_REPO/$DIST_PATH — this guard verified nothing. Check GH_TOKEN and that the path still exists."
    exit 1
fi
[ -s "$DISTLIST" ] && [ "$(wc -l < "$DISTLIST")" -ge 50 ] || {
    echo "::error::$INFRA_REPO/$DIST_PATH listed $(wc -l < "$DISTLIST") build-*.json. The fleet has >100; a listing this short means the request was truncated or the path moved, not that the fleet shrank. Refusing to pass on it."
    exit 1
}
note "$(wc -l < "$DISTLIST") build-*.json in $INFRA_REPO/$DIST_PATH"

if check_tree "$REPO_ROOT" "$DISTLIST"; then
    pass "every live service's src/build-*.json resolves to a real dist file"
else
    fail "at least one src/build-*.json does not resolve — see the ✗ lines above. A container rename moves this generated filename; fix the symlink (and the flake.nix readFile) to the new container_name."
fi

echo ""
[ "$FAIL" -eq 0 ] && echo "PASS" || echo "FAIL"
exit "$FAIL"
