# Host networking: dovecot listens on internal ports only
# Front nginx handles external ports (993) with proxy protocol

service imap-login {
  inet_listener imap {
    port = 10143
  }
  inet_listener imaps {
    port = 10993
    ssl = yes
  }
}

service lmtp {
  inet_listener lmtp {
    port = 2525
  }
}

service managesieve-login {
  inet_listener sieve {
    port = 14190
  }
}
