{
  description = "Caddy public-edge L7 allowlist (oci-analytics) — dist layout v2";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.11";

  outputs = { self, nixpkgs }: let
    forAllSystems = nixpkgs.lib.genAttrs [ "x86_64-linux" "aarch64-linux" ];

    buildJson   = builtins.fromJSON (builtins.readFile ../build.json);
    caddyPublic = builtins.fromJSON (builtins.readFile ./build-caddy-public.json);

    engine = import ../../_shared/engine.nix;
    lib    = nixpkgs.lib;

    caddyfileText = import ./caddyfile-public.nix { inherit lib caddyPublic; };

    templates = [
      { name = "Caddyfile"; text = caddyfileText; }
    ];

  in {
    packages = forAllSystems (system: let
      pkgs = nixpkgs.legacyPackages.${system};
      engineOut = engine {
        inherit pkgs buildJson templates;
        container = caddyPublic;
        srcDir = ./.;
        composeSpec = import ./compose.nix { inherit buildJson; container = caddyPublic; };
        title = "Caddy Public";
      };
      svcPath = "a_solutions/infra-sec_caddy-public";
      htmlBanner = ''
        <!-- ══════════════════════════════════════════════════════════════════ -->
        <!-- DO NOT EDIT — AUTO-GENERATED by _shared/engine.nix (overlay)     -->
        <!-- Source:  ${svcPath}/src/flake.nix                                -->
        <!-- Rebuild: ${svcPath}/build.sh ship                                -->
        <!-- ══════════════════════════════════════════════════════════════════ -->
      '';
      htmlBannerFile = pkgs.writeText "banner.html" htmlBanner;
      withBanner = src: pkgs.runCommand (baseNameOf src) {} ''
        cat ${htmlBannerFile} ${src} > $out
      '';
    in {
      default = pkgs.runCommand "${buildJson.name}-dist-v2-overlay" {
        passthru = engineOut.passthru;
      } ''
        cp -r ${engineOut} $out
        chmod -R u+w $out
        cp ${withBanner ./error.html} $out/configs/error.html
      '';
    });
  };
}
