[package]
name = "http-to-smtp-proxy-api"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "http-to-smtp-proxy-api"
path = "main.rs"

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["full"] }
lettre = { version = "0.11", default-features = false, features = ["tokio1-rustls-tls", "smtp-transport", "builder"] }
hickory-resolver = { version = "0.24", features = ["tokio-runtime"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
lto = false
codegen-units = 8
