use crate::types::*;
use chrono::{Datelike, NaiveDate, Utc};
use reqwest::Client;
use std::time::Duration;
use tokio::time::timeout;
use trust_dns_resolver::config::{NameServerConfig, Protocol, ResolverConfig, ResolverOpts};
use trust_dns_resolver::TokioAsyncResolver;

const HTTP_TIMEOUT: Duration = Duration::from_secs(5);

/// Stable marker embedded in Caddy's global wildcard fallback ("wormhole")
/// page. The edge serves this auto-generated HTML with HTTP 200 for ANY
/// unrouted `*.diegonmarcos.com` host/path, which would otherwise false-green
/// a down/misrouted service. Emitted verbatim by the `_shared/engine.nix`
/// overlay that builds the fallback page, so matching it is exact, not a guess.
const EDGE_FALLBACK_MARKER: &str = "AUTO-GENERATED by _shared/engine.nix";

fn http_client() -> Client {
    Client::builder()
        .timeout(HTTP_TIMEOUT)
        .danger_accept_invalid_certs(true)
        .redirect(reqwest::redirect::Policy::none())
        .build()
        .unwrap()
}

fn auth_client(token: &str) -> Client {
    let mut headers = reqwest::header::HeaderMap::new();
    headers.insert(
        "Authorization",
        format!("Bearer {}", token).parse().unwrap(),
    );
    Client::builder()
        .timeout(Duration::from_secs(10))
        .danger_accept_invalid_certs(true)
        .default_headers(headers)
        .build()
        .unwrap()
}

async fn check_endpoint_once(client: &Client, url: &str) -> (u16, bool) {
    match timeout(HTTP_TIMEOUT, client.get(url).send()).await {
        Ok(Ok(resp)) => {
            let status = resp.status().as_u16();
            let fallback = if (200..=299).contains(&status) {
                match timeout(HTTP_TIMEOUT, resp.text()).await {
                    Ok(Ok(body)) => body.contains(EDGE_FALLBACK_MARKER),
                    _ => false,
                }
            } else {
                false
            };
            (status, fallback)
        }
        _ => (0, false),
    }
}

/// Check endpoint HTTP status with latency measurement.
///
/// 2026-07-03: a whole batch (all ~76 endpoints, including ones verified
/// live seconds later by hand) reported HTTP 0 in one run — self-contention
/// from firing every check fully unbounded-concurrent on a 2-vCPU GHA
/// runner (76 simultaneous TLS handshakes) delays individual task polls
/// past the 5s timeout even though the target is healthy. One retry after
/// a short backoff absorbs that transient scheduling jitter without
/// masking a genuinely down endpoint (which still fails both attempts).
pub async fn check_endpoint(ep: &EndpointCheck) -> EndpointResult {
    let client = http_client();
    let start = std::time::Instant::now();
    let (mut code, mut edge_fallback) = check_endpoint_once(&client, &ep.url).await;
    if code == 0 {
        tokio::time::sleep(Duration::from_millis(500)).await;
        let (code2, fallback2) = check_endpoint_once(&client, &ep.url).await;
        code = code2;
        edge_fallback = fallback2;
    }
    let latency_ms = start.elapsed().as_millis() as u64;
    EndpointResult {
        service: ep.service.clone(),
        url: ep.url.clone(),
        status_code: code,
        latency_ms,
        edge_fallback,
    }
}

/// Check TLS certificate expiry via openssl CLI
pub async fn check_cert(domain: &str) -> CertResult {
    let output = timeout(
        Duration::from_secs(8),
        tokio::process::Command::new("sh")
            .args([
                "-c",
                &format!(
                    "echo | openssl s_client -servername {} -connect {}:443 2>/dev/null | openssl x509 -noout -enddate 2>/dev/null | cut -d= -f2",
                    domain, domain
                ),
            ])
            .output(),
    )
    .await;

    let expiry_raw = output
        .ok()
        .and_then(|r| r.ok())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_default();

    if expiry_raw.is_empty() {
        return CertResult { domain: domain.into(), days_left: -1, expiry: "N/A".into() };
    }

    // Parse date
    let days_left = tokio::process::Command::new("date")
        .args(["-d", &expiry_raw, "+%s"])
        .output()
        .await
        .ok()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .and_then(|s| s.parse::<i64>().ok())
        .map(|epoch| {
            let now = chrono::Utc::now().timestamp();
            (epoch - now) / 86400
        })
        .unwrap_or(-1);

    CertResult { domain: domain.into(), days_left, expiry: expiry_raw }
}

/// DNS lookups for diegonmarcos.com
pub async fn check_dns() -> Vec<DnsResult> {
    let mut rc = ResolverConfig::new();
    rc.add_name_server(NameServerConfig::new(
        "1.1.1.1:53".parse().unwrap(),
        Protocol::Udp,
    ));
    let mut opts = ResolverOpts::default();
    opts.timeout = Duration::from_secs(5);
    let resolver = TokioAsyncResolver::tokio(rc, opts);

    let mut results = Vec::new();

    // MX
    let mx_val = match resolver.mx_lookup("diegonmarcos.com").await {
        Ok(mx) => mx.iter().next().map(|m| format!("{} {}", m.preference(), m.exchange())).unwrap_or_default(),
        Err(_) => String::new(),
    };
    results.push(DnsResult { record_type: "MX".into(), value: mx_val });

    // SPF
    let spf_val = match resolver.txt_lookup("diegonmarcos.com").await {
        Ok(txt) => txt.iter().find(|t| t.to_string().contains("v=spf1")).map(|t| t.to_string()).unwrap_or_default(),
        Err(_) => String::new(),
    };
    results.push(DnsResult { record_type: "SPF".into(), value: spf_val });

    // DKIM
    let dkim_val = match resolver.txt_lookup("default._domainkey.diegonmarcos.com").await {
        Ok(txt) => txt.iter().next().map(|t| t.to_string()).unwrap_or_default(),
        Err(_) => String::new(),
    };
    results.push(DnsResult { record_type: "DKIM".into(), value: dkim_val });

    // DMARC
    let dmarc_val = match resolver.txt_lookup("_dmarc.diegonmarcos.com").await {
        Ok(txt) => txt.iter().next().map(|t| t.to_string()).unwrap_or_default(),
        Err(_) => String::new(),
    };
    results.push(DnsResult { record_type: "DMARC".into(), value: dmarc_val });

    results
}

/// Load repo list + max_runs from cloud-data-workflows.json (declarative).
/// Falls back to the legacy 3-repo list only if the JSON is missing —
/// existing deployments keep working while the config file rolls out.
fn workflows_config() -> (Vec<String>, usize) {
    use reports_common::context::find_cloud_data_file;
    let legacy = (
        vec![
            "diegonmarcos/cloud-infra".to_string(),
            "diegonmarcos/front".to_string(),
            "diegonmarcos/cloud-data".to_string(),
        ],
        20usize,
    );
    // Migrated to build-reports.json:.workflows. Falls back to legacy
    // cloud-data-workflows.json (now in z_archive) for back-compat.
    let v: serde_json::Value = if let Some(section) = reports_common::context::load_build_reports_section("workflows") {
        section
    } else {
        let path = match find_cloud_data_file("cloud-data-workflows.json") {
            Some(p) => p,
            None => return legacy,
        };
        let bytes = match std::fs::read(&path) {
            Ok(b) => b,
            Err(_) => return legacy,
        };
        match serde_json::from_slice::<serde_json::Value>(&bytes) {
            Ok(v) => v,
            Err(_) => return legacy,
        }
    };
    let repos: Vec<String> = v["github"]["repos"]
        .as_array()
        .map(|arr| {
            arr.iter()
                .filter_map(|x| x.as_str().map(|s| s.to_string()))
                .collect()
        })
        .unwrap_or_else(|| legacy.0.clone());
    let max = v["github"]["max_runs_per_repo"].as_u64().unwrap_or(20) as usize;
    (repos, max)
}

/// Fetch GHA workflow runs from every repo declared in cloud-data-workflows.json.
pub async fn fetch_gha(github_token: &str) -> Vec<GhaRun> {
    let client = auth_client(github_token);
    let (repos, max_runs) = workflows_config();

    let futs: Vec<_> = repos.iter().map(|repo| {
        let c = client.clone();
        let repo = repo.to_string();
        let max_runs = max_runs;
        async move {
            let url = format!(
                "https://api.github.com/repos/{}/actions/runs?per_page={}&status=completed",
                repo, max_runs
            );
            let resp = timeout(
                Duration::from_secs(10),
                c.get(&url)
                    .header("User-Agent", "cloud-health-daily-mail")
                    .send(),
            )
            .await;

            let json: serde_json::Value = match resp {
                Ok(Ok(r)) if r.status().is_success() => r.json().await.unwrap_or_default(),
                _ => return vec![],
            };

            let repo_short = repo.split('/').last().unwrap_or("?").to_string();
            json["workflow_runs"]
                .as_array()
                .map(|runs| {
                    runs.iter()
                        .take(20)
                        .map(|r| GhaRun {
                            name: r["name"].as_str().unwrap_or("?").to_string(),
                            repo: repo_short.clone(),
                            conclusion: r["conclusion"].as_str().unwrap_or("?").to_string(),
                            created_at: r["created_at"].as_str().unwrap_or("").to_string(),
                            html_url: r["html_url"].as_str().unwrap_or("").to_string(),
                        })
                        .collect::<Vec<_>>()
                })
                .unwrap_or_default()
        }
    }).collect();

    let results = futures::future::join_all(futs).await;
    let mut all_runs: Vec<GhaRun> = results.into_iter().flatten().collect();
    // Sort by created_at descending (most recent first)
    all_runs.sort_by(|a, b| b.created_at.cmp(&a.created_at));
    all_runs
}

/// Fetch GHA workflow definitions from every repo declared in cloud-data-workflows.json.
pub async fn fetch_gha_workflows(github_token: &str) -> Vec<GhaWorkflow> {
    let client = auth_client(github_token);
    let (repos, _max_runs) = workflows_config();

    let futs: Vec<_> = repos.iter().map(|repo| {
        let c = client.clone();
        let repo = repo.to_string();
        async move {
            let url = format!(
                "https://api.github.com/repos/{}/actions/workflows?per_page=50",
                repo
            );
            let resp = timeout(
                Duration::from_secs(10),
                c.get(&url)
                    .header("User-Agent", "cloud-health-daily-mail")
                    .send(),
            )
            .await;

            let json: serde_json::Value = match resp {
                Ok(Ok(r)) if r.status().is_success() => r.json().await.unwrap_or_default(),
                _ => return vec![],
            };

            let repo_short = repo.split('/').last().unwrap_or("?").to_string();

            // For each workflow, fetch latest run to get conclusion
            let workflows = json["workflows"].as_array().cloned().unwrap_or_default();
            let mut results = Vec::new();

            for wf in &workflows {
                let wf_id = wf["id"].as_u64().unwrap_or(0);
                let name = wf["name"].as_str().unwrap_or("?").to_string();
                let state = wf["state"].as_str().unwrap_or("unknown").to_string();
                let path = wf["path"].as_str().unwrap_or("").to_string();

                // Fetch latest run for this workflow
                let run_url = format!(
                    "https://api.github.com/repos/{}/actions/workflows/{}/runs?per_page=1&status=completed",
                    repo, wf_id
                );
                let (last_conclusion, last_run_at) = match timeout(
                    Duration::from_secs(8),
                    c.get(&run_url)
                        .header("User-Agent", "cloud-health-daily-mail")
                        .send(),
                ).await {
                    Ok(Ok(r)) if r.status().is_success() => {
                        let rj: serde_json::Value = r.json().await.unwrap_or_default();
                        let runs = rj["workflow_runs"].as_array();
                        match runs.and_then(|a| a.first()) {
                            Some(run) => (
                                run["conclusion"].as_str().unwrap_or("none").to_string(),
                                run["created_at"].as_str().unwrap_or("").to_string(),
                            ),
                            None => ("never_run".to_string(), String::new()),
                        }
                    }
                    _ => ("unknown".to_string(), String::new()),
                };

                results.push(GhaWorkflow {
                    name,
                    repo: repo_short.clone(),
                    state,
                    path,
                    last_conclusion,
                    last_run_at,
                });
            }

            results
        }
    }).collect();

    let results = futures::future::join_all(futs).await;
    results.into_iter().flatten().collect()
}

/// Fetch GHCR packages + GitHub disk usage
pub async fn fetch_ghcr(github_token: &str) -> (Vec<GhcrPackage>, usize, u64) {
    let client = auth_client(github_token);

    // Fetch packages and user disk usage in parallel
    let (pkgs_resp, user_resp) = tokio::join!(
        timeout(Duration::from_secs(10),
            client.get("https://api.github.com/user/packages?package_type=container&per_page=100")
                .header("User-Agent", "cloud-health-daily-mail").send()),
        timeout(Duration::from_secs(10),
            client.get("https://api.github.com/user")
                .header("User-Agent", "cloud-health-daily-mail").send()),
    );

    let pkgs_json: serde_json::Value = match pkgs_resp {
        Ok(Ok(r)) => r.json().await.unwrap_or_default(),
        _ => return (vec![], 0, 0),
    };

    let disk_kb = match user_resp {
        Ok(Ok(r)) => {
            let j: serde_json::Value = r.json().await.unwrap_or_default();
            j["disk_usage"].as_u64().unwrap_or(0)
        }
        _ => 0,
    };

    let arr = pkgs_json.as_array().cloned().unwrap_or_default();
    let total = arr.len();

    let mut pkgs: Vec<GhcrPackage> = arr
        .iter()
        .map(|p| GhcrPackage {
            name: p["name"].as_str().unwrap_or("?").to_string(),
            updated_at: p["updated_at"].as_str().unwrap_or("").to_string(),
        })
        .collect();

    pkgs.sort_by(|a, b| b.updated_at.cmp(&a.updated_at));
    pkgs.truncate(10);

    (pkgs, total, disk_kb)
}

/// Fetch Dagu DAG status via API at WG IP 10.0.0.4:8070
/// Supports DAGU_USERNAME / DAGU_PASSWORD env vars for basic auth.
pub async fn fetch_dags() -> Vec<DagStatus> {
    let dagu_user = std::env::var("DAGU_USERNAME").unwrap_or_default();
    let dagu_pass = std::env::var("DAGU_PASSWORD").unwrap_or_default();
    let has_auth = !dagu_user.is_empty() && !dagu_pass.is_empty();

    // Build client — with or without basic auth
    let client = if has_auth {
        Client::builder()
            .timeout(HTTP_TIMEOUT)
            .danger_accept_invalid_certs(true)
            .redirect(reqwest::redirect::Policy::none())
            .build()
            .unwrap()
    } else {
        http_client()
    };

    // Try WG mesh first (production), then localhost (when running inside Dagu container)
    let urls = [
        "http://10.0.0.4:8070/api/v2/dags",
        "http://localhost:8070/api/v2/dags",
        "http://10.0.0.4:8070/api/v1/dags",
        "http://localhost:8070/api/v1/dags",
    ];

    for url in &urls {
        let mut req = client.get(*url);
        if has_auth {
            req = req.basic_auth(&dagu_user, Some(&dagu_pass));
        }

        let resp = timeout(Duration::from_secs(5), req.send()).await;
        let json: serde_json::Value = match resp {
            Ok(Ok(r)) if r.status().is_success() => r.json().await.unwrap_or_default(),
            Ok(Ok(r)) => {
                eprintln!("  Dagu {}: HTTP {}", url, r.status());
                continue;
            }
            Ok(Err(e)) => {
                eprintln!("  Dagu {}: {}", url, e);
                continue;
            }
            Err(_) => {
                eprintln!("  Dagu {}: timeout", url);
                continue;
            }
        };

        // v2 format: { "dags": [{ "dag": { "name": ..., "schedule": ... }, "latestDAGRun": { "statusLabel": ... } }] }
        if let Some(dags) = json["dags"].as_array() {
            eprintln!("  Dagu: loaded {} DAGs from {}", dags.len(), url);
            return dags.iter().map(|d| {
                // schedule can be in dag.schedule or dag.schedule[0].expression
                let schedule = d["dag"]["schedule"].as_str()
                    .map(|s| s.to_string())
                    .or_else(|| {
                        d["dag"]["schedule"].as_array()
                            .and_then(|a| a.first())
                            .and_then(|s| s["expression"].as_str().or(s.as_str()))
                            .map(|s| s.to_string())
                    })
                    .unwrap_or_default();

                DagStatus {
                    name: d["dag"]["name"].as_str()
                        .or(d["fileName"].as_str())
                        .unwrap_or("?").to_string(),
                    status: d["latestDAGRun"]["statusLabel"].as_str()
                        .unwrap_or("not_started").to_string(),
                    started_at: d["latestDAGRun"]["startedAt"].as_str()
                        .unwrap_or("").to_string(),
                    schedule,
                }
            }).collect();
        }

        // v1 format: { "DAGs": [{ "DAG": { "Name": ..., "Schedule": ... }, "Status": { "Status": ... } }] }
        if let Some(dags) = json["DAGs"].as_array() {
            eprintln!("  Dagu: loaded {} DAGs from {} (v1)", dags.len(), url);
            return dags.iter().map(|d| {
                let schedule = d["DAG"]["Schedule"].as_str()
                    .map(|s| s.to_string())
                    .or_else(|| {
                        d["DAG"]["Schedule"].as_array()
                            .and_then(|a| a.first())
                            .and_then(|s| s["Expression"].as_str().or(s.as_str()))
                            .map(|s| s.to_string())
                    })
                    .unwrap_or_default();

                DagStatus {
                    name: d["DAG"]["Name"].as_str()
                        .or(d["File"].as_str())
                        .unwrap_or("?").to_string(),
                    status: d["Status"]["Status"].as_str()
                        .unwrap_or("none").to_string(),
                    started_at: d["Status"]["StartedAt"].as_str()
                        .unwrap_or("").to_string(),
                    schedule,
                }
            }).collect();
        }

        eprintln!("  Dagu {}: unexpected JSON format", url);
    }

    eprintln!("  Dagu: all endpoints failed, returning empty");
    vec![]
}

/// Fetch OCI bucket sizes via `oci os bucket get` (parallel)
pub async fn fetch_bucket_sizes(buckets: &[CloudBucket]) -> Vec<CloudBucket> {
    let futs: Vec<_> = buckets.iter().map(|bucket| {
        let b = bucket.clone();
        async move {
            let mut result = b.clone();
            if b.provider == "oci" {
                let output = timeout(
                    Duration::from_secs(10),
                    tokio::process::Command::new("oci")
                        .args([
                            "os", "bucket", "get",
                            "--bucket-name", &b.name,
                            "--fields", "approximateSize",
                            "--query", "data.\"approximate-size\"",
                            "--raw-output",
                        ])
                        .stdout(std::process::Stdio::piped())
                        .stderr(std::process::Stdio::piped())
                        .output(),
                )
                .await;

                result.size_bytes = output
                    .ok()
                    .and_then(|r| r.ok())
                    .filter(|o| o.status.success())
                    .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
                    .and_then(|s| s.parse::<u64>().ok())
                    .unwrap_or(0);
            }
            result
        }
    }).collect();
    futures::future::join_all(futs).await
}

/// Fetch cloud costs from OCI billing CLI (6 months, grouped by service)
pub async fn fetch_cloud_costs() -> Vec<CloudCost> {
    let mut costs = Vec::new();

    // OCI costs via CLI
    let tenancy = tokio::process::Command::new("sh")
        .args(["-c", "grep tenancy ~/.oci/config 2>/dev/null | head -1 | cut -d= -f2 | tr -d ' '"])
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .output()
        .await;

    if let Ok(t) = tenancy {
        let tid = String::from_utf8_lossy(&t.stdout).trim().to_string();
        if !tid.is_empty() {
            let now = chrono::Utc::now();
            let start = (now - chrono::Duration::days(180)).format("%Y-%m-01T00:00:00Z").to_string();
            let end = (now + chrono::Duration::days(1)).format("%Y-%m-01T00:00:00Z").to_string();

            let output = timeout(
                Duration::from_secs(30),
                tokio::process::Command::new("oci")
                    .args([
                        "usage-api", "usage-summary", "request-summarized-usages",
                        "--tenant-id", &tid,
                        "--time-usage-started", &start,
                        "--time-usage-ended", &end,
                        "--granularity", "MONTHLY",
                        "--query-type", "COST",
                        "--group-by", "[\"service\"]",
                        "--output", "json",
                    ])
                    .stdout(std::process::Stdio::piped())
                    .stderr(std::process::Stdio::piped())
                    .output(),
            )
            .await;

            if let Ok(Ok(o)) = output {
                if let Ok(j) = serde_json::from_slice::<serde_json::Value>(&o.stdout) {
                    if let Some(items) = j["data"]["items"].as_array() {
                        for item in items {
                            let amt = item["computed-amount"].as_f64().unwrap_or(0.0);
                            let usage = item["computed-quantity"].as_f64()
                                .or(item["attributed-usage"].as_str().and_then(|s| s.parse().ok()))
                                .unwrap_or(0.0);
                            let svc = item["service"].as_str().unwrap_or("?");
                            let month_raw = item["time-usage-started"].as_str().unwrap_or("");
                            let month: String = month_raw.chars().take(7).collect();
                            let currency = item["currency"].as_str().unwrap_or("EUR").trim().to_string();
                            let currency = if currency.is_empty() { "EUR".to_string() } else { currency };

                            // Include if there's any cost OR any usage (free tier has usage but $0)
                            if amt > 0.001 || usage > 0.01 {
                                costs.push(CloudCost {
                                    provider: "OCI".into(),
                                    month,
                                    service: svc.to_string(),
                                    amount: amt,
                                    currency,
                                    usage,
                                });
                            }
                        }
                    }
                }
            }
        }
    }

    costs
}

/// Fetch GitHub repos via `gh repo list`
pub async fn fetch_repos() -> Vec<GithubRepo> {
    let output = timeout(
        Duration::from_secs(15),
        tokio::process::Command::new("gh")
            .args([
                "repo", "list",
                "--limit", "50",
                "--json", "name,visibility,updatedAt,primaryLanguage,diskUsage",
            ])
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::piped())
            .output(),
    )
    .await;

    let json: serde_json::Value = match output {
        Ok(Ok(o)) if o.status.success() => {
            serde_json::from_slice(&o.stdout).unwrap_or_default()
        }
        _ => return vec![],
    };

    json.as_array()
        .map(|arr| {
            arr.iter()
                .map(|r| GithubRepo {
                    name: r["name"].as_str().unwrap_or("?").to_string(),
                    visibility: r["visibility"].as_str().unwrap_or("?").to_string(),
                    updated_at: r["updatedAt"].as_str().unwrap_or("").to_string(),
                    language: r["primaryLanguage"]["name"].as_str().unwrap_or("—").to_string(),
                    disk_kb: r["diskUsage"].as_u64().unwrap_or(0),
                })
                .collect()
        })
        .unwrap_or_default()
}

/// Fetch Matomo analytics via MariaDB on oci-apps (SSH)
pub async fn fetch_matomo_analytics() -> Vec<MatomoSite> {
    // Matomo runs on oci-apps, MariaDB embedded in matomo-hybrid container
    let db_pass = std::env::var("MATOMO_DB_PASSWORD")
        .unwrap_or_else(|_| "MatomoDB2025!".to_string());

    let sql = format!(
        r#"mysql -u matomo -p{} matomo -N -B -e "
SELECT idsite, name, main_url FROM matomo_site;
SELECT '---VISITS---';
SELECT DATE_FORMAT(visit_first_action_time, '%Y-%m') AS m, COUNT(*) FROM matomo_log_visit GROUP BY m ORDER BY m;
SELECT '---PAGEVIEWS---';
SELECT DATE_FORMAT(server_time, '%Y-%m') AS m, COUNT(*) FROM matomo_log_link_visit_action GROUP BY m ORDER BY m;
SELECT '---TOTALS---';
SELECT COUNT(*) FROM matomo_log_visit;
SELECT COUNT(*) FROM matomo_log_link_visit_action;
" 2>/dev/null"#,
        db_pass
    );

    let ssh_cmd = format!("docker exec matomo-hybrid sh -c '{}'", sql.replace('\'', "'\\''"));

    let result = timeout(
        Duration::from_secs(15),
        tokio::process::Command::new("ssh")
            .args([
                "-o", "ConnectTimeout=5",
                "-o", "ServerAliveInterval=15",
                "-o", "ServerAliveCountMax=2",
                "-o", "BatchMode=yes",
                "-o", "StrictHostKeyChecking=no",
                "-o", "LogLevel=ERROR",
                "oci-apps",
                &ssh_cmd,
            ])
            .output(),
    )
    .await;

    let output = match result {
        Ok(Ok(o)) if o.status.success() => String::from_utf8_lossy(&o.stdout).to_string(),
        _ => {
            eprintln!("  Matomo: SSH/DB query failed");
            return vec![];
        }
    };

    // Parse output
    let mut sites: Vec<MatomoSite> = Vec::new();
    let mut monthly_visits: Vec<MatomoMonthly> = Vec::new();
    let mut monthly_pv: std::collections::HashMap<String, u64> = std::collections::HashMap::new();
    let mut total_visits: u64 = 0;
    let mut total_pv: u64 = 0;
    let mut section = "sites";

    for line in output.lines() {
        let line = line.trim();
        if line.is_empty() { continue; }
        if line == "---VISITS---" { section = "visits"; continue; }
        if line == "---PAGEVIEWS---" { section = "pageviews"; continue; }
        if line == "---TOTALS---" { section = "totals"; continue; }

        match section {
            "sites" => {
                let parts: Vec<&str> = line.splitn(3, '\t').collect();
                if parts.len() >= 3 {
                    sites.push(MatomoSite {
                        id: parts[0].parse().unwrap_or(0),
                        name: parts[1].trim().to_string(),
                        url: parts[2].trim().to_string(),
                        ..Default::default()
                    });
                }
            }
            "visits" => {
                let parts: Vec<&str> = line.split('\t').collect();
                if parts.len() >= 2 {
                    let month = parts[0].to_string();
                    let count: u64 = parts[1].parse().unwrap_or(0);
                    monthly_visits.push(MatomoMonthly { month, visits: count, pageviews: 0 });
                }
            }
            "pageviews" => {
                let parts: Vec<&str> = line.split('\t').collect();
                if parts.len() >= 2 {
                    let month = parts[0].to_string();
                    let count: u64 = parts[1].parse().unwrap_or(0);
                    monthly_pv.insert(month, count);
                }
            }
            "totals" => {
                if let Ok(n) = line.parse::<u64>() {
                    if total_visits == 0 { total_visits = n; }
                    else { total_pv = n; }
                }
            }
            _ => {}
        }
    }

    // Merge pageviews into monthly_visits
    for mv in &mut monthly_visits {
        if let Some(pv) = monthly_pv.get(&mv.month) {
            mv.pageviews = *pv;
        }
    }

    // Attach to first site (Matomo usually has one main site)
    if let Some(site) = sites.first_mut() {
        site.total_visits = total_visits;
        site.total_pageviews = total_pv;
        site.monthly = monthly_visits;
    }

    eprintln!("  Matomo: loaded {} sites, {} total visits", sites.len(), total_visits);
    sites
}

/// Fetch web analytics from Umami API
pub async fn fetch_umami_analytics() -> Vec<UmamiSite> {
    // Username defaults to "admin" (Umami default), password required from env
    let username = std::env::var("UMAMI_USERNAME")
        .ok()
        .filter(|u| !u.is_empty())
        .unwrap_or_else(|| "admin".to_string());
    let password = match std::env::var("UMAMI_PASSWORD") {
        Ok(p) if !p.is_empty() => p,
        _ => {
            eprintln!("  UMAMI_PASSWORD not set, skipping Umami analytics");
            return vec![];
        }
    };

    // Read Umami URL from UMAMI_URL env var, or default to oci-apps WG IP
    let base_url_owned = std::env::var("UMAMI_URL")
        .unwrap_or_else(|_| "http://10.0.0.6:3006".to_string());
    let base_url = base_url_owned.as_str();
    let client = Client::builder()
        .timeout(Duration::from_secs(10))
        .build()
        .unwrap();

    // 1. Authenticate
    let login_body = serde_json::json!({
        "username": username,
        "password": password,
    });

    let token = match timeout(
        Duration::from_secs(10),
        client
            .post(format!("{}/api/auth/login", base_url))
            .json(&login_body)
            .send(),
    )
    .await
    {
        Ok(Ok(resp)) if resp.status().is_success() => {
            let j: serde_json::Value = resp.json().await.unwrap_or_default();
            match j["token"].as_str() {
                Some(t) => t.to_string(),
                None => {
                    eprintln!("  Umami login: no token in response");
                    return vec![];
                }
            }
        }
        Ok(Ok(resp)) => {
            eprintln!("  Umami login failed: HTTP {}", resp.status());
            return vec![];
        }
        _ => {
            eprintln!("  Umami unreachable at {}", base_url);
            return vec![];
        }
    };

    let auth_client = Client::builder()
        .timeout(Duration::from_secs(10))
        .default_headers({
            let mut headers = reqwest::header::HeaderMap::new();
            headers.insert(
                "Authorization",
                format!("Bearer {}", token).parse().unwrap(),
            );
            headers
        })
        .build()
        .unwrap();

    // 2. List websites
    let websites: serde_json::Value = match timeout(
        Duration::from_secs(10),
        auth_client.get(format!("{}/api/websites", base_url)).send(),
    )
    .await
    {
        Ok(Ok(resp)) if resp.status().is_success() => resp.json().await.unwrap_or_default(),
        _ => {
            eprintln!("  Umami: failed to list websites");
            return vec![];
        }
    };

    let site_arr = websites["data"]
        .as_array()
        .or_else(|| websites.as_array())
        .cloned()
        .unwrap_or_default();

    let now = Utc::now();
    let mut sites = Vec::new();

    for site_json in &site_arr {
        let id = site_json["id"].as_str().unwrap_or("").to_string();
        let name = site_json["name"].as_str().unwrap_or("?").to_string();
        let domain = site_json["domain"].as_str().unwrap_or("?").to_string();

        if id.is_empty() {
            continue;
        }

        // 3a. Current month stats (MTD)
        let month_start = NaiveDate::from_ymd_opt(now.year(), now.month(), 1)
            .unwrap()
            .and_hms_opt(0, 0, 0)
            .unwrap()
            .and_utc()
            .timestamp_millis();
        let now_ms = now.timestamp_millis();

        let current_month = fetch_umami_stats(&auth_client, base_url, &id, month_start, now_ms).await;

        // 3b. Last 6 months
        let mut last_6_months = Vec::new();
        for i in 1..=6 {
            let (y, m) = {
                let total_months = (now.year() * 12 + now.month() as i32 - 1) - i;
                let y = total_months / 12;
                let m = (total_months % 12 + 1) as u32;
                (y, m)
            };
            let m_start = NaiveDate::from_ymd_opt(y, m, 1)
                .unwrap()
                .and_hms_opt(0, 0, 0)
                .unwrap()
                .and_utc()
                .timestamp_millis();
            let next_m = if m == 12 {
                NaiveDate::from_ymd_opt(y + 1, 1, 1)
            } else {
                NaiveDate::from_ymd_opt(y, m + 1, 1)
            };
            let m_end = next_m
                .unwrap()
                .and_hms_opt(0, 0, 0)
                .unwrap()
                .and_utc()
                .timestamp_millis();

            let stats = fetch_umami_stats(&auth_client, base_url, &id, m_start, m_end).await;
            let label = format!("{:04}-{:02}", y, m);
            last_6_months.push((label, stats));
        }
        last_6_months.reverse(); // oldest first

        // 3c. Top pages (current month)
        let top_pages = fetch_umami_top_pages(&auth_client, base_url, &id, month_start, now_ms).await;

        sites.push(UmamiSite {
            id,
            name,
            domain,
            current_month,
            last_6_months,
            top_pages,
        });
    }

    eprintln!("  Umami: loaded {} sites", sites.len());
    sites
}

async fn fetch_umami_stats(client: &Client, base_url: &str, site_id: &str, start_ms: i64, end_ms: i64) -> UmamiStats {
    let url = format!(
        "{}/api/websites/{}/stats?startAt={}&endAt={}",
        base_url, site_id, start_ms, end_ms
    );
    match timeout(Duration::from_secs(8), client.get(&url).send()).await {
        Ok(Ok(resp)) if resp.status().is_success() => {
            let j: serde_json::Value = resp.json().await.unwrap_or_default();
            // Umami v2 API returns flat numbers: {"pageviews": 719, ...}
            // Older versions return nested: {"pageviews": {"value": 719}, ...}
            let extract = |key: &str| -> u64 {
                j[key].as_u64()
                    .or_else(|| j[key]["value"].as_u64())
                    .unwrap_or(0)
            };
            UmamiStats {
                pageviews: extract("pageviews"),
                visitors: extract("visitors"),
                visits: extract("visits"),
                bounces: extract("bounces"),
                total_time: extract("totaltime"),
            }
        }
        _ => UmamiStats::default(),
    }
}

async fn fetch_umami_top_pages(client: &Client, base_url: &str, site_id: &str, start_ms: i64, end_ms: i64) -> Vec<(String, u64)> {
    let url = format!(
        "{}/api/websites/{}/metrics?startAt={}&endAt={}&type=url",
        base_url, site_id, start_ms, end_ms
    );
    match timeout(Duration::from_secs(8), client.get(&url).send()).await {
        Ok(Ok(resp)) if resp.status().is_success() => {
            let j: serde_json::Value = resp.json().await.unwrap_or_default();
            j.as_array()
                .map(|arr| {
                    arr.iter()
                        .take(10)
                        .map(|item| {
                            let page = item["x"].as_str().unwrap_or("?").to_string();
                            let views = item["y"].as_u64().unwrap_or(0);
                            (page, views)
                        })
                        .collect()
                })
                .unwrap_or_default()
        }
        _ => vec![],
    }
}
