#!/bin/sh
# ╔══════════════════════════════════════════════════════════════════╗
# ║ cloud-data-reports entrypoint — UNIVERSAL                       ║
# ║                                                                  ║
# ║ Same pattern as cloud-builder-x entrypoint.                     ║
# ║ Sets up SSH, WG, SOPS, then dispatches report commands.         ║
# ║                                                                  ║
# ║ Usage:                                                           ║
# ║   docker compose run --rm reports all                            ║
# ║   docker compose run --rm reports stack                          ║
# ║   docker compose run --rm reports cloud                          ║
# ║   docker compose run --rm reports mail                           ║
# ║   docker compose run --rm reports bash                           ║
# ╚══════════════════════════════════════════════════════════════════╝
set -e

# ── 1. Help / passthrough ─────────────────────────────────────────
case "${1:-}" in
  ""|--help|-h)
    echo "cloud-data-reports — health report runner"
    echo ""
    echo "Commands:"
    echo "  all            Run all 5 reports (master + 4 derives)"
    echo "  daily          Master: cloud-health-full-daily (build only — NO email)"
    echo "  daily-mail     Master: cloud-health-full-daily — build + send via SMTP"
    echo "  mail           Derive: cloud-mail-health-full"
    echo "  url            Derive: cloud-url-health-report (fast)"
    echo "  sec-network    Derive: cloud-sec-network-report"
    echo "  sec-data       Derive: cloud-sec-data-report"
    echo "  bash           Interactive shell"
    exit 0
    ;;
  bash|sh)
    # Interactive shell — setup env but don't dispatch
    ;;
  all|daily|daily-mail|mail|url|sec-network|sec-data)
    # Handled below after setup
    ;;
  *)
    exec "$@"
    ;;
esac

# ── 2. SSH setup (env vars OR mounted files) ──────────────────────
mkdir -p ~/.ssh 2>/dev/null || true
chmod 700 ~/.ssh 2>/dev/null || true
ssh-keyscan github.com >> ~/.ssh/known_hosts 2>/dev/null || true

# Resilient host-key handling for the WG mesh: the report container's
# ~/.ssh/ is bind-mounted read-only from the host (Dagu's /opt/ssh-keys
# layout) and shares a known_hosts file across many runs and VM rebuilds.
# When a target VM (oci-mail / oci-apps / gcp-proxy) is reprovisioned its
# ECDSA/ED25519 host key changes, but the stale entry persists in the
# bind-mounted known_hosts. OpenSSH then refuses every connection with
# "REMOTE HOST IDENTIFICATION HAS CHANGED" — which cascades into ~10
# downstream report failures (Cloud API * / Caddy L4 * / Authelia health /
# SMTP :25 banner / TLS WG direct / config drift).
#
# Since /root/.ssh is read-only we cannot purge the stale entry there.
# Instead, write a container-local /etc/ssh/ssh_config.d/ override so SSH
# ignores the bind-mounted known_hosts entirely for the internal WG mesh
# (10.0.0.0/24 + 10.1.0.0/24). The override is by Match address so it
# leaves github.com and other external hosts on normal TOFU rules.
mkdir -p /etc/ssh/ssh_config.d 2>/dev/null || true
cat > /etc/ssh/ssh_config.d/00-wg-mesh-tofu.conf <<'EOF'
# Auto-generated by cloud-data-reports entrypoint.sh — DO NOT EDIT.
# Redirect known_hosts to a writable ephemeral file so the bind-mounted
# read-only ~/.ssh/known_hosts (carrying stale keys from prior VM
# rebuilds) is ignored. Combined with the user config's existing
# `Host * StrictHostKeyChecking accept-new`, every WG-mesh host is
# treated TOFU on each container lifecycle.
#
# NOTE: ssh_config's `Match` keyword does NOT support `address`
# (that's sshd_config-only); use a `Host` glob list instead. The
# patterns cover the SSH aliases (oci-*, gcp-*) and direct-IP usage
# (10.0.0.*, 10.1.0.*); github.com and other external hosts keep
# normal known_hosts behaviour.
Host oci-* gcp-* 10.0.0.* 10.1.0.*
    UserKnownHostsFile /tmp/known_hosts_wg
    StrictHostKeyChecking accept-new
EOF

# Materialise per-VM SSH keys from env vars. Source of truth is the consolidated
# JSON (vms[*].gha.ssh_secret) — the same env-var name CI exposes. We never
# hardcode VM names here.
CONSOLIDATED=""
# $CLOUD_DATA_DIR is the canonical override the consumer (Rust + this
# entrypoint) both honour. The remaining static paths are fallbacks for
# environments where the env var isn't set (e.g. interactive `docker run`).
# `cloud-source` is the dagu-volume location populated hourly by
# sync_secrets.yaml, which clones the PRIVATE cloud repo — that's where
# 1_cloud-configs/dist/_cloud-data-consolidated.json lives. The public cloud-data
# repo does NOT carry this file (consolidated.json is generated, not
# committed to the public mirror).
for cand in ${CLOUD_DATA_DIR:+"$CLOUD_DATA_DIR/_cloud-data-consolidated.json"} \
            /var/lib/dagu/data/cloud-source/1_cloud-configs/dist/_cloud-data-consolidated.json \
            /root/git/cloud-infra/1_cloud-configs/dist/_cloud-data-consolidated.json \
            /root/git/cloud-data/_cloud-data-consolidated.json \
            /home/diego/git/cloud-infra/1_cloud-configs/dist/_cloud-data-consolidated.json; do
  [ -z "$cand" ] && continue
  if [ -f "$cand" ]; then
    CONSOLIDATED="$cand"
    echo "[setup]   probe HIT: $cand"
    break
  else
    echo "[setup]   probe miss: $cand"
  fi
done

if [ -z "$CONSOLIDATED" ]; then
  echo "[setup]   skip SSH-config derive: CONSOLIDATED unset"
fi

# Derive CLOUD_REPO_DIR (root of the private cloud/ repo) from the consolidated
# path so the Rust reports can find a_solutions/*/dist/*.tpl files for drift
# checks. CONSOLIDATED points at <root>/1_cloud-configs/dist/_cloud-data-consolidated.json
# for full cloud-repo mounts; we strip three levels to get back to <root>.
# When the consolidated path is from a cloud-data-only mount (no 1_cloud-configs/dist
# in the path), CLOUD_REPO_DIR will fall through to empty and the drift check
# will skip itself gracefully.
if [ -n "$CONSOLIDATED" ] && [ -z "${CLOUD_REPO_DIR:-}" ]; then
  case "$CONSOLIDATED" in
    */1_cloud-configs/dist/_cloud-data-consolidated.json)
      CLOUD_REPO_DIR="${CONSOLIDATED%/1_cloud-configs/dist/_cloud-data-consolidated.json}"
      export CLOUD_REPO_DIR
      echo "[setup]   CLOUD_REPO_DIR=$CLOUD_REPO_DIR"
      ;;
  esac
fi
if ! command -v jq >/dev/null 2>&1; then
  echo "[setup]   skip SSH-config derive: jq not in PATH (got: $(command -v jq 2>&1 || echo none))"
fi
if [ -n "$CONSOLIDATED" ] && command -v jq >/dev/null 2>&1; then
  # ~/.ssh is bind-mounted read-only by some callers (Dagu's
  # health_mail-full / health_cloud-full DAGs bind /opt/ssh-keys/dagu
  # at /root/.ssh:ro) — in those cases the keys + config are already
  # pre-provisioned on the host and we have nothing to derive. Detect
  # by testing write-ability; if read-only, skip the derive block
  # entirely so the script doesn't abort under `set -e` on the first
  # `: > ~/.ssh/config.d.tmp`.
  if ! ( : > ~/.ssh/.writability_probe ) 2>/dev/null; then
    echo "[setup] SSH config: \$HOME/.ssh is read-only — keys already provisioned, skipping derive"
  else
    rm -f ~/.ssh/.writability_probe
    echo "[setup] SSH config: deriving from $CONSOLIDATED"
    : > ~/.ssh/config.d.tmp
  # jq emits TSV: ssh_alias \t wg_ip \t user \t ssh_secret
  # SSH is WG-only (port 22 firewalled to 0.0.0.0/0), so HostName MUST be the
  # WireGuard mesh IP — the public .ip always times out. wg0 is up before this
  # runs, so 10.0.0.x is reachable.
  jq -r '
    .vms
    | to_entries[]
    | select(.value.gha.ssh_secret != null and .value.wg_ip != null and .value.wg_ip != "TBD")
    | [.value.ssh_alias, .value.wg_ip, (.value.user // "ubuntu"), .value.gha.ssh_secret]
    | @tsv
  ' "$CONSOLIDATED" | while IFS="$(printf '\t')" read -r alias ip user secret; do
    [ -z "$alias" ] && continue
    eval "key_val=\${$secret:-}"
    if [ -z "$key_val" ]; then
      echo "[setup]   skip $alias — env \$$secret unset"
      continue
    fi
    key_file="$HOME/.ssh/id_${secret}"
    printf '%s\n' "$key_val" > "$key_file"
    chmod 600 "$key_file"
    cat >> ~/.ssh/config.d.tmp <<EOF
Host ${alias}
  HostName ${ip}
  User ${user}
  IdentityFile ${key_file}
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  ServerAliveInterval 30
  ServerAliveCountMax 10

EOF
    echo "[setup]   $alias → ${user}@${ip} (key=\$$secret)"
  done
  if [ -s ~/.ssh/config.d.tmp ]; then
    mv ~/.ssh/config.d.tmp ~/.ssh/config
    chmod 600 ~/.ssh/config
  else
    rm -f ~/.ssh/config.d.tmp
    echo "[setup] SSH config: no VMs matched (no secrets set?)"
  fi
  fi  # close the writability-probe if/else added for read-only ~/.ssh
elif [ -n "${SSH_KEY:-}" ]; then
  echo "$SSH_KEY" > ~/.ssh/id_deploy
  chmod 600 ~/.ssh/id_deploy
  echo "[setup] SSH key from \$SSH_KEY (single-host fallback)"
elif [ -f ~/.ssh/id_rsa ] || [ -f ~/.ssh/vault_id_rsa ] \
  || [ -f ~/.ssh/id_ed25519 ] || [ -f ~/.ssh/id_deploy ]; then
  echo "[setup] SSH keys from mounted ~/.ssh"
else
  echo "[setup] WARNING: no SSH keys found"
fi

# Single-host override (legacy SSH_ALIAS/SSH_HOST/SSH_KEY path) — append only
# if the data-driven config block isn't already covering it.
if [ -n "${SSH_ALIAS:-}" ] && [ -n "${SSH_HOST:-}" ] && \
   ! grep -q "^Host ${SSH_ALIAS}\$" ~/.ssh/config 2>/dev/null; then
  cat >> ~/.ssh/config <<EOF

Host ${SSH_ALIAS}
  HostName ${SSH_HOST}
  User ${SSH_USER:-ubuntu}
  IdentityFile ~/.ssh/id_deploy
  StrictHostKeyChecking no
  ServerAliveInterval 30
  ServerAliveCountMax 10
EOF
  chmod 600 ~/.ssh/config
fi

# ── 3. SOPS setup (mounted file takes precedence; env var only if dir writable) ──
if [ -f ~/.config/sops/age/keys.txt ]; then
  export SOPS_AGE_KEY_FILE=~/.config/sops/age/keys.txt
  echo "[setup] SOPS age key from mounted file"
elif [ -n "${SOPS_AGE_KEY:-}" ] && mkdir -p ~/.config/sops/age 2>/dev/null && [ -w ~/.config/sops/age ]; then
  printf '%s' "$SOPS_AGE_KEY" > ~/.config/sops/age/keys.txt
  export SOPS_AGE_KEY_FILE=~/.config/sops/age/keys.txt
  echo "[setup] SOPS age key from env var"
else
  echo "[setup] WARNING: no SOPS age key (not mounted, not in env, or config dir RO)" >&2
fi

# ── 4. GHCR login (optional — only if docker client is in image) ──
if ! command -v docker >/dev/null 2>&1; then
  echo "[setup] docker client not in image — skipping GHCR login (reports don't need it)"
elif [ -n "${GITHUB_TOKEN:-}" ]; then
  echo "$GITHUB_TOKEN" | docker login ghcr.io -u "${GITHUB_ACTOR:-diegonmarcos}" --password-stdin 2>/dev/null \
    && echo "[setup] GHCR authenticated" \
    || echo "[setup] GHCR login failed (non-fatal)"
elif command -v gh >/dev/null 2>&1 && gh auth token >/dev/null 2>&1; then
  gh auth token 2>/dev/null | docker login ghcr.io -u "$(gh api user --jq .login 2>/dev/null || echo diegonmarcos)" --password-stdin 2>/dev/null \
    && echo "[setup] GHCR authenticated via gh CLI" \
    || echo "[setup] GHCR login failed (non-fatal)"
fi

# ── 5. WireGuard (if key provided) ────────────────────────────────
# Peer endpoint+pubkey come from cloud-data (vault provider mapping). We pin
# to the gcp-proxy hub which routes to all internal VMs via AllowedIPs.
# Prefer the dedicated health-runner identity (10.0.0.201) over the legacy
# shared gha-runner identity (10.0.0.200). 10.0.0.200 is shared with the
# HM-ship cloud-builder + the desktop-adjacent builder, so when two of them
# are online at once they evict each other from the hub and the prober's
# direct mesh probes (IMAP/SMTP/:22) flap to "WG DOWN". A dedicated peer +
# key ends the collision. Falls back to WG_PRIVATE_KEY/10.0.0.200 until the
# WG_HEALTH_RUNNER_PRIVATE_KEY secret is provisioned.
WG_RUNNER_KEY="${WG_HEALTH_RUNNER_PRIVATE_KEY:-${WG_PRIVATE_KEY:-}}"
if [ -n "$WG_RUNNER_KEY" ]; then
  if ! command -v wg-quick >/dev/null 2>&1; then
    echo "[setup] WireGuard SKIPPED — wg-quick not in image (fix Dockerfile)" >&2
  else
    SUDO=""; command -v sudo >/dev/null 2>&1 && SUDO="sudo"
    umask 077
    # Peer details: hub = gcp-E2-f_0 (gcp-proxy). Resolved from consolidated.
    WG_PEER_PUBKEY=""
    WG_PEER_ENDPOINT=""
    if [ -n "$CONSOLIDATED" ] && command -v jq >/dev/null 2>&1; then
      WG_PEER_PUBKEY=$(jq -r '.vms["gcp-E2-f_0"].wg_public_key // empty' "$CONSOLIDATED")
      WG_PEER_IP=$(jq -r '.vms["gcp-E2-f_0"].ip // empty' "$CONSOLIDATED")
      WG_PEER_PORT=$(jq -r '.vms["gcp-E2-f_0"].wg_port // 51820' "$CONSOLIDATED")
      [ -n "$WG_PEER_IP" ] && WG_PEER_ENDPOINT="${WG_PEER_IP}:${WG_PEER_PORT}"
    fi
    : "${WG_PEER_PUBKEY:=vV/phXUwnCjxACQ5Df11Uw47BzJaK4r85jPYMu2HmDc=}"
    : "${WG_PEER_ENDPOINT:=35.226.147.64:51820}"
    # Self-IP tracks the key: dedicated peer → 10.0.0.201 (data-driven from
    # consolidated), legacy shared key → 10.0.0.200.
    if [ -n "${WG_HEALTH_RUNNER_PRIVATE_KEY:-}" ]; then
      WG_SELF_IP=""
      [ -n "$CONSOLIDATED" ] && command -v jq >/dev/null 2>&1 && \
        WG_SELF_IP=$(jq -r '.native.wireguard.clients["health-runner"].wg_ip // empty' "$CONSOLIDATED")
      : "${WG_SELF_IP:=10.0.0.201}"
    else
      WG_SELF_IP="10.0.0.200"
    fi
    cat > /tmp/wg0.conf << WGEOF
[Interface]
PrivateKey = ${WG_RUNNER_KEY}
Address = ${WG_SELF_IP}/24

[Peer]
PublicKey = ${WG_PEER_PUBKEY}
Endpoint = ${WG_PEER_ENDPOINT}
AllowedIPs = 10.0.0.0/24
PersistentKeepalive = 25
WGEOF
    $SUDO mkdir -p /etc/wireguard
    $SUDO cp /tmp/wg0.conf /etc/wireguard/wg0.conf
    rm /tmp/wg0.conf
    if $SUDO wg-quick up wg0; then
      echo "[setup] WireGuard up (peer=${WG_PEER_ENDPOINT})"
    else
      echo "[setup] WireGuard FAILED — VM probes over 10.0.0.0/24 will fail" >&2
    fi
  fi
fi

# ── 5b. wg-public spoke (if key provided) ─────────────────────────
# Second mesh: the prober joins wg-public (10.1.0.0/24) as the declared
# `health-runner` client so it can probe HUB-BOUND services (e.g.
# cf-worker-bridge binds the hub IP 10.1.0.1:8092 — unreachable from
# wg0, whose AllowedIPs only cover 10.0.0.0/24). Hub-and-spoke:
# spoke→hub traffic is exactly the path we need.
# All peer parameters are data-driven from _cloud-data-consolidated.json
# (.wireguard_public — hub pubkey/endpoint, own client wg_ip). Only the
# private key arrives via env (GHA secret WG_PUBLIC_PRIVATE_KEY,
# mirrored from vault wireguard/health-runner-public/privatekey).
if [ -n "${WG_PUBLIC_PRIVATE_KEY:-}" ] && command -v wg-quick >/dev/null 2>&1; then
  SUDO=""; command -v sudo >/dev/null 2>&1 && SUDO="sudo"
  umask 077
  WGP_HUB_PUBKEY=""
  WGP_HUB_ENDPOINT=""
  WGP_OWN_IP=""
  if [ -n "$CONSOLIDATED" ] && command -v jq >/dev/null 2>&1; then
    WGP_HUB_PUBKEY=$(jq -r '.wireguard_public.peers[]? | select(.role == "hub") | .wg_public_key // empty' "$CONSOLIDATED")
    WGP_HUB_ENDPOINT=$(jq -r '.wireguard_public.peers[]? | select(.role == "hub") | .endpoint // empty' "$CONSOLIDATED")
    WGP_OWN_IP=$(jq -r '.wireguard_public.clients["health-runner"].wg_ip // empty' "$CONSOLIDATED")
  fi
  if [ -n "$WGP_HUB_PUBKEY" ] && [ -n "$WGP_HUB_ENDPOINT" ] && [ "$WGP_HUB_ENDPOINT" != "dynamic" ] && [ -n "$WGP_OWN_IP" ]; then
    cat > /tmp/wg1.conf << WGEOF
[Interface]
PrivateKey = ${WG_PUBLIC_PRIVATE_KEY}
Address = ${WGP_OWN_IP}/24

[Peer]
PublicKey = ${WGP_HUB_PUBKEY}
Endpoint = ${WGP_HUB_ENDPOINT}
AllowedIPs = 10.1.0.0/24
PersistentKeepalive = 25
WGEOF
    $SUDO mkdir -p /etc/wireguard
    $SUDO cp /tmp/wg1.conf /etc/wireguard/wg1.conf
    rm /tmp/wg1.conf
    if $SUDO wg-quick up wg1; then
      echo "[setup] wg-public up (hub=${WGP_HUB_ENDPOINT}, self=${WGP_OWN_IP})"
      # Prime the tunnel: this container is an ephemeral, roaming, NAT'd
      # peer with no static endpoint, so the hub can't reach us until WE
      # initiate the handshake. PersistentKeepalive only fires at +25s —
      # far too late for a single-shot CI run whose probes start within
      # ~2s. Without priming, the first cf-worker-bridge probe hits a cold
      # tunnel and eats the full 10s timeout (handshake completes mid-probe
      # but TCP has already stalled). Force the handshake now with a couple
      # of packets to the hub IP so the path is warm before the reports
      # binary probes 10.1.0.0/24. Best-effort — never fail the run on it.
      WGP_HUB_IP="${WGP_HUB_ENDPOINT%%:*}"
      WGP_HUB_WGIP=$(jq -r '.wireguard_public.peers[]? | select(.role == "hub") | .wg_ip // empty' "$CONSOLIDATED" 2>/dev/null)
      ping -c 3 -W 2 "${WGP_HUB_WGIP:-10.1.0.1}" >/dev/null 2>&1 || true
      echo "[setup] wg-public tunnel primed (hub wg_ip=${WGP_HUB_WGIP:-10.1.0.1})"
    else
      echo "[setup] wg-public FAILED — hub-bound probes over 10.1.0.0/24 will fail" >&2
    fi
  else
    echo "[setup] wg-public SKIPPED — hub pubkey/endpoint or health-runner client missing in consolidated" >&2
  fi
fi

# ── 5c. R3: derive mail submission endpoints from service topology ─────────────
# send.sh requires MAIL_SUBMIT_PRIMARY/FALLBACK from env (no hardcoded IPs).
# Fully data-driven:
#   PRIMARY  = maddy direct SMTPS: oci-mail WG IP + ports.smtp from build-maddy.json
#   FALLBACK = stalwart direct SMTPS: oci-mail WG IP + port from Caddy L4 smtps.* route
# Both are direct WG connections (container runs --network host on oci-apps).
# Caddy L4 is NOT in the submission path — smtps.diegonmarcos.com now routes to
# stalwart only (post-migration), so deriving both endpoints from Caddy L4 would
# send all submission attempts to stalwart and miss maddy where no-reply@ lives.
if [ -n "$CONSOLIDATED" ] && command -v jq >/dev/null 2>&1; then
  DIST_DIR="$(dirname "$CONSOLIDATED")"

  # oci-mail WG IP — submission target for both maddy and stalwart
  OCI_MAIL_WG=$(jq -r '
    .vms | to_entries[]
    | select(.value.ssh_alias == "oci-mail")
    | .value.wg_ip // empty
  ' "$CONSOLIDATED" 2>/dev/null | head -1)

  # PRIMARY: maddy SMTPS port from build-maddy.json service spec
  MADDY_SMTP_PORT=""
  BUILD_MADDY="${DIST_DIR}/build-maddy.json"
  [ -f "$BUILD_MADDY" ] && MADDY_SMTP_PORT=$(jq -r '.services.maddy.ports.smtp // empty' "$BUILD_MADDY" 2>/dev/null)

  # FALLBACK: stalwart SMTPS port from Caddy L4 smtps.* route
  STALWART_SMTPS_PORT=""
  BUILD_CADDY="${DIST_DIR}/build-caddy.json"
  if [ -f "$BUILD_CADDY" ]; then
    STALWART_SMTPS_PORT=$(jq -r '
      (.l4_routes // [])[]
      | select((.sni // "") | ascii_downcase | startswith("smtp"))
      | (.upstream | split(":")[1])
    ' "$BUILD_CADDY" 2>/dev/null | head -1)
  fi

  if [ -n "$OCI_MAIL_WG" ] && [ -n "$MADDY_SMTP_PORT" ]; then
    export MAIL_SUBMIT_PRIMARY="${MAIL_SUBMIT_PRIMARY:-smtps://${OCI_MAIL_WG}:${MADDY_SMTP_PORT}}"
    echo "[setup] MAIL_SUBMIT_PRIMARY=$MAIL_SUBMIT_PRIMARY (maddy direct WG)"
  else
    echo "[setup] WARNING: could not derive MAIL_SUBMIT_PRIMARY (oci-mail WG=$OCI_MAIL_WG maddy-port=$MADDY_SMTP_PORT) — must be set via env" >&2
  fi

  if [ -n "$OCI_MAIL_WG" ] && [ -n "$STALWART_SMTPS_PORT" ]; then
    export MAIL_SUBMIT_FALLBACK="${MAIL_SUBMIT_FALLBACK:-smtps://${OCI_MAIL_WG}:${STALWART_SMTPS_PORT}}"
    echo "[setup] MAIL_SUBMIT_FALLBACK=$MAIL_SUBMIT_FALLBACK (stalwart direct WG)"
  elif [ -n "${MAIL_SUBMIT_PRIMARY:-}" ]; then
    export MAIL_SUBMIT_FALLBACK="${MAIL_SUBMIT_FALLBACK:-$MAIL_SUBMIT_PRIMARY}"
    echo "[setup] MAIL_SUBMIT_FALLBACK=$MAIL_SUBMIT_FALLBACK (same as primary — no stalwart SMTPS route found)"
  else
    echo "[setup] WARNING: could not derive MAIL_SUBMIT_FALLBACK — must be set via env" >&2
  fi
fi

# ── 5d. R6: load bearer token from vault (if not already set via env) ─────────
# Priority: (1) $BEARER_TOKEN env var set by caller/GHA, (2) vault pre-signed JWT
# file (local interactive use), (3) missing → warn but continue (public checks still work).
# The Rust context::load_bearer_token() reads the same vault path; this export
# makes it available earlier so entrypoint-level shell probes can also use it.
if [ -z "${BEARER_TOKEN:-}" ]; then
  _VAULT_JWT="$HOME/git/cloud-vault/A0_keys/providers/authelia/signed-bearer_jwt/tokens/cloud-admin.json"
  # Also try common mount paths used in GHA / Dagu containers
  for _jwtpath in \
    "$_VAULT_JWT" \
    "/vault/A0_keys/providers/authelia/signed-bearer_jwt/tokens/cloud-admin.json" \
    "/root/git/cloud-vault/A0_keys/providers/authelia/signed-bearer_jwt/tokens/cloud-admin.json"; do
    if [ -f "$_jwtpath" ] && command -v jq >/dev/null 2>&1; then
      _tok=$(jq -r '.access_token // empty' "$_jwtpath" 2>/dev/null)
      if [ -n "$_tok" ]; then
        export BEARER_TOKEN="$_tok"
        echo "[setup] Bearer token loaded from vault JWT (${_jwtpath##*/git/cloud-vault/})"
        break
      fi
    fi
  done
  if [ -z "${BEARER_TOKEN:-}" ]; then
    # R6: fail loud — do NOT run private/OIDC checks blind. A missing bearer
    # makes every auth-gated endpoint false-fail, which looks identical to a
    # real outage. The operator must know the token is missing, not discover it
    # in a sea of red checks. `REQUIRE_BEARER=false` opts out for the rare
    # public-only run (e.g. the `url` derive, which needs no auth).
    REQUIRE_BEARER="${REQUIRE_BEARER:-true}"
    case "${1:-}" in
      url) REQUIRE_BEARER=false ;;  # url-health is public-only, no auth needed
    esac
    if [ "$REQUIRE_BEARER" = "true" ]; then
      echo "[setup] FATAL: BEARER_TOKEN unset and no vault JWT found." >&2
      echo "        Private/OIDC endpoint checks would false-fail and mask real state." >&2
      echo "        Provide it via the BEARER_TOKEN env var, or mount the vault at" >&2
      echo "        \$HOME/git/cloud-vault/A0_keys/providers/authelia/signed-bearer_jwt/tokens/cloud-admin.json," >&2
      echo "        or set REQUIRE_BEARER=false for an explicit public-only run." >&2
      exit 1
    fi
    echo "[setup] WARNING: BEARER_TOKEN unset — public-only run (REQUIRE_BEARER=false)" >&2
  fi
fi

# ── 5d. R7: export WG_UP for Rust binary — gates UNKNOWN vs CRITICAL ──────────
# The Rust capabilities.rs re-detects WG, but exporting WG_UP here lets shell
# logic in this entrypoint and in send.sh also branch on mesh availability.
WG_UP="false"
if command -v wg >/dev/null 2>&1 && wg show wg0 >/dev/null 2>&1; then
  WG_UP="true"
fi
export WG_UP
echo "[setup] WG_UP=$WG_UP"

echo "[setup] Ready"

# ── 6. Dispatch ───────────────────────────────────────────────────
# Honour caller-set REPORTS_DIR; otherwise resolve from the canonical
# clone path baked into the image; otherwise fall back to $PWD so the
# dispatch works under any docker `-w` working-directory mount layout.
# 2026-08-19: app moved cloud-data/y_old/reports -> cloud-infra/
# a_solutions/infra-obs_reports/src (binaries live in cloud-infra now;
# only report OUTPUT still publishes to cloud-data). Callers that mount
# a cloud-infra checkout at a non-default path (Dagu's dagu_dagu_data
# volume mounts it at /var/lib/dagu/data/cloud-source, GHA mounts
# $GITHUB_WORKSPACE directly) MUST set REPORTS_DIR explicitly — the
# $PWD fallback below only helps callers that `-w` straight into the
# reports src dir.
REPORTS_DIR="${REPORTS_DIR:-/root/git/cloud-infra/a_solutions/infra-obs_reports/src}"
if [ ! -f "$REPORTS_DIR/build.sh" ] && [ -f "$PWD/build.sh" ]; then
    echo "[dispatch] REPORTS_DIR fallback: $REPORTS_DIR not found, using \$PWD ($PWD)"
    REPORTS_DIR="$PWD"
fi
CMD="$1"; shift

case "$CMD" in
  all)           exec bash "$REPORTS_DIR/build.sh" all ;;
  daily)         exec bash "$REPORTS_DIR/build.sh" health-full-daily ;;
  daily-mail)    exec bash "$REPORTS_DIR/src/cloud-health-full-daily/build.sh" ship ;;
  mail)          exec bash "$REPORTS_DIR/build.sh" mail-health-full ;;
  url)           exec bash "$REPORTS_DIR/build.sh" url-health ;;
  sec-network)   exec bash "$REPORTS_DIR/build.sh" sec-network ;;
  sec-data)      exec bash "$REPORTS_DIR/build.sh" sec-data ;;
  bash|sh)       exec bash "$@" ;;
esac
