# ══════════════════════════════════════════════════════════════════
# engine.nix — the dist/ orchestrator (dist layout v2)
#
# Replaces per-service YAML/TOML heredocs. Each service's flake.nix
# becomes a thin ~25-line wrapper that calls engine with declared
# templates + compose spec + (for own-code) nativeBuild.
#
# Produces the canonical dist/ shape described in
# /home/diego/.claude/plans/imperative-giggling-gizmo.md
#
# Emits into the derivation's $out (which build.sh copies to dist/):
#   manifest.json               self-describing index
#   code/<arch>/Dockerfile      image recipe per declared arch
#   configs/Dockerfile          FROM scratch, COPY . /configs
#   configs/*                   rendered templates (banner + @VAR@ subst)
#   compose/docker-compose.yml  from composeSpec attrset via toYAML,
#                                 with compose-defaults.json merged in
#   assets/*                    static files (verbatim)
#   assets/hooks/               optional — copied from srcDir/hooks if present
#
# Does NOT produce:
#   code/<arch>/<binary>        Type A compile is ship-engine work
#   data/                       cloud-data stays in 1_cicd/dist/, never duplicated
#   secrets/ sensitive/ .build/ ship-engine concerns, gitignored
# ══════════════════════════════════════════════════════════════════

{ pkgs
, buildJson           # parsed ../build.json
, container           # parsed ./build-<container>.json
, srcDir              # the service's src/ path
, templates ? []      # [{ name; vars; } | { name; text; }]
, composeSpec         # attrset — serialised to YAML
, extraAssets ? []    # list of paths copied verbatim into dist/assets/
, includeCloudData ? (buildJson.build.include_cloud_data or false) == true
                      || (buildJson.build.include_cloud_data or false) == "true"
, nativeBuild ? null  # null = Type B (wrap upstream); set = Type A (own code)
, title ? buildJson.name or "unnamed-service"
}:

let
  inherit (pkgs) lib;

  # ──────────────────────────────────────────────────────────────
  # Banner — AUTO-GENERATED marker injected into every emitted file
  # svcDirName is derived from srcDir (data-driven, no hardcoding).
  # ──────────────────────────────────────────────────────────────
  svcDirName = baseNameOf (dirOf srcDir);
  svcPath    = "a_solutions/${svcDirName}";

  bannerLines = [
    "╔══════════════════════════════════════════════════════════════════╗"
    "║ GENERATED FILE — DO NOT EDIT — NIX FLAKES WAY                    ║"
    "║ AUTO-GENERATED by _shared/engine.nix — dist/ output is a build   ║"
    "║ artifact. Edit src/ + run build.sh, never touch dist/.           ║"
    "╠══════════════════════════════════════════════════════════════════╣"
    "║ Source:  ${svcPath}/src/flake.nix"
    "║ Rebuild: ${svcPath}/build.sh ship"
    "╚══════════════════════════════════════════════════════════════════╝"
  ];

  mkBanner = prefix:
    (lib.concatMapStringsSep "\n" (l: "${prefix} ${l}") bannerLines) + "\n";

  # ──────────────────────────────────────────────────────────────
  # NOTE: dist/ does NOT duplicate cloud-data JSONs. 1_cicd/dist/
  # is the single source of truth; services reference it at runtime
  # via mount/symlink, not via per-service bundling. The
  # include_cloud_data flag in build.json is kept as metadata only
  # (surfaced in manifest.json) — engine never copies files.
  # ──────────────────────────────────────────────────────────────

  # ──────────────────────────────────────────────────────────────
  # Fleet-wide compose defaults — data-driven from
  # _shared/compose-defaults.json. Per-service fields override.
  # ──────────────────────────────────────────────────────────────
  composeDefaultsFile = builtins.fromJSON (builtins.readFile ./compose-defaults.json);
  composeDefaults     = composeDefaultsFile.defaults;

  # Memory ceiling — see _shared/memory-ceiling.nix for the whole story.
  # Applied to the FINAL services attrset (below), so nothing the engine itself
  # injects escapes it either.
  applyMemoryCeiling = services:
    import ./memory-ceiling.nix {
      policy   = composeDefaultsFile.memory_limit;
      category = buildJson.category or null;
      title    = title;
      inherit services;
    };

  # ──────────────────────────────────────────────────────────────
  # Agent toolbelt (#509, extends #366/#450) — data-driven from
  # _shared/agent-toolbelt.json, the ONE declaration every AI agent
  # container (my-ai_claude-api, my-ai-api, hermes-agent) consumes.
  # Never hand-write an apt-get/gh/yq install line per service again.
  # ──────────────────────────────────────────────────────────────
  agentToolbelt = builtins.fromJSON (builtins.readFile ./agent-toolbelt.json);
  toolbeltApt    = lib.concatStringsSep " " agentToolbelt.apt_packages;
  toolbeltVerify = lib.concatStringsSep " " agentToolbelt.binaries;
  ghT = agentToolbelt.tarballs.gh;
  yqT = agentToolbelt.tarballs.yq;
  # {version}/{arch} in the JSON become shell-variable REFERENCES (braced, so
  # they can't glob into a neighbouring literal like _linux_) — substituted at
  # nix-eval time, expanded at Docker-build time once ARCH is known.
  subst = s: lib.replaceStrings [ "{version}" "{arch}" ] [ "\${GH_VERSION}" "\${TOOL_ARCH}" ] s;
  substY = s: lib.replaceStrings [ "{version}" "{arch}" ] [ "\${YQ_VERSION}" "\${TOOL_ARCH}" ] s;
  ghDir  = subst ghT.extracted_dir;
  ghUrl  = subst ghT.url;
  ghBin  = subst ghT.extracted_bin;
  yqUrl  = substY yqT.url;
  # One verbatim shell command (matches the existing runtime_extra_run shape:
  # semicolon-joined, arch-aware, ends in a fail-loud probe of every declared
  # binary so a missing tool fails the BUILD, not the dispatch).
  toolbeltExtraRun = ''set -eu; ARCH="$(uname -m)"; case "$ARCH" in aarch64|arm64) TOOL_ARCH=arm64 ;; x86_64|amd64) TOOL_ARCH=amd64 ;; *) echo "unsupported architecture: $ARCH" >&2; exit 1 ;; esac; GH_VERSION=${ghT.version}; curl -fsSL "${ghUrl}" | tar -xz -C /tmp; install -m 0755 "/tmp/${ghDir}/${ghBin}" /usr/local/bin/gh; rm -rf "/tmp/${ghDir}"; YQ_VERSION=${yqT.version}; curl -fsSL -o /usr/local/bin/yq "${yqUrl}"; chmod +x /usr/local/bin/yq; for t in ${toolbeltVerify}; do command -v "$t" >/dev/null || { echo "agent toolbelt: missing $t" >&2; exit 1; }; done'';

  # Deep per-field merge: service field wins if set. Uses recursiveUpdate
  # so nested attrsets (deploy.resources.limits.pids etc.) survive overlay.
  mergeSvc = svc: lib.recursiveUpdate composeDefaults svc;

  # ──────────────────────────────────────────────────────────────
  # Conditional secrets auto-mount.
  #
  # Whenever src/secrets.yaml exists, the engine-side
  # cloud-ship-container-step-secrets-decrypt.sh produces:
  #   dist/.secrets              KEY=VALUE dotenv
  #   dist/.secrets.d/<KEY>      one file per key (mode 0600)
  #   dist/.secrets.json         {"KEY":"value", ...}
  #
  # Wire all three into every container service so consumers can pick
  # the daemon-native pattern (env / _FILE / app-side JSON) instead of
  # shell-text manipulation. List-aware concatenation — services that
  # already declare env_file/volumes keep their entries.
  # ──────────────────────────────────────────────────────────────
  hasSecrets = builtins.pathExists (srcDir + "/secrets.yaml");

  secretsEnvFile = [ ".secrets" ];
  secretsVolumes = [
    "./.secrets.d:/run/secrets:ro"
    "./.secrets.json:/run/secrets.json:ro"
  ];

  mergeSecretsInto = svc:
    if !hasSecrets then svc
    else svc // {
      env_file = lib.unique ((svc.env_file or []) ++ secretsEnvFile);
      volumes  = lib.unique ((svc.volumes  or []) ++ secretsVolumes);
    };

  # ──────────────────────────────────────────────────────────────
  # Conditional shared git-tree auto-mount (agent containers).
  #
  # #345 mounted the one shared checkout — docker volume cloud-git-gh,
  # the same tree Gitea serves at /data/git-gh — into my-ai_claude-api
  # by hand-copying a PAIR of lines into its compose.nix: one entry in
  # the service `volumes` list, and one pinned name in the top-level
  # `volumes` attrset. Two more agent containers needed the identical
  # pair and never got it, so hermes-agent and my-ai-api spent weeks
  # telling their users the repositories did not exist (#416).
  #
  # Declaring it ONCE here is what stops the third recurrence.
  #
  # Deliberately NOT in compose-defaults.json: that file is merged into
  # EVERY service on the fleet (mergeSvc above), which would mount the
  # source tree into matomo, caddy and stalwart. This is opt-in per
  # container, from build.json `agent.git_tree`.
  #
  # The top-level `name` pin is the whole point and is NOT optional.
  # Without it compose invents a PROJECT-SCOPED volume (<project>_git_gh)
  # and the container gets an empty directory with no error at all —
  # indistinguishable from the bug this exists to fix.
  # ──────────────────────────────────────────────────────────────
  agentSpec    = buildJson.agent or {};
  wantsGitTree = (agentSpec.git_tree or false) == true;
  gitTreeKey   = "git_gh";
  gitTreeName  = "cloud-git-gh";

  # ONE canonical path, every agent container, no exceptions (#561).
  #
  # This used to be a per-container string, `agent.git_tree_mount`, and three
  # containers grew three different answers:
  #   my-ai_claude-api  /home/appuser/git   (not even via this flag — it
  #                                          hand-wrote the volume lines)
  #   my-ai-api         /home/appuser/git
  #   hermes-agent      /opt/data/git
  # The per-container field was documented as "the container's own $HOME/git",
  # and NOTHING checked that claim. hermes's build.json asserts HOME is
  # /opt/data (from its passwd entry); measured 2026-09-20 the running
  # container reports HOME=/root and uid 0, so the tree was mounted at a path
  # that was not $HOME/git at all. An agent doing the natural `ls $HOME/git`
  # got "No such file or directory" and reported that the repositories did not
  # exist — the exact symptom #416 was closed on, returning through a
  # different door.
  #
  # A mount point is not a per-service opinion. One path, declared here, and
  # the containers stop disagreeing. The path is ALSO published as
  # AGENT_GIT_TREE so nothing downstream has to infer it from $HOME — which is
  # what broke, and what a comment cannot prevent.
  gitTreeMountPath = "/home/appuser/git";

  # Setting the old per-container field is now a BUILD ERROR rather than a
  # silently-ignored value: a stale string left in a build.json would otherwise
  # read as the live declaration while the engine used something else, which is
  # the same "two declarations, one of them lying" shape being removed here.
  _gitTreeMountGuard =
    if (agentSpec ? git_tree_mount)
    then throw ("${title}: agent.git_tree_mount is no longer per-container. "
                + "The shared checkout mounts at ${gitTreeMountPath} in EVERY "
                + "agent container (see _shared/engine.nix). Delete the field; "
                + "the path is published to the container as AGENT_GIT_TREE.")
    else null;

  # `seq`, not a bare binding. Nix is lazy: a `let` binding nothing references
  # is NEVER evaluated, so the throw above could not fire and the guard would
  # have been decoration — a check that passes whether or not the defect is
  # present. Forcing it here ties it to the one value every git-tree path
  # already reads.
  gitTreeMount = builtins.seq _gitTreeMountGuard gitTreeMountPath;

  # Read-only unless the container is expected to COMMIT from the shared
  # tree. Extra writers on ONE working tree is a real concurrency
  # decision, not a default to inherit: git refuses the second write, so
  # an unplanned writer shows up as a failed dispatch rather than as
  # work silently lost — which is the failure #345 set out to end.
  gitTreeWritable = (agentSpec.git_tree_writable or false) == true;
  gitTreeSuffix   = if gitTreeWritable then "" else ":ro";

  # The tree on disk has ONE owner — the uid that cloned it, 10001 — and
  # every other agent container arrives with a different one. git's
  # ownership check then refuses EVERYTHING, not merely writes:
  #
  #   fatal: detected dubious ownership in repository at '/opt/data/git/cloud-infra'
  #
  # `git status`, `git log`, `git remote` and `git push` all die that same
  # way, so an agent stands in the tree, lists six repositories, and cannot
  # read a single one of them. #421 moved the working directory INTO the
  # tree; this is the half that was underneath it, and it is why mounting
  # the tree writable was never enough to make an agent able to use it.
  #
  # safe.directory is git's own answer and is honoured ONLY from protected
  # configuration — system, global, or the command scope that
  # GIT_CONFIG_COUNT/KEY/VALUE writes. The env triple is the only one of
  # those three that can be declared from here, for images we do not build.
  # It is set for read-only mounts too: reading is exactly what the check
  # blocks first.
  #
  # The credential helper travels with it, for writable trees only, because
  # a token-less agent fails at the LAST step rather than the first — it
  # edits, commits, and only then discovers it can never push, having
  # already written into a tree the other agents share. The helper reads
  # GH_TOKEN from the environment, which each container's own sops secrets
  # supply; `$$` is compose's escape, so what reaches the container is the
  # literal `${GH_TOKEN}` for git's shell to expand when the helper runs.
  gitTreeGitEnv =
    {
      # Published so nothing has to INFER the tree's location from $HOME. That
      # inference is precisely what failed: hermes runs with HOME=/root while
      # the tree sat at /opt/data/git, so `ls $HOME/git` found nothing and the
      # agent reported the repositories missing. An env var cannot drift from
      # the mount — they are the same binding, one line apart.
      AGENT_GIT_TREE     = gitTreeMount;
      GIT_CONFIG_COUNT   = if gitTreeWritable then "2" else "1";
      GIT_CONFIG_KEY_0   = "safe.directory";
      GIT_CONFIG_VALUE_0 = "*";
    } // (if gitTreeWritable
          then {
            GIT_CONFIG_KEY_1   = "credential.helper";
            GIT_CONFIG_VALUE_1 =
              "!f() { echo username=x-access-token; echo \"password=$\${GH_TOKEN}\"; }; f";
          }
          else {});

  # Mounting the tree is only half of it. `docker exec` starts every command
  # at the image's WorkingDir, and an agent that is handed work there starts
  # OUTSIDE the checkout: it finds no repository, reports the code as missing,
  # and answers anyway. That failure looks identical to "the mount is broken"
  # while the mount is perfectly fine, so the working directory is declared
  # here, next to the mount it depends on, rather than left to the image.
  #
  # Opt-in, not automatic: a container whose main process needs its own
  # WORKDIR (an API serving /app) must keep it, and only the sessions that
  # are supposed to live in the tree move into it.
  gitTreeIsWorkingDirectory =
    (agentSpec.git_tree_is_working_directory or false) == true;

  # ── Ownership repair, declared (#558) ───────────────────────────────────
  # The tree has ONE owner, 10001 (see the safe.directory block above). When
  # something writes into it as another uid, every agent silently loses the
  # tree: git dies with "detected dubious ownership" or "insufficient
  # permission for adding an object" deep inside a subprocess, and the turn
  # still reports success. Measured 2026-09-20: 260 root-owned paths across
  # four repos — including .git/config, ~117 object fanout dirs and a whole
  # c_tasks/ — which is why the backlog went stale and #540's session sync
  # kept "failing" for reasons that were never sync bugs.
  #
  # The writer was gitea (a rw mount it never used, running as root); that
  # mount is gone. This is the other half: the tree REPAIRS ITSELF on every
  # deploy, so no one has to shell into the box — and a future root writer
  # costs one deploy instead of a day of misread failures.
  #
  # Agents cannot do this themselves. They run as 10001 and chown on a
  # root-owned path is EPERM, which is exactly why a fix living in an agent's
  # own start.sh could never have worked.
  #
  # Fail-closed: if any path is still wrong afterwards the service exits
  # non-zero, and depends_on(service_completed_successfully) stops the agents
  # from starting into a tree they cannot write. A silent partial repair is
  # the failure this whole ticket is about.
  gitTreeOwnerUid   = "10001";
  gitTreeOwnerGid   = "999";
  gitTreeRepairKey  = "git-tree-owner-repair";
  gitTreeRepairSvc = {
    # busybox is multi-arch and ~4MB; find/xargs/chown is all this needs.
    image   = "busybox:1.37";
    user    = "0:0";                  # the whole point — only root can chown
    restart = "no";
    volumes = [ "${gitTreeKey}:/git-tree" ];
    command = [
      "sh" "-c"
      # EVERY `$` here MUST be written `$$`. Compose interpolates `$VAR` in its
      # own config BEFORE the container ever sees it, so a bare `$bad` is
      # replaced with the empty string and the script silently becomes
      # `[ "" -eq 0 ]` — which errors, exits 1, and (via
      # service_completed_successfully) blocks every agent container from
      # starting. That is exactly what happened on 2026-09-20: this repair took
      # the telegram bots down and left my-ai-api in `created` state, because
      # the failure surfaced as compose warnings nobody reads:
      #   warning: The "bad" variable is not set. Defaulting to a blank string.
      # `$$` is compose's escape and reaches the shell as a single `$` — the
      # same escape the credential.helper above already uses for GH_TOKEN.
      # test-git-tree-owner-repair.mjs now fails on any unescaped `$` here.
      (lib.concatStringsSep "\n" [
        "set -eu"
        "bad=$$(find /git-tree ! -uid ${gitTreeOwnerUid} 2>/dev/null | wc -l)"
        "find /git-tree ! -uid ${gitTreeOwnerUid} -print0 2>/dev/null | xargs -0 -r chown ${gitTreeOwnerUid}:${gitTreeOwnerGid} 2>/dev/null || true"
        "left=$$(find /git-tree ! -uid ${gitTreeOwnerUid} 2>/dev/null | wc -l)"
        "echo \"[git-tree-repair] paths not owned by ${gitTreeOwnerUid}: before=$$bad after=$$left\""
        # Loud, not silent: the deploy log is the only place anyone sees this.
        "[ \"$$left\" -eq 0 ] || { echo \"[git-tree-repair] ERROR: $$left path(s) still wrong — agents would fail to commit\" >&2; exit 1; }"
      ])
    ];
  };

  # Every container sharing the tree waits for the repair. Without this the
  # agent and the repair race, and the agent wins often enough to look fine.
  gitTreeDependsOn = { "${gitTreeRepairKey}" = { condition = "service_completed_successfully"; }; };

  mergeGitTreeInto = svc:
    if !wantsGitTree then svc
    else svc // {
      volumes = lib.unique ((svc.volumes or [])
        ++ [ "${gitTreeKey}:${gitTreeMount}${gitTreeSuffix}" ]);
      # The service's own declarations win: this supplies the git contract
      # the mount needs, it does not overrule a container that states its
      # own. Compose also accepts a LIST for `environment`, and merging an
      # attrset into a list is a build error rather than a wrong value, so
      # the list form is left exactly as written.
      environment =
        let e = svc.environment or {}; in
        if builtins.isAttrs e then gitTreeGitEnv // e else e;
      # Compose accepts depends_on in two shapes and will NOT mix them. The
      # short LIST form only waits for the dependency to START, which for a
      # one-shot repair means "wait for it to begin chowning" — useless. So an
      # existing list is converted to the long form (preserving its entries as
      # service_started, the semantics it already had) before ours is added
      # with service_completed_successfully.
      depends_on =
        let d = svc.depends_on or null; in
        if d == null then gitTreeDependsOn
        else if builtins.isList d
          then (lib.listToAttrs
                 (map (n: { name = n; value = { condition = "service_started"; }; }) d))
               // gitTreeDependsOn
          else d // gitTreeDependsOn;
    } // (if gitTreeIsWorkingDirectory
          then { working_dir = gitTreeMount; }
          else {});

  # Order matters for the rendered YAML: the git tree is appended BEFORE
  # the secrets mounts, matching the volume order my-ai_claude-api
  # already renders today (claude_home, git_gh, .secrets.d, .secrets.json).
  # Keeping that order means migrating a service from hand-written lines
  # to this flag does not churn its dist hash — and a dist-hash churn
  # here means a container RECREATE, which kills any agent running in it.
  applyDefaults = spec:
    # Forced here, not only via gitTreeMount: a build.json that sets the dead
    # `agent.git_tree_mount` while git_tree is false would otherwise never
    # evaluate the guard, and the stale string would sit in the declaration
    # looking live. Every container goes through applyDefaults.
    builtins.seq _gitTreeMountGuard (
    spec // {
      # The repair is added AFTER the mapAttrs on purpose: it must not receive
      # the git-tree merge (it mounts the volume itself, at its own path, and a
      # depends_on pointing at itself would deadlock the project).
      # applyMemoryCeiling wraps the WHOLE set, git-tree repair included: a
      # container the engine adds is still a container, and the one that got
      # away is exactly how uncapped stays reachable.
      services = applyMemoryCeiling ((lib.mapAttrs
        (_: svc: mergeSecretsInto (mergeGitTreeInto (mergeSvc svc)))
        (spec.services or {}))
        // (if wantsGitTree then { "${gitTreeRepairKey}" = gitTreeRepairSvc; } else {}));
    } // (if wantsGitTree
          then {
            volumes = (spec.volumes or {})
              // { "${gitTreeKey}" = { name = gitTreeName; }; };
          }
          else {}));

  # ──────────────────────────────────────────────────────────────
  # Arch routing — data-driven from build.json:docker.arch
  # Always emit BOTH amd64 and arm64 slots; mark non-declared
  # archs with a `.skip` sentinel so ship engine bypasses them.
  # ──────────────────────────────────────────────────────────────
  declaredArchs =
    let d = buildJson.docker.arch or "amd64"; in
    if builtins.isList d then d
    else if builtins.isString d then lib.splitString "," d
    else [ "amd64" ];

  allArchs = [ "amd64" "arm64" ];

  # ──────────────────────────────────────────────────────────────
  # Template rendering — pure-Nix substitution (no shell-quoting)
  #   { name; vars; }  → read srcDir/templates/<name>.tpl, @VAR@ subst
  #   { name; text;  } → write pre-computed string verbatim
  # Banner spliced after any leading shebang (#!) so scripts stay executable.
  # ──────────────────────────────────────────────────────────────
  pickPrefix = name:
    let n = name; in
    # php-fpm + ini configs use `;` (else FPM dies with ZEND_INI_PARSER_ENTRY).
    # DNS zone files (RFC 1035) also use `;` — `#` causes hickory-dns to abort
    # with "Label contains invalid characters". Detect by name.
    if lib.hasSuffix ".ini" n
    || lib.hasSuffix ".zone" n
    || lib.hasInfix "php-fpm" n
    || lib.hasInfix "php.fpm" n then ";"
    else if lib.hasSuffix ".sh"   n || lib.hasSuffix ".yml" n
    || lib.hasSuffix ".yaml" n || lib.hasSuffix ".conf" n
    || lib.hasSuffix ".toml" n
    || n == "Dockerfile" || lib.hasPrefix "Dockerfile" n then "#"
    else if lib.hasSuffix ".js" n || lib.hasSuffix ".ts" n
         || lib.hasSuffix ".rs" n || lib.hasSuffix ".go" n then "//"
    else "#";

  spliceBanner = banner: body:
    if lib.hasPrefix "#!" body then
      let m = lib.strings.match "^(#![^\n]*\n)([[:print:][:space:]]*)$" body; in
      if m != null
      then (builtins.elemAt m 0) + banner + (builtins.elemAt m 1)
      else banner + body
    else banner + body;

  renderTemplate = t: let
    # JSON has no comment syntax — banner would invalidate the file (e.g.
    # Stalwart's `Failed to parse data store settings: expected value at
    # line 1 column 1`). Skip banner for .json files; the auto-generated
    # marker still lives in manifest.json + the file's git path.
    isJson = lib.hasSuffix ".json" t.name;
    prefix = pickPrefix t.name;
    banner = if isJson then "" else mkBanner prefix;
    body =
      if t ? text then t.text
      else let
        raw  = builtins.readFile "${srcDir}/templates/${t.name}.tpl";
        vars = t.vars or {};
        keys = map (k: "@${k}@") (lib.attrNames vars);
        vals = map (v: toString v) (lib.attrValues vars);
      in lib.replaceStrings keys vals raw;
  in
    pkgs.writeText t.name (spliceBanner banner body);

  # ──────────────────────────────────────────────────────────────
  # Dockerfile for code/<arch>/ — Type B (wrap) or Type A (own)
  # ──────────────────────────────────────────────────────────────
  mkCodeDockerfile = arch:
    if nativeBuild != null then
      # Two Type-A flavors:
      #   (a) nativeBuild.dockerfile set → vendor a service-shipped Dockerfile
      #       (multi-stage upstream Dockerfile, e.g. Mattermost release-11.7).
      #       Engine prepends a banner and copies the file verbatim; the service
      #       owns the build recipe. Pair with `nativeBuild.extraFiles` for any
      #       sibling files the Dockerfile expects in the build context (e.g.
      #       a `passwd` file COPY'd into a distroless stage).
      #   (b) no dockerfile → engine generates the legacy single-binary recipe
      #       (FROM base + COPY binary + CMD).
      if (nativeBuild.dockerfile or null) != null then
        pkgs.writeText "Dockerfile" ''
          ${mkBanner "#"}# Type A — service-shipped Dockerfile, arch=${arch}
          # Source: ${toString nativeBuild.dockerfile}
          ${lib.replaceStrings
              [ "@AGENT_TOOLBELT_APT@" "@AGENT_TOOLBELT_EXTRA_RUN@" ]
              [ toolbeltApt toolbeltExtraRun ]
              (builtins.readFile nativeBuild.dockerfile)}
        ''
      else
        pkgs.writeText "Dockerfile" ''
          ${mkBanner "#"}# Type A — own code, arch=${arch}
          FROM ${nativeBuild.baseImage or "debian:bookworm-slim"}
          ${lib.optionalString (nativeBuild.apt or "" != "")
            "RUN apt-get update && apt-get install -y --no-install-recommends ${nativeBuild.apt} && rm -rf /var/lib/apt/lists/*"}
          COPY ${baseNameOf nativeBuild.binary} /usr/local/bin/${baseNameOf nativeBuild.binary}
          LABEL org.opencontainers.image.source="https://github.com/diegonmarcos/cloud-infra"
          CMD ["${baseNameOf nativeBuild.binary}"]
        ''
    else
      let
        upstream = buildJson.upstream_image or (container.container.image or "alpine:latest");
        # Declarative opt-in: build.json#docker.agent_toolbelt = true (#509).
        # Sources apt/extra-run from the ONE fleet-wide _shared/agent-toolbelt.json
        # declaration instead of a per-service hand-typed list, so hermes-agent
        # cannot drift from my-ai_claude-api / my-ai-api's toolbelt.
        wantsToolbelt = (buildJson.docker.agent_toolbelt or false) == true;
        # Declarative opt-in: build.json#docker.runtime_packages = { apk=..; apt=..; }
        # Lets Type B (wrap upstream) extend the image without a service-local Dockerfile.
        rtPkgs   = buildJson.docker.runtime_packages or {};
        apkList  = rtPkgs.apk or "";
        aptList  = if wantsToolbelt then toolbeltApt else (rtPkgs.apt or "");
        # Declarative opt-in: build.json#docker.runtime_extra_run = [ "cmd"; .. ]
        # One list entry becomes one RUN, emitted AFTER the package lines so a
        # command may rely on what runtime_packages just installed.
        #
        # This exists because a package manager cannot deliver every tool. The
        # case that forced it is `gh` (#366): it is not in Debian's repositories,
        # so `runtime_packages.apt` structurally CANNOT install it — and an agent
        # without gh runs `gh run view`, gets `gh: not found`, and reports its CI
        # green having checked nothing. That is a fail-open, so the absence had to
        # become expressible here rather than pushing the service into a
        # service-local Dockerfile it does not otherwise need.
        #
        # Entries are emitted verbatim, so each one owns its own failure
        # behaviour: end a command with a version probe if you want a missing
        # tool to break the BUILD instead of shipping and failing at runtime.
        extraRun = if wantsToolbelt then [ toolbeltExtraRun ] else (buildJson.docker.runtime_extra_run or []);
      in
      pkgs.writeText "Dockerfile" ''
        ${mkBanner "#"}# Type B — wrap upstream, arch=${arch}
        FROM ${upstream}
        LABEL org.opencontainers.image.source="https://github.com/diegonmarcos/cloud-infra"
        LABEL cloud.diegonmarcos.from-image="${upstream}"
        ${lib.optionalString (apkList != "")
          "RUN apk add --no-cache ${apkList}"}
        ${lib.optionalString (aptList != "")
          "RUN apt-get update && apt-get install -y --no-install-recommends ${aptList} && rm -rf /var/lib/apt/lists/*"}
        ${lib.concatMapStringsSep "\n" (cmd: "RUN ${cmd}") extraRun}
      '';

  # ──────────────────────────────────────────────────────────────
  # Dockerfile for configs/ — always thin, always the same
  # ──────────────────────────────────────────────────────────────
  configsDockerfile = pkgs.writeText "Dockerfile" ''
    ${mkBanner "#"}# configs image — FROM scratch
    FROM scratch
    COPY . /configs
    LABEL org.opencontainers.image.source="https://github.com/diegonmarcos/cloud-infra"
    LABEL cloud.diegonmarcos.image-type="configs"
  '';

  # ──────────────────────────────────────────────────────────────
  # docker-compose.yml — YAML serialised from composeSpec attrset
  # with compose-defaults.json deep-merged into every service.
  # ──────────────────────────────────────────────────────────────
  composeYaml = pkgs.writeText "docker-compose.yml"
    ((mkBanner "#")
     + (lib.generators.toYAML {} (applyDefaults composeSpec)));

  # ──────────────────────────────────────────────────────────────
  # manifest.json — self-describing index (+ _banner array)
  # ──────────────────────────────────────────────────────────────
  manifest = {
    service = buildJson.name;
    type = if nativeBuild != null then "own-code" else "wrap-image";
    archs = declaredArchs;
    images = {
      binaries = {
        repo = "ghcr.io/diegonmarcos/${buildJson.name}-binaries";
        tags = lib.listToAttrs (map (a: { name = a; value = null; }) declaredArchs);
      };
      configs = {
        repo = "ghcr.io/diegonmarcos/${buildJson.name}-configs";
        tag = "latest";
        digest = null;
      };
    };
    upstream_ref =
      buildJson.upstream_image or (container.container.image or null);
    include_cloud_data = includeCloudData;  # metadata only; no duplication
    has_hooks = builtins.pathExists (srcDir + "/hooks");
    _meta = {
      layout_version = 2;
      generated_by = "_shared/engine.nix";
    };
    _banner = bannerLines;
  };

  manifestJson = pkgs.writeText "manifest.json"
    (builtins.toJSON manifest);

in
pkgs.runCommand "${buildJson.name}-dist-v2" {
  passthru = { inherit manifest declaredArchs; };
} ''
  mkdir -p $out/{code,configs,compose,assets}

  # ── manifest.json ──
  cp ${manifestJson} $out/manifest.json

  # ── code/<arch>/ — Dockerfile per arch, .skip marker for others ──
  # extraFiles (Type A vendored multi-file build context, e.g. the `passwd`
  # file Mattermost's distroless final stage COPYs) land next to the
  # Dockerfile so the docker build context is complete.
  ${lib.concatMapStringsSep "\n" (arch:
    let df = mkCodeDockerfile arch; in
    if lib.elem arch declaredArchs then ''
      mkdir -p $out/code/${arch}
      cp ${df} $out/code/${arch}/Dockerfile
      ${lib.optionalString (nativeBuild != null && (nativeBuild.extraFiles or []) != [])
        (lib.concatMapStringsSep "\n" (f:
          # cp -rL: recursive + follow symlinks. Enables directories in
          # extraFiles (e.g. ./code/scripts) so multi-file builds like
          # matomo can land their COPY tree under code/<arch>/<dir>/
          # without enumerating every file. Regular files still work
          # the same — cp -rL on a single file behaves like cp.
          "cp -rL ${f} $out/code/${arch}/${baseNameOf (toString f)}"
        ) (nativeBuild.extraFiles or []))}
    '' else ''
      mkdir -p $out/code/${arch}
      touch $out/code/${arch}/.skip
    ''
  ) allArchs}

  # ── configs/ — Dockerfile + rendered templates ──
  # Template names may contain / (e.g. zones/app.zone) — mkdir -p the parent.
  cp ${configsDockerfile} $out/configs/Dockerfile
  ${lib.concatMapStringsSep "\n" (t:
    let rendered = renderTemplate t; in ''
      mkdir -p "$(dirname "$out/configs/${t.name}")"
      cp ${rendered} $out/configs/${t.name}
    ''
  ) templates}

  # ── compose/ ──
  cp ${composeYaml} $out/compose/docker-compose.yml

  # ── assets/ — verbatim copy; also home for hooks/ subdir ──
  # Entry forms:
  #   • path              (source path, uses baseNameOf for dest name)
  #   • { name; src; }    (explicit dest name, for derived/store assets
  #                        whose baseName would be hash-prefixed)
  ${lib.concatMapStringsSep "\n" (a:
    if builtins.isAttrs a && a ? name && a ? src
    then ''
      mkdir -p "$out/assets/$(dirname '${a.name}')"
      cp -rL ${a.src} "$out/assets/${a.name}"
      chmod -R u+w "$out/assets/${a.name}"
    ''
    else ''
      cp -rL ${a} "$out/assets/${baseNameOf a}"
      chmod -R u+w "$out/assets/${baseNameOf a}"
    ''
  ) extraAssets}
  ${lib.optionalString (lib.pathExists (srcDir + "/hooks")) ''
    cp -r ${srcDir + "/hooks"} $out/assets/hooks
    chmod -R u+w $out/assets/hooks
  ''}
''
