# ══════════════════════════════════════════════════════════════════
# engine.nix — the dist/ orchestrator (dist layout v2)
#
# Replaces per-service YAML/TOML heredocs. Each service's flake.nix
# becomes a thin ~25-line wrapper that calls engine with declared
# templates + compose spec + (for own-code) nativeBuild.
#
# Produces the canonical dist/ shape described in
# /home/diego/.claude/plans/imperative-giggling-gizmo.md
#
# Emits into the derivation's $out (which build.sh copies to dist/):
#   manifest.json               self-describing index
#   code/<arch>/Dockerfile      image recipe per declared arch
#   configs/Dockerfile          FROM scratch, COPY . /configs
#   configs/*                   rendered templates (banner + @VAR@ subst)
#   compose/docker-compose.yml  from composeSpec attrset via toYAML,
#                                 with compose-defaults.json merged in
#   assets/*                    static files (verbatim)
#   assets/hooks/               optional — copied from srcDir/hooks if present
#
# Does NOT produce:
#   code/<arch>/<binary>        Type A compile is ship-engine work
#   data/                       cloud-data stays in 2_configs/dist/, never duplicated
#   secrets/ sensitive/ .build/ ship-engine concerns, gitignored
# ══════════════════════════════════════════════════════════════════

{ pkgs
, buildJson           # parsed ../build.json
, container           # parsed ./build-<container>.json
, srcDir              # the service's src/ path
, templates ? []      # [{ name; vars; } | { name; text; }]
, composeSpec         # attrset — serialised to YAML
, extraAssets ? []    # list of paths copied verbatim into dist/assets/
, includeCloudData ? (buildJson.build.include_cloud_data or false) == true
                      || (buildJson.build.include_cloud_data or false) == "true"
, nativeBuild ? null  # null = Type B (wrap upstream); set = Type A (own code)
, title ? buildJson.name or "unnamed-service"
}:

let
  inherit (pkgs) lib;

  # ──────────────────────────────────────────────────────────────
  # Banner — AUTO-GENERATED marker injected into every emitted file
  # svcDirName is derived from srcDir (data-driven, no hardcoding).
  # ──────────────────────────────────────────────────────────────
  svcDirName = baseNameOf (dirOf srcDir);
  svcPath    = "a_solutions/${svcDirName}";

  bannerLines = [
    "╔══════════════════════════════════════════════════════════════════╗"
    "║ DO NOT EDIT — DECLARATIVE ENVIRONMENT — NIX FLAKES WAY           ║"
    "║ AUTO-GENERATED by _shared/engine.nix — dist/ output is a build   ║"
    "║ artifact. Edit src/ + run build.sh, never touch dist/.           ║"
    "╠══════════════════════════════════════════════════════════════════╣"
    "║ Source:  ${svcPath}/src/flake.nix"
    "║ Rebuild: ${svcPath}/build.sh ship"
    "╚══════════════════════════════════════════════════════════════════╝"
  ];

  mkBanner = prefix:
    (lib.concatMapStringsSep "\n" (l: "${prefix} ${l}") bannerLines) + "\n";

  # ──────────────────────────────────────────────────────────────
  # NOTE: dist/ does NOT duplicate cloud-data JSONs. 2_configs/dist/
  # is the single source of truth; services reference it at runtime
  # via mount/symlink, not via per-service bundling. The
  # include_cloud_data flag in build.json is kept as metadata only
  # (surfaced in manifest.json) — engine never copies files.
  # ──────────────────────────────────────────────────────────────

  # ──────────────────────────────────────────────────────────────
  # Fleet-wide compose defaults — data-driven from
  # _shared/compose-defaults.json. Per-service fields override.
  # ──────────────────────────────────────────────────────────────
  composeDefaults =
    (builtins.fromJSON (builtins.readFile ./compose-defaults.json)).defaults;

  # Deep per-field merge: service field wins if set. Uses recursiveUpdate
  # so nested attrsets (deploy.resources.limits.pids etc.) survive overlay.
  mergeSvc = svc: lib.recursiveUpdate composeDefaults svc;

  applyDefaults = spec:
    spec // {
      services = lib.mapAttrs (_: mergeSvc) (spec.services or {});
    };

  # ──────────────────────────────────────────────────────────────
  # Arch routing — data-driven from build.json:docker.arch
  # Always emit BOTH amd64 and arm64 slots; mark non-declared
  # archs with a `.skip` sentinel so ship engine bypasses them.
  # ──────────────────────────────────────────────────────────────
  declaredArchs =
    let d = buildJson.docker.arch or "amd64"; in
    if builtins.isList d then d
    else if builtins.isString d then [ d ]
    else [ "amd64" ];

  allArchs = [ "amd64" "arm64" ];

  # ──────────────────────────────────────────────────────────────
  # Template rendering — pure-Nix substitution (no shell-quoting)
  #   { name; vars; }  → read srcDir/templates/<name>.tpl, @VAR@ subst
  #   { name; text;  } → write pre-computed string verbatim
  # Banner spliced after any leading shebang (#!) so scripts stay executable.
  # ──────────────────────────────────────────────────────────────
  pickPrefix = name:
    let n = name; in
    if lib.hasSuffix ".sh"   n || lib.hasSuffix ".yml" n
    || lib.hasSuffix ".yaml" n || lib.hasSuffix ".conf" n
    || lib.hasSuffix ".toml" n || lib.hasSuffix ".ini"  n
    || n == "Dockerfile" || lib.hasPrefix "Dockerfile" n then "#"
    else if lib.hasSuffix ".js" n || lib.hasSuffix ".ts" n
         || lib.hasSuffix ".rs" n || lib.hasSuffix ".go" n then "//"
    else "#";

  spliceBanner = banner: body:
    if lib.hasPrefix "#!" body then
      let m = lib.strings.match "^(#![^\n]*\n)([[:print:][:space:]]*)$" body; in
      if m != null
      then (builtins.elemAt m 0) + banner + (builtins.elemAt m 1)
      else banner + body
    else banner + body;

  renderTemplate = t: let
    prefix = pickPrefix t.name;
    banner = mkBanner prefix;
    body =
      if t ? text then t.text
      else let
        raw  = builtins.readFile "${srcDir}/templates/${t.name}.tpl";
        vars = t.vars or {};
        keys = map (k: "@${k}@") (lib.attrNames vars);
        vals = map (v: toString v) (lib.attrValues vars);
      in lib.replaceStrings keys vals raw;
  in
    pkgs.writeText t.name (spliceBanner banner body);

  # ──────────────────────────────────────────────────────────────
  # Dockerfile for code/<arch>/ — Type B (wrap) or Type A (own)
  # ──────────────────────────────────────────────────────────────
  mkCodeDockerfile = arch:
    if nativeBuild != null then
      pkgs.writeText "Dockerfile" ''
        ${mkBanner "#"}# Type A — own code, arch=${arch}
        FROM ${nativeBuild.baseImage or "debian:bookworm-slim"}
        ${lib.optionalString (nativeBuild.apt or "" != "")
          "RUN apt-get update && apt-get install -y --no-install-recommends ${nativeBuild.apt} && rm -rf /var/lib/apt/lists/*"}
        COPY ${baseNameOf nativeBuild.binary} /usr/local/bin/${baseNameOf nativeBuild.binary}
        LABEL org.opencontainers.image.source="https://github.com/diegonmarcos/cloud"
        CMD ["${baseNameOf nativeBuild.binary}"]
      ''
    else
      let upstream = buildJson.upstream_image or (container.container.image or "alpine:latest"); in
      pkgs.writeText "Dockerfile" ''
        ${mkBanner "#"}# Type B — wrap upstream, arch=${arch}
        FROM ${upstream}
        LABEL org.opencontainers.image.source="https://github.com/diegonmarcos/cloud"
        LABEL cloud.diegonmarcos.from-image="${upstream}"
      '';

  # ──────────────────────────────────────────────────────────────
  # Dockerfile for configs/ — always thin, always the same
  # ──────────────────────────────────────────────────────────────
  configsDockerfile = pkgs.writeText "Dockerfile" ''
    ${mkBanner "#"}# configs image — FROM scratch
    FROM scratch
    COPY . /configs
    LABEL org.opencontainers.image.source="https://github.com/diegonmarcos/cloud"
    LABEL cloud.diegonmarcos.image-type="configs"
  '';

  # ──────────────────────────────────────────────────────────────
  # docker-compose.yml — YAML serialised from composeSpec attrset
  # with compose-defaults.json deep-merged into every service.
  # ──────────────────────────────────────────────────────────────
  composeYaml = pkgs.writeText "docker-compose.yml"
    ((mkBanner "#")
     + (lib.generators.toYAML {} (applyDefaults composeSpec)));

  # ──────────────────────────────────────────────────────────────
  # manifest.json — self-describing index (+ _banner array)
  # ──────────────────────────────────────────────────────────────
  manifest = {
    service = buildJson.name;
    type = if nativeBuild != null then "own-code" else "wrap-image";
    archs = declaredArchs;
    images = {
      binaries = {
        repo = "ghcr.io/diegonmarcos/${buildJson.name}-binaries";
        tags = lib.listToAttrs (map (a: { name = a; value = null; }) declaredArchs);
      };
      configs = {
        repo = "ghcr.io/diegonmarcos/${buildJson.name}-configs";
        tag = "latest";
        digest = null;
      };
    };
    upstream_ref =
      buildJson.upstream_image or (container.container.image or null);
    include_cloud_data = includeCloudData;  # metadata only; no duplication
    has_hooks = builtins.pathExists (srcDir + "/hooks");
    _meta = {
      layout_version = 2;
      generated_by = "_shared/engine.nix";
    };
    _banner = bannerLines;
  };

  manifestJson = pkgs.writeText "manifest.json"
    (builtins.toJSON manifest);

in
pkgs.runCommand "${buildJson.name}-dist-v2" {
  passthru = { inherit manifest declaredArchs; };
} ''
  mkdir -p $out/{code,configs,compose,assets}

  # ── manifest.json ──
  cp ${manifestJson} $out/manifest.json

  # ── code/<arch>/ — Dockerfile per arch, .skip marker for others ──
  ${lib.concatMapStringsSep "\n" (arch:
    let df = mkCodeDockerfile arch; in
    if lib.elem arch declaredArchs then ''
      mkdir -p $out/code/${arch}
      cp ${df} $out/code/${arch}/Dockerfile
    '' else ''
      mkdir -p $out/code/${arch}
      touch $out/code/${arch}/.skip
    ''
  ) allArchs}

  # ── configs/ — Dockerfile + rendered templates ──
  # Template names may contain / (e.g. zones/app.zone) — mkdir -p the parent.
  cp ${configsDockerfile} $out/configs/Dockerfile
  ${lib.concatMapStringsSep "\n" (t:
    let rendered = renderTemplate t; in ''
      mkdir -p "$(dirname "$out/configs/${t.name}")"
      cp ${rendered} $out/configs/${t.name}
    ''
  ) templates}

  # ── compose/ ──
  cp ${composeYaml} $out/compose/docker-compose.yml

  # ── assets/ — verbatim copy; also home for hooks/ subdir ──
  ${lib.concatMapStringsSep "\n" (a:
    "cp -r ${a} $out/assets/${baseNameOf a}"
  ) extraAssets}
  ${lib.optionalString (lib.pathExists (srcDir + "/hooks")) ''
    cp -r ${srcDir + "/hooks"} $out/assets/hooks
    chmod -R u+w $out/assets/hooks
  ''}
''
