{
  description = "Caddy reverse proxy — dist layout v2";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.11";

  outputs = { self, nixpkgs }: let
    forAllSystems = nixpkgs.lib.genAttrs [ "x86_64-linux" "aarch64-linux" ];

    buildJson    = builtins.fromJSON (builtins.readFile ../build.json);
    caddyRoutes  = builtins.fromJSON (builtins.readFile ./build-caddy.json);

    engine = import ../../_shared/engine.nix;
    lib    = nixpkgs.lib;

    caddyfileText = import ./caddyfile.nix { inherit lib caddyRoutes; };

    templates = [
      { name = "Caddyfile"; text = caddyfileText; }
    ];

  in {
    packages = forAllSystems (system: let
      pkgs = nixpkgs.legacyPackages.${system};
      engineOut = engine {
        inherit pkgs buildJson templates;
        container = caddyRoutes;
        srcDir = ./.;
        composeSpec = import ./compose.nix { inherit buildJson; container = caddyRoutes; };
        title = "Caddy";
      };
      svcPath = "a_solutions/bb-sec_caddy";
      htmlBanner = ''
        <!-- ══════════════════════════════════════════════════════════════════ -->
        <!-- DO NOT EDIT — AUTO-GENERATED by _shared/engine.nix (overlay)     -->
        <!-- Source:  ${svcPath}/src/flake.nix                                -->
        <!-- Rebuild: ${svcPath}/build.sh ship                                -->
        <!-- ══════════════════════════════════════════════════════════════════ -->
      '';
      htmlBannerFile = pkgs.writeText "banner.html" htmlBanner;
      withBanner = src: pkgs.runCommand (baseNameOf src) {} ''
        cat ${htmlBannerFile} ${src} > $out
      '';
    in {
      default = pkgs.runCommand "${buildJson.name}-dist-v2-overlay" {
        passthru = engineOut.passthru;
      } ''
        cp -r ${engineOut} $out
        chmod -R u+w $out
        cp ${withBanner ./error.html}              $out/configs/error.html
        cp ${withBanner ./dashboard.html}          $out/configs/dashboard.html
        cp ${withBanner ./ntfy-setup.html}         $out/configs/ntfy-setup.html
        mkdir -p $out/configs/mail
        cp ${withBanner ./servermail.html}         $out/configs/mail/servermail.html
        cp ${withBanner ./servermail-config.html}  $out/configs/mail/servermail-config.html
        mkdir -p $out/configs/wkd/hu
        touch $out/configs/wkd/policy
        cp ${./pgp-wkd-key.bin}         $out/configs/wkd/hu/s8y7oh5xrdpu9psba3i5ntk64ohouhga
      '';
    });
  };
}
