{
  description = "Hickory DNS — wildcard *.app + *.db → Caddy (10.0.0.1)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.11";
  };

  outputs = { self, nixpkgs }: let
    forAllSystems = nixpkgs.lib.genAttrs [ "x86_64-linux" "aarch64-linux" ];

    buildJson = builtins.fromJSON (builtins.readFile ../build.json);
    # Single source of truth: build-hickory-dns.json (symlink → 2_configs/dist/
    # build-hickory-dns.json). Engine resolves symlink before nix build.
    buildContainer = builtins.fromJSON (builtins.readFile ./build-hickory-dns.json);

    config = {
      dns_port = buildJson.ports.dns;
      container_name = buildContainer.container.container_name;
    };

    # Caddy's WG IP — every wildcard zone points here.
    # Caddy terminates TLS + L7 routing per-hostname via its own config.
    caddy_wg_ip = buildContainer.services.caddy.ip;

    # Declared suffixes (from build.json) — add a new one to create a whole new TLD.
    zones = buildJson.dns.zones;
    forwarders = buildJson.dns.forwarders;

    title = "Hickory DNS";
    docker = import ../../_shared/docker.nix;

    # ── Zone file: wildcard → Caddy ───────────────────────────────────
    mkZoneFile = pkgs: suffix: pkgs.writeText "${suffix}.zone" ''
      $ORIGIN ${suffix}.
      $TTL 60
      @    IN SOA  hickory-dns.${suffix}. admin.${suffix}. 1 3600 900 604800 60
      @    IN NS   hickory-dns.${suffix}.
      @    IN A    ${caddy_wg_ip}
      *    IN A    ${caddy_wg_ip}
    '';

    # ── named.toml: one [[zones]] block per suffix + root forwarder ──
    mkNamedToml = pkgs:
      let
        zoneBlocks = nixpkgs.lib.concatMapStringsSep "\n\n" (suffix: ''
          [[zones]]
          zone = "${suffix}"
          zone_type = "Primary"
          file = "${suffix}.zone"
        '') zones;
      in pkgs.writeText "named.toml" ''
        # Declarative Hickory config — generated by Nix flake.
        # Source: ~/git/cloud/a_solutions/ba-clo_hickory-dns/src/flake.nix
        # Rebuild: ~/git/cloud/a_solutions/ba-clo_hickory-dns/build.sh ship
        listen_addrs_ipv4 = ["${caddy_wg_ip}"]
        listen_port = ${toString config.dns_port}
        directory = "/etc/zones"

        # ── Wildcard zones (catch-all → Caddy WG IP) ──
        ${zoneBlocks}

        # ── Root forwarder (everything else → declared upstream DNS) ──
        [[zones]]
        zone = "."
        zone_type = "External"

        [zones.stores]
        type = "forward"

        ${nixpkgs.lib.concatMapStringsSep "\n\n" (ns: ''
          [[zones.stores.name_servers]]
          ip = "${ns}"
          connections = [
            { protocol = { type = "udp" } },
            { protocol = { type = "tcp" } }
          ]
        '') forwarders}
      '';

    # ── GHCR image wrapping ─────────────────────────────────────────
    ghcr-hickory = docker.mkGhcrBuild {
      name = "hickory-dns";
      fromImage = "hickorydns/hickory-dns:latest";
    };

    # ── Docker Compose ─────────────────────────────────────────────
    mkDockerCompose = pkgs: docker.mkCompose pkgs {
      banner = docker.banner "~/git/cloud/a_solutions/ba-clo_hickory-dns/src/flake.nix";
      services = {
        hickory-dns = docker.mkService {
          name = "hickory-dns";
          image = ghcr-hickory.image;
          build = ghcr-hickory.build;
          container_name = config.container_name;
          networkMode = "host";
          skipCapDrop = true;
          environment = [
            "RUST_LOG=hickory_dns=info,hickory_server=info"
          ];
          volumes = [
            "./named.toml:/etc/named.toml:ro"
            "./zones:/etc/zones:ro"
          ];
          memLimit = "48M";
          memReservation = "16M";
        };
      };
    };

  in {
    packages = forAllSystems (system: let
      pkgs = nixpkgs.legacyPackages.${system};
    in let
      defaultPkg = pkgs.runCommand "hickory-dns-configs" {} ''
        mkdir -p $out/zones
        cp ${mkDockerCompose pkgs} $out/docker-compose.yml
        cp ${mkNamedToml pkgs} $out/named.toml
        ${nixpkgs.lib.concatMapStringsSep "\n" (s: ''
          cp ${mkZoneFile pkgs s} $out/zones/${s}.zone
        '') zones}
      '';
    in {
      default = defaultPkg;
      docs = docker.mkDocs pkgs { inherit title config defaultPkg; };
    });
  };
}
