{
  description = "Hickory DNS - Internal DNS server for WireGuard mesh (per-service .app zones)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.11";
  };

  outputs = { self, nixpkgs }: let
    forAllSystems = nixpkgs.lib.genAttrs [ "x86_64-linux" "aarch64-linux" ];

    config = {};

    title = "Hickory DNS";
    docker = import ../../_shared/docker.nix;

    # ── Service registry (auto-generated from cloud-topology.json) ────
    # Source: cloud-data-dns-services.json — generated by C3 API /dns-registry endpoint
    # Synced by Dagu cloud-data-sync → cloud-data/cloud-data-dns-services.json
    # Symlinked into src/ so nix flake can read it at build time:
    #   src/cloud-data-dns-services.json → ../../../cloud-data/cloud-data-dns-services.json
    # Fallback: empty (bootstrap / fresh clone before first Dagu run)
    dnsRegistry =
      let
        jsonPath = ./cloud-data-dns-services.json;
        raw = if builtins.pathExists jsonPath then builtins.readFile jsonPath else "";
      in if builtins.stringLength raw > 2
         then builtins.fromJSON raw
         else { services = {}; vms = {}; suffix = "app"; };

    suffix = dnsRegistry.suffix or "app";
    services = dnsRegistry.services;
    vms = dnsRegistry.vms;

    # ── Per-service zone files ─────────────────────────────────────────
    # Each service gets its own zone: authelia.app, vaultwarden.app, etc.
    # Unknown .app names (google.app) have no zone → root forwarder → Cloudflare.
    mkServiceZone = pkgs: name: ip:
      pkgs.writeText "${name}.${suffix}.zone" ''
$ORIGIN ${name}.${suffix}.
$TTL 60
@  IN SOA  hickory-dns.${suffix}. admin.${suffix}. 1 3600 900 604800 60
@  IN NS   hickory-dns.${suffix}.
@  IN A    ${ip}
'';

    # ── Hickory DNS named.toml ─────────────────────────────────────────
    # Per-service zones + root forwarder for everything else.
    mkNamedToml = pkgs:
      let
        names = builtins.attrNames services;
        zoneBlocks = builtins.concatStringsSep "\n" (
          map (name: ''
      [[zones]]
      zone = "${name}.${suffix}"
      zone_type = "Primary"

      [zones.stores]
      type = "file"
      zone_file_path = "/etc/zones/${name}.${suffix}.zone"
'') names);
      in pkgs.writeText "named.toml" ''
      listen_addrs_ipv4 = ["10.0.0.1"]
      listen_port = 53

      # ── Per-service zones (<name>.app → WG IP) ──
${zoneBlocks}
      # ── Fallback forwarder (everything else → Cloudflare/Google) ──
      [[zones]]
      zone = "."
      zone_type = "External"

      [zones.stores]
      type = "forward"
      name_servers = [
          { socket_addr = "1.1.1.1:53", protocol = "tcp" },
          { socket_addr = "1.1.1.1:53", protocol = "udp" },
          { socket_addr = "1.0.0.1:53", protocol = "tcp" },
          { socket_addr = "1.0.0.1:53", protocol = "udp" },
          { socket_addr = "8.8.8.8:53", protocol = "tcp" },
          { socket_addr = "8.8.8.8:53", protocol = "udp" },
          { socket_addr = "8.8.4.4:53", protocol = "tcp" },
          { socket_addr = "8.8.4.4:53", protocol = "udp" }
      ]
    '';

    # ── Init script — fetch DNS registry from C3 API if zones missing ──
    mkInitSh = pkgs: pkgs.writeText "init.sh" ''
      #!/bin/sh
      set -e
      cd "$(dirname "$0")"
      CONFIG_DIR="./config"
      ZONES_DIR="$CONFIG_DIR/zones"
      NAMED_TOML="$CONFIG_DIR/named.toml"
      C3_API="https://api.diegonmarcos.com/c3-api"
      SUFFIX="app"

      # If zones already exist and named.toml has zone entries, skip
      if [ -f "$NAMED_TOML" ] && [ -d "$ZONES_DIR" ] && ls "$ZONES_DIR"/*.zone >/dev/null 2>&1; then
        ZONE_COUNT=$(ls "$ZONES_DIR"/*.zone 2>/dev/null | wc -l)
        if [ "$ZONE_COUNT" -gt 0 ]; then
          echo "[init] $ZONE_COUNT zones found — skipping C3 API fetch"
          exit 0
        fi
      fi

      echo "[init] Zones missing — fetching DNS registry from C3 API..."
      mkdir -p "$ZONES_DIR"

      # Fetch DNS registry (JSON: { services: { name: { ip: "x.x.x.x" }, ... } })
      REGISTRY=$(curl -sf --max-time 10 "$C3_API/dns-registry" 2>/dev/null || echo "")
      if [ -z "$REGISTRY" ] || [ "$REGISTRY" = "{}" ]; then
        echo "[init] WARNING: C3 API unreachable or empty — starting with forwarder only"
        # Write minimal named.toml (forwarder only)
        cat > "$NAMED_TOML" <<'TOML'
      listen_addrs_ipv4 = ["10.0.0.1"]
      listen_port = 53
      [[zones]]
      zone = "."
      zone_type = "External"
      [zones.stores]
      type = "forward"
      name_servers = [
        { socket_addr = "1.1.1.1:53", protocol = "udp" },
        { socket_addr = "8.8.8.8:53", protocol = "udp" }
      ]
TOML
        exit 0
      fi

      echo "[init] Generating zones from C3 API registry..."

      # Parse services and generate zone files + named.toml
      ZONE_BLOCKS=""
      echo "$REGISTRY" | python3 -c "
import json, sys
data = json.load(sys.stdin)
services = data.get('services', {})
for name, info in services.items():
    ip = info.get('ip', '')
    if not ip:
        continue
    zone_file = sys.argv[1] + '/' + name + '.${SUFFIX}.zone'
    with open(zone_file, 'w') as f:
        f.write(f'\$ORIGIN {name}.${SUFFIX}.\n\$TTL 60\n@  IN SOA  hickory-dns.${SUFFIX}. admin.${SUFFIX}. 1 3600 900 604800 60\n@  IN NS   hickory-dns.${SUFFIX}.\n@  IN A    {ip}\n')
    print(f'  zone={name}.${SUFFIX} ip={ip}')
" "$ZONES_DIR" 2>&1 || echo "[init] WARNING: python3 parse failed"

      # Generate named.toml from zone files
      {
        echo 'listen_addrs_ipv4 = ["10.0.0.1"]'
        echo 'listen_port = 53'
        echo ''
        for zf in "$ZONES_DIR"/*.zone; do
          [ -f "$zf" ] || continue
          ZONE_NAME=$(basename "$zf" .zone)
          cat <<ZONE

[[zones]]
zone = "$ZONE_NAME"
zone_type = "Primary"

[zones.stores]
type = "file"
zone_file_path = "/etc/zones/$ZONE_NAME.zone"
ZONE
        done
        cat <<'FWD'

[[zones]]
zone = "."
zone_type = "External"

[zones.stores]
type = "forward"
name_servers = [
  { socket_addr = "1.1.1.1:53", protocol = "tcp" },
  { socket_addr = "1.1.1.1:53", protocol = "udp" },
  { socket_addr = "1.0.0.1:53", protocol = "tcp" },
  { socket_addr = "1.0.0.1:53", protocol = "udp" },
  { socket_addr = "8.8.8.8:53", protocol = "tcp" },
  { socket_addr = "8.8.8.8:53", protocol = "udp" },
  { socket_addr = "8.8.4.4:53", protocol = "tcp" },
  { socket_addr = "8.8.4.4:53", protocol = "udp" }
]
FWD
      } > "$NAMED_TOML"

      ZONE_COUNT=$(ls "$ZONES_DIR"/*.zone 2>/dev/null | wc -l)
      echo "[init] Done — $ZONE_COUNT zones generated"
    '';

    # ── Docker Compose ─────────────────────────────────────────────────
    mkDockerCompose = pkgs: docker.mkCompose pkgs {
      banner = docker.banner "~/git/cloud/a_solutions/ba-clo_hickory-dns/src/flake.nix";
      services = {
        hickory-dns = docker.mkService {
          name = "hickory-dns";
          image = "hickorydns/hickory-dns:latest";
          container_name = "hickory-dns";
          skipCapDrop = true;
          environment = [
            "RUST_LOG=hickory_dns=info,hickory_server=info"
          ];
          volumes = [
            "./config/named.toml:/etc/named.toml:ro"
            "./config/zones:/etc/zones:ro"
          ];
          dns = ["1.1.1.1" "8.8.8.8"];
          memLimit = "64M";
        };
      };
    };

  in {
    packages = forAllSystems (system: let
      pkgs = nixpkgs.legacyPackages.${system};
    in let
      # Flake outputs ONLY docker-compose.yml.
      # named.toml + zones are RUNTIME data on the VM, managed by Dagu/C3 pipeline.
      # They persist in /opt/containers/hickory-dns/config/ across deploys.
      defaultPkg = pkgs.runCommand "hickory-dns-configs" {} ''
        mkdir -p $out
        cp ${mkDockerCompose pkgs} $out/docker-compose.yml
        cp ${mkInitSh pkgs} $out/init.sh
        chmod +x $out/init.sh
      '';
    in {
      default = defaultPkg;
      docs = docker.mkDocs pkgs { inherit title config defaultPkg; };
    });
  };
}
