{
  description = "Hickory DNS - Internal DNS server for WireGuard mesh (per-service .app zones)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.11";
  };

  outputs = { self, nixpkgs }: let
    forAllSystems = nixpkgs.lib.genAttrs [ "x86_64-linux" "aarch64-linux" ];

    buildJson = builtins.fromJSON (builtins.readFile ../build.json);
    svc = (builtins.fromJSON (builtins.readFile ./cloud-data-service-connections.json)).services;

    config = {
      dns_port = buildJson.ports.dns;
    };

    title = "Hickory DNS";
    docker = import ../../_shared/docker.nix;

    # ── Service registry (auto-generated from cloud-topology.json) ────
    # Source: cloud-data-dns-services.json — generated by C3 API /dns-registry endpoint
    # Synced by Dagu cloud-data-sync → cloud-data/cloud-data-dns-services.json
    # Symlinked into src/ so nix flake can read it at build time:
    #   src/cloud-data-dns-services.json → ../../../cloud-data/cloud-data-dns-services.json
    # Fallback: empty (bootstrap / fresh clone before first Dagu run)
    dnsRegistry =
      let
        jsonPath = ./cloud-data-dns-services.json;
        raw = if builtins.pathExists jsonPath then builtins.readFile jsonPath else "";
      in if builtins.stringLength raw > 2
         then builtins.fromJSON raw
         else { services = {}; vms = {}; suffix = "app"; };

    suffix = dnsRegistry.suffix or "app";
    services = dnsRegistry.services;
    vms = dnsRegistry.vms;

    # ── Per-service zone files ─────────────────────────────────────────
    # Each service gets its own zone: authelia.app, vaultwarden.app, etc.
    # Unknown .app names (google.app) have no zone → root forwarder → Cloudflare.
    mkServiceZone = pkgs: name: ip:
      pkgs.writeText "${name}.${suffix}.zone" ''
$ORIGIN ${name}.${suffix}.
$TTL 60
@  IN SOA  hickory-dns.${suffix}. admin.${suffix}. 1 3600 900 604800 60
@  IN NS   hickory-dns.${suffix}.
@  IN A    ${ip}
'';

    # ── Hickory DNS named.toml ─────────────────────────────────────────
    # Per-service zones + root forwarder for everything else.
    mkNamedToml = pkgs:
      let
        names = builtins.attrNames services;
        zoneBlocks = builtins.concatStringsSep "\n" (
          map (name: ''
      [[zones]]
      zone = "${name}.${suffix}"
      zone_type = "Primary"

      [zones.stores]
      type = "file"
      zone_file_path = "/etc/zones/${name}.${suffix}.zone"
'') names);
      in pkgs.writeText "named.toml" ''
      # 0.0.0.0 = safe default; init.sh regenerates with cloud-data IP if WG is up
      listen_addrs_ipv4 = ["0.0.0.0"]
      listen_port = ${toString config.dns_port}

      # ── Per-service zones (<name>.app → WG IP) ──
${zoneBlocks}
      # ── Fallback forwarder (everything else → Cloudflare/Google) ──
      [[zones]]
      zone = "."
      zone_type = "External"

      [zones.stores]
      type = "forward"
      name_servers = [
          { socket_addr = "1.1.1.1:53", protocol = "tcp" },
          { socket_addr = "1.1.1.1:53", protocol = "udp" },
          { socket_addr = "1.0.0.1:53", protocol = "tcp" },
          { socket_addr = "1.0.0.1:53", protocol = "udp" },
          { socket_addr = "8.8.8.8:53", protocol = "tcp" },
          { socket_addr = "8.8.8.8:53", protocol = "udp" },
          { socket_addr = "8.8.4.4:53", protocol = "tcp" },
          { socket_addr = "8.8.4.4:53", protocol = "udp" }
      ]
    '';

    # init.sh is a separate file (not inline nix string — avoids escaping issues)

    # ── GHCR image wrapping ─────────────────────────────────────────────
    ghcr-hickory = docker.mkGhcrBuild {
      name = "hickory-dns";
      fromImage = "hickorydns/hickory-dns:latest";
    };

    # ── Docker Compose ─────────────────────────────────────────────────
    mkDockerCompose = pkgs: docker.mkCompose pkgs {
      banner = docker.banner "~/git/cloud/a_solutions/ba-clo_hickory-dns/src/flake.nix";
      services = {
        hickory-dns = docker.mkService {
          name = "hickory-dns";
          image = ghcr-hickory.image;
          build = ghcr-hickory.build;
          container_name = "hickory-dns";
          skipCapDrop = true;
          environment = [
            "RUST_LOG=hickory_dns=info,hickory_server=info"
          ];
          volumes = [
            "./config/named.toml:/etc/named.toml:ro"
            "./config/zones:/etc/zones:ro"
          ];
          dns = ["1.1.1.1" "8.8.8.8"];
          memLimit = "64M";
        };
      };
    };

  in {
    packages = forAllSystems (system: let
      pkgs = nixpkgs.legacyPackages.${system};
    in let
      # Flake outputs ONLY docker-compose.yml.
      # named.toml + zones are RUNTIME data on the VM, managed by Dagu/C3 pipeline.
      # They persist in /opt/containers/hickory-dns/config/ across deploys.
      defaultPkg = pkgs.runCommand "hickory-dns-configs" {} ''
        mkdir -p $out
        cp ${mkDockerCompose pkgs} $out/docker-compose.yml
        cp ${./init.sh} $out/init.sh
        chmod +x $out/init.sh
      '';
    in {
      default = defaultPkg;
      docs = docker.mkDocs pkgs { inherit title config defaultPkg; };
    });
  };
}
