#!/bin/bash
#
# Palantir Monitor - Cloud Infrastructure Health Report
# Generates comprehensive MD report and sends via email
#

set -o pipefail

# Configuration
REPORT_DIR="/app/reports"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
REPORT_FILE="$REPORT_DIR/health-report-${TIMESTAMP}.md"
REPORT_JSON="$REPORT_DIR/health-report-${TIMESTAMP}.json"
TO_EMAIL="me@diegonmarcos.com"
FROM_EMAIL="no-reply@diegonmarcos.com"
SMTP_PROXY_URL="${SMTP_PROXY_URL:-http://smtp.diegonmarcos.com:8080/}"
SMTP_PROXY_KEY="${SMTP_PROXY_KEY:-stalwart-proxy-key-2025}"

# Source configuration
source /app/config/endpoints.conf 2>/dev/null || true

# Initialize report
init_report() {
    cat > "$REPORT_FILE" << EOF
# Cloud Infrastructure Health Report

**Generated:** $(date '+%Y-%m-%d %H:%M:%S UTC')
**Host:** $(hostname)
**Report ID:** $(date +%s)

---

EOF
}

# Run all checks and append to report
run_all_checks() {
    echo "Running external connectivity checks..."
    /app/scripts/check-external.sh >> "$REPORT_FILE"

    echo "Running cloud provider checks..."
    /app/scripts/check-cloud.sh >> "$REPORT_FILE"

    echo "Running Docker container checks..."
    /app/scripts/check-docker.sh >> "$REPORT_FILE"

    echo "Running port/firewall analysis..."
    /app/scripts/check-ports.sh >> "$REPORT_FILE"

    echo "Running IP address inventory..."
    /app/scripts/check-ips.sh >> "$REPORT_FILE"

    echo "Running security checks..."
    /app/scripts/check-security.sh >> "$REPORT_FILE"

    echo "Collecting malware scan reports..."
    /app/scripts/check-sauron.sh >> "$REPORT_FILE"
}

# Add summary section
add_summary() {
    local ok_count=$(grep -c '\[OK\]' "$REPORT_FILE" 2>/dev/null || echo 0)
    local fail_count=$(grep -c '\[FAIL\]' "$REPORT_FILE" 2>/dev/null || echo 0)
    local warn_count=$(grep -c '\[WARN\]' "$REPORT_FILE" 2>/dev/null || echo 0)

    cat >> "$REPORT_FILE" << EOF

---

## Summary

| Status | Count |
|--------|-------|
| OK | $ok_count |
| FAIL | $fail_count |
| WARN | $warn_count |

---

*Generated by palantir-monitor*
*Report stored at: $REPORT_FILE*
EOF

    # Set subject based on failures
    if [[ $fail_count -gt 0 ]]; then
        SUBJECT="[ALERT] Cloud Health - $fail_count failures - $(date '+%Y-%m-%d')"
    elif [[ $warn_count -gt 0 ]]; then
        SUBJECT="[WARN] Cloud Health - $warn_count warnings - $(date '+%Y-%m-%d')"
    else
        SUBJECT="[OK] Cloud Health Report - $(date '+%Y-%m-%d')"
    fi
}

# Generate JSON report
generate_json_report() {
    local ok_count=$(grep -c '\[OK\]' "$REPORT_FILE" 2>/dev/null || echo 0)
    local fail_count=$(grep -c '\[FAIL\]' "$REPORT_FILE" 2>/dev/null || echo 0)
    local warn_count=$(grep -c '\[WARN\]' "$REPORT_FILE" 2>/dev/null || echo 0)

    cat > "$REPORT_JSON" << EOF
{
  "metadata": {
    "generated": "$(date '+%Y-%m-%d %H:%M:%S UTC')",
    "host": "$(hostname)",
    "report_id": "$(date +%s)",
    "timestamp": "$TIMESTAMP"
  },
  "summary": {
    "ok_count": $ok_count,
    "fail_count": $fail_count,
    "warn_count": $warn_count,
    "total_checks": $((ok_count + fail_count + warn_count)),
    "status": "$(if [[ $fail_count -gt 0 ]]; then echo "ALERT"; elif [[ $warn_count -gt 0 ]]; then echo "WARN"; else echo "OK"; fi)"
  },
  "checks": {
    "external_connectivity": $(grep -c '\[OK\]' "$REPORT_FILE" 2>/dev/null | head -1 || echo 0),
    "cloud_infrastructure": {
      "vms_checked": $(grep -o 'VM Health' "$REPORT_FILE" | wc -l || echo 0),
      "docker_hosts": $(grep -o 'Docker Status per VM' "$REPORT_FILE" | wc -l || echo 0)
    },
    "security": {
      "ports_analyzed": true,
      "firewall_checked": true,
      "malware_scans": true
    }
  },
  "vms": [
$(grep '| oci-\|| gcp-' "$REPORT_FILE" | grep -v '|-' | while IFS='|' read -r _ vm_name ip status uptime load mem _; do
    vm_name=$(echo "$vm_name" | xargs)
    ip=$(echo "$ip" | xargs)
    status=$(echo "$status" | xargs)
    uptime=$(echo "$uptime" | xargs)
    load=$(echo "$load" | xargs)
    mem=$(echo "$mem" | xargs)

    [[ -z "$vm_name" ]] && continue

    cat << VMEOF
    {
      "name": "$vm_name",
      "ip": "$ip",
      "status": "$status",
      "uptime": "$uptime",
      "load": "$load",
      "memory": "$mem"
    },
VMEOF
done | sed '$ s/,$//')
  ],
  "report_files": {
    "markdown": "$(basename "$REPORT_FILE")",
    "json": "$(basename "$REPORT_JSON")"
  }
}
EOF

    echo "JSON report generated: $REPORT_JSON"
}

# Send email with report (using swaks for attachment support)
send_email() {
    echo "Sending report via swaks with attachment..."

    # SMTP credentials (Mailu relay account)
    SMTP_USER="${SMTP_USER:-no-reply@diegonmarcos.com}"
    SMTP_PASS="${SMTP_PASS:-}"

    # Primary: swaks via Mailu SMTPS (port 465 implicit TLS) with auth
    if [[ -n "$SMTP_PASS" ]]; then
        # Use full report as body + attach both MD and JSON files
        if swaks --to "$TO_EMAIL" \
                 --from "$FROM_EMAIL" \
                 --server "130.110.251.193" \
                 --port 465 \
                 --tlsc \
                 --auth LOGIN \
                 --auth-user "$SMTP_USER" \
                 --auth-password "$SMTP_PASS" \
                 --header "Subject: $SUBJECT" \
                 --header "X-Report-ID: $(date +%s)" \
                 --header "X-Palantir-Monitor: true" \
                 --body "@$REPORT_FILE" \
                 --attach-type "text/markdown" \
                 --attach-name "health-report.md" \
                 --attach "@$REPORT_FILE" \
                 --attach-type "application/json" \
                 --attach-name "health-report.json" \
                 --attach "@$REPORT_JSON" \
                 --timeout 30 2>&1; then
            echo "[OK] Email sent via Mailu SMTPS with attachments (MD + JSON)"
            return 0
        fi
    fi

    echo "[WARN] SMTP auth failed or not configured, trying HTTP proxy..."

    # Fallback: HTTP SMTP proxy (sends inline, no attachment)
    local report_content
    report_content=$(cat "$REPORT_FILE")

    local response
    response=$(curl -s -X POST "${SMTP_PROXY_URL}" \
        -H "Content-Type: text/plain" \
        -H "X-API-Key: ${SMTP_PROXY_KEY}" \
        --data-binary "From: $FROM_EMAIL
To: $TO_EMAIL
Subject: $SUBJECT
Date: $(date -R)
Content-Type: text/plain; charset=utf-8

$report_content" \
        --max-time 30 2>&1)

    if echo "$response" | grep -qi "delivered\|success\|250"; then
        echo "[OK] Email sent via HTTP proxy (inline report)"
        return 0
    else
        echo "[WARN] HTTP proxy failed: $response"
    fi

    # Final fallback: ntfy notification
    echo "Trying ntfy notification..."
    if curl -s -X POST "https://rss.diegonmarcos.com/palantir" \
         -H "Title: $SUBJECT" \
         -H "Priority: high" \
         -H "Tags: cloud,monitor" \
         -d "$(head -50 "$REPORT_FILE")" \
         --max-time 10 2>&1 | grep -q "id"; then
        echo "[OK] Notification sent via ntfy"
        return 0
    fi

    echo "[FAIL] All delivery methods failed"
    return 1
}

# Main execution
main() {
    echo "=========================================="
    echo "Palantir Monitor - Cloud Health Check"
    echo "Started: $(date)"
    echo "=========================================="

    mkdir -p "$REPORT_DIR"

    init_report
    run_all_checks
    add_summary
    generate_json_report

    echo ""
    echo "Reports generated:"
    echo "  - Markdown: $REPORT_FILE"
    echo "  - JSON: $REPORT_JSON"
    echo ""

    # Display markdown report
    cat "$REPORT_FILE"

    echo ""
    echo "=========================================="

    send_email

    echo ""
    echo "Completed: $(date)"

    # Keep container running if in daemon mode
    if [[ "${DAEMON_MODE:-false}" == "true" ]]; then
        echo "Daemon mode - sleeping until next run..."
        sleep "${CHECK_INTERVAL:-86400}"
        exec "$0"
    fi
}

main "$@"
