#!/bin/bash
#
# Palantir Monitor - Cloud Infrastructure Health Report
# Generates comprehensive MD report and sends via email
#

set -o pipefail

# Configuration
REPORT_DIR="/app/reports"
REPORT_FILE="$REPORT_DIR/health-report-$(date +%Y%m%d-%H%M%S).md"
TO_EMAIL="me@diegonmarcos.com"
FROM_EMAIL="no-reply@diegonmarcos.com"
SMTP_PROXY_URL="${SMTP_PROXY_URL:-http://smtp.diegonmarcos.com:8080/}"
SMTP_PROXY_KEY="${SMTP_PROXY_KEY:-stalwart-proxy-key-2025}"

# Source configuration
source /app/config/endpoints.conf 2>/dev/null || true

# Initialize report
init_report() {
    cat > "$REPORT_FILE" << EOF
# Cloud Infrastructure Health Report

**Generated:** $(date '+%Y-%m-%d %H:%M:%S UTC')
**Host:** $(hostname)
**Report ID:** $(date +%s)

---

EOF
}

# Run all checks and append to report
run_all_checks() {
    echo "Running external connectivity checks..."
    /app/scripts/check-external.sh >> "$REPORT_FILE"

    echo "Running cloud provider checks..."
    /app/scripts/check-cloud.sh >> "$REPORT_FILE"

    echo "Running Docker container checks..."
    /app/scripts/check-docker.sh >> "$REPORT_FILE"

    echo "Running port/firewall analysis..."
    /app/scripts/check-ports.sh >> "$REPORT_FILE"

    echo "Running IP address inventory..."
    /app/scripts/check-ips.sh >> "$REPORT_FILE"

    echo "Running security checks..."
    /app/scripts/check-security.sh >> "$REPORT_FILE"

    echo "Collecting malware scan reports..."
    /app/scripts/check-sauron.sh >> "$REPORT_FILE"
}

# Add summary section
add_summary() {
    local ok_count=$(grep -c '\[OK\]' "$REPORT_FILE" 2>/dev/null || echo 0)
    local fail_count=$(grep -c '\[FAIL\]' "$REPORT_FILE" 2>/dev/null || echo 0)
    local warn_count=$(grep -c '\[WARN\]' "$REPORT_FILE" 2>/dev/null || echo 0)

    cat >> "$REPORT_FILE" << EOF

---

## Summary

| Status | Count |
|--------|-------|
| OK | $ok_count |
| FAIL | $fail_count |
| WARN | $warn_count |

---

*Generated by palantir-monitor*
*Report stored at: $REPORT_FILE*
EOF

    # Set subject based on failures
    if [[ $fail_count -gt 0 ]]; then
        SUBJECT="[ALERT] Cloud Health - $fail_count failures - $(date '+%Y-%m-%d')"
    elif [[ $warn_count -gt 0 ]]; then
        SUBJECT="[WARN] Cloud Health - $warn_count warnings - $(date '+%Y-%m-%d')"
    else
        SUBJECT="[OK] Cloud Health Report - $(date '+%Y-%m-%d')"
    fi
}

# Send email with report (using swaks for attachment support)
send_email() {
    echo "Sending report via swaks with attachment..."

    # Primary: swaks via Mailu SMTPS (port 465 implicit TLS)
    if swaks --to "$TO_EMAIL" \
             --from "$FROM_EMAIL" \
             --server "130.110.251.193" \
             --port 465 \
             --tlsc \
             --header "Subject: $SUBJECT" \
             --header "X-Report-ID: $(date +%s)" \
             --header "X-Palantir-Monitor: true" \
             --body "Cloud Infrastructure Health Report attached.\n\nGenerated: $(date '+%Y-%m-%d %H:%M:%S UTC')\nHost: $(hostname)" \
             --attach-type "text/markdown" \
             --attach-name "health-report.md" \
             --attach "@$REPORT_FILE" \
             --timeout 30 2>&1; then
        echo "[OK] Email sent via swaks with attachment"
        return 0
    else
        echo "[WARN] swaks to Mailu failed, trying Cloudflare MX..."

        # Fallback: swaks direct to Cloudflare MX
        if swaks --to "$TO_EMAIL" \
                 --from "$FROM_EMAIL" \
                 --server "route1.mx.cloudflare.net" \
                 --port 25 \
                 --header "Subject: $SUBJECT" \
                 --body "Cloud Infrastructure Health Report attached.\n\nGenerated: $(date)" \
                 --attach-type "text/markdown" \
                 --attach-name "health-report.md" \
                 --attach "@$REPORT_FILE" \
                 --timeout 30 2>&1; then
            echo "[OK] Email sent via Cloudflare MX"
            return 0
        else
            echo "[FAIL] All email methods failed"
            return 1
        fi
    fi
}

# Main execution
main() {
    echo "=========================================="
    echo "Palantir Monitor - Cloud Health Check"
    echo "Started: $(date)"
    echo "=========================================="

    mkdir -p "$REPORT_DIR"

    init_report
    run_all_checks
    add_summary

    echo ""
    echo "Report generated: $REPORT_FILE"
    echo ""

    # Display report
    cat "$REPORT_FILE"

    echo ""
    echo "=========================================="

    send_email

    echo ""
    echo "Completed: $(date)"

    # Keep container running if in daemon mode
    if [[ "${DAEMON_MODE:-false}" == "true" ]]; then
        echo "Daemon mode - sleeping until next run..."
        sleep "${CHECK_INTERVAL:-86400}"
        exec "$0"
    fi
}

main "$@"
