#!/bin/bash
#
# Palantir Monitor - Cloud Infrastructure Health Report
# Generates comprehensive MD report and sends via email
#

set -o pipefail

# Configuration
REPORT_DIR="/app/reports"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
REPORT_FILE="$REPORT_DIR/health-report-${TIMESTAMP}.md"
REPORT_JSON="$REPORT_DIR/health-report-${TIMESTAMP}.json"
TO_EMAIL="me@diegonmarcos.com"
FROM_EMAIL="no-reply@diegonmarcos.com"
SMTP_PROXY_URL="${SMTP_PROXY_URL:-http://smtp.diegonmarcos.com:8080/}"
SMTP_PROXY_KEY="${SMTP_PROXY_KEY:-stalwart-proxy-key-2025}"

# Source configuration
source /app/config/endpoints.conf 2>/dev/null || true

# Initialize report with topology
init_report() {
    cat > "$REPORT_FILE" << EOF
# 📊 Palantir Monitor - Cloud Infrastructure Health Report

**Generated:** $(date '+%Y-%m-%d %H:%M:%S UTC')
**Report ID:** $(date +%s)

---

## 🗺️ Infrastructure Topology

### Cloud Providers

| Provider | Region | Tier |
|----------|--------|------|
| Oracle Cloud (OCI) | eu-marseille-1 | Always Free |
| Google Cloud (GCP) | us-central1 | Free Tier |

### Virtual Machines

| VM | Provider | IP | RAM | Role | Services |
|----|----------|-----|-----|------|----------|
| oci-f-micro_1 | OCI | 130.110.251.193 | 1GB | Mail Server | Mailu |
| oci-f-micro_2 | OCI | 129.151.228.66 | 1GB | Analytics | Matomo |
| gcp-f-micro_1 | GCP | 35.226.147.64 | 1GB | Proxy/Auth | NPM, Authelia, ntfy |
| oci-p-flex_1 | OCI | 84.235.234.87 | 8GB | Media (Wake) | Photoprism, Syncthing |

### Domain Structure

| Domain | Purpose |
|--------|---------|
| diegonmarcos.com | Root domain (Cloudflare DNS) |
| mail.*.com | Email services (Mailu) |
| analytics.*.com | Web analytics (Matomo) |
| proxy.*.com | Reverse proxy admin (NPM) |
| auth.*.com | 2FA gateway (Authelia) |
| rss.*.com | Push notifications (ntfy) |
| photos.app.*.com | Photo management (wake-on-demand) |

### Docker Networks

| Network | Subnet | VM | Purpose |
|---------|--------|----|---------|
| mail_network | 172.20.0.0/24 | oci-f-micro_1 | Mailu stack |
| matomo_network | 172.21.0.0/24 | oci-f-micro_2 | Analytics |
| npm_default | 172.18.0.0/24 | gcp-f-micro_1 | Proxy services |
| dev_network | 172.24.0.0/24 | oci-p-flex_1 | Media apps |

---

EOF
}

# Run all checks and append to report
run_all_checks() {
    echo "Running external connectivity checks..."
    /app/scripts/check-external.sh >> "$REPORT_FILE"

    echo "Running cloud provider checks..."
    /app/scripts/check-cloud.sh >> "$REPORT_FILE"

    echo "Running Docker container checks..."
    /app/scripts/check-docker.sh >> "$REPORT_FILE"

    echo "Running port/firewall analysis..."
    /app/scripts/check-ports.sh >> "$REPORT_FILE"

    echo "Running IP address inventory..."
    /app/scripts/check-ips.sh >> "$REPORT_FILE"

    echo "Running security checks..."
    /app/scripts/check-security.sh >> "$REPORT_FILE"

    echo "Collecting malware scan reports..."
    /app/scripts/check-sauron.sh >> "$REPORT_FILE"
}

# Add summary section
add_summary() {
    # Count emoji status indicators (✅ ❌ ⚠️)
    local ok_count=$(grep -o '✅' "$REPORT_FILE" 2>/dev/null | wc -l || echo 0)
    local fail_count=$(grep -o '❌' "$REPORT_FILE" 2>/dev/null | wc -l || echo 0)
    local warn_count=$(grep -o '⚠️' "$REPORT_FILE" 2>/dev/null | wc -l || echo 0)
    local total=$((ok_count + fail_count + warn_count))

    cat >> "$REPORT_FILE" << EOF

---

## 📈 Overall Summary

| Metric | Value |
|--------|-------|
| ✅ Passed | $ok_count |
| ❌ Failed | $fail_count |
| ⚠️ Warnings | $warn_count |
| **Total Checks** | **$total** |

### Health Score: $(echo "scale=0; $ok_count * 100 / ($total + 1)" | bc)%

---

*🤖 Generated by Palantir Monitor v2.0*
*📍 Report: $REPORT_FILE*
EOF

    # Set subject based on failures
    if [[ $fail_count -gt 0 ]]; then
        SUBJECT="🚨 [ALERT] Cloud Health - $fail_count failures - $(date '+%Y-%m-%d')"
    elif [[ $warn_count -gt 0 ]]; then
        SUBJECT="⚠️ [WARN] Cloud Health - $warn_count warnings - $(date '+%Y-%m-%d')"
    else
        SUBJECT="✅ [OK] Cloud Health Report - $(date '+%Y-%m-%d')"
    fi
}

# Generate JSON report
generate_json_report() {
    # Count emoji status indicators
    local ok_count=$(grep -o '✅' "$REPORT_FILE" 2>/dev/null | wc -l || echo 0)
    local fail_count=$(grep -o '❌' "$REPORT_FILE" 2>/dev/null | wc -l || echo 0)
    local warn_count=$(grep -o '⚠️' "$REPORT_FILE" 2>/dev/null | wc -l || echo 0)
    local total=$((ok_count + fail_count + warn_count))
    local health_score=$(echo "scale=0; $ok_count * 100 / ($total + 1)" | bc)

    cat > "$REPORT_JSON" << EOF
{
  "metadata": {
    "generated": "$(date '+%Y-%m-%dT%H:%M:%SZ')",
    "host": "$(hostname)",
    "report_id": "$(date +%s)",
    "timestamp": "$TIMESTAMP",
    "version": "2.0"
  },
  "summary": {
    "ok_count": $ok_count,
    "fail_count": $fail_count,
    "warn_count": $warn_count,
    "total_checks": $total,
    "health_score": $health_score,
    "status": "$(if [[ $fail_count -gt 0 ]]; then echo "ALERT"; elif [[ $warn_count -gt 0 ]]; then echo "WARN"; else echo "OK"; fi)"
  },
  "topology": {
    "providers": ["Oracle Cloud (OCI)", "Google Cloud (GCP)"],
    "regions": {
      "oci": "eu-marseille-1",
      "gcp": "us-central1"
    },
    "vms": [
      {"id": "oci-f-micro_1", "provider": "OCI", "ip": "130.110.251.193", "ram": "1GB", "role": "Mail Server", "services": ["Mailu"]},
      {"id": "oci-f-micro_2", "provider": "OCI", "ip": "129.151.228.66", "ram": "1GB", "role": "Analytics", "services": ["Matomo"]},
      {"id": "gcp-f-micro_1", "provider": "GCP", "ip": "35.226.147.64", "ram": "1GB", "role": "Proxy/Auth", "services": ["NPM", "Authelia", "ntfy"]},
      {"id": "oci-p-flex_1", "provider": "OCI", "ip": "84.235.234.87", "ram": "8GB", "role": "Media", "services": ["Photoprism", "Syncthing", "Radicale"], "mode": "wake-on-demand"}
    ],
    "domains": {
      "root": "diegonmarcos.com",
      "subdomains": ["mail", "analytics", "proxy", "auth", "rss", "cloud", "photos", "sync", "cal"]
    },
    "networks": [
      {"name": "mail_network", "subnet": "172.20.0.0/24", "vm": "oci-f-micro_1"},
      {"name": "matomo_network", "subnet": "172.21.0.0/24", "vm": "oci-f-micro_2"},
      {"name": "npm_default", "subnet": "172.18.0.0/24", "vm": "gcp-f-micro_1"},
      {"name": "dev_network", "subnet": "172.24.0.0/24", "vm": "oci-p-flex_1"}
    ]
  },
  "checks": {
    "external_connectivity": {
      "total": $(grep -A100 '1️⃣' "$REPORT_FILE" | grep -m1 'Total.*Checks' | grep -oP '\d+(?= \|)' | head -1 || echo 20),
      "ssh_accessible": $(grep -A100 '1️⃣' "$REPORT_FILE" | grep -c '✅.*SSH\|✅.*22' || echo 0),
      "https_accessible": $(grep -A100 '1️⃣' "$REPORT_FILE" | grep -c '✅.*HTTPS\|✅.*443' || echo 0)
    },
    "cloud_infrastructure": {
      "vms_online": $(grep -c '✅.*Online\|✅.*reachable' "$REPORT_FILE" 2>/dev/null || echo 0),
      "containers_running": $(grep -oP 'Running: \d+' "$REPORT_FILE" 2>/dev/null | grep -oP '\d+' | head -1 || echo 0),
      "containers_stopped": $(grep -oP 'Stopped: \d+' "$REPORT_FILE" 2>/dev/null | grep -oP '\d+' | head -1 || echo 0)
    },
    "ports": {
      "expected_open": $(grep -A100 '4️⃣' "$REPORT_FILE" | grep -c '✅' || echo 0),
      "unexpected_closed": $(grep -A100 '4️⃣' "$REPORT_FILE" | grep -c '❌' || echo 0),
      "database_ports_exposed": false
    },
    "security": {
      "ssl_certs_valid": $(grep -A100 '6️⃣' "$REPORT_FILE" 2>/dev/null | grep -c '✅.*days\|✅.*certificate' || echo 0),
      "security_headers_present": $(grep -A100 '6️⃣' "$REPORT_FILE" 2>/dev/null | grep -c '✅.*HSTS\|✅.*CSP\|✅.*X-' || echo 0),
      "malware_scanners_active": $(grep -A100 '7️⃣' "$REPORT_FILE" 2>/dev/null | grep -c '✅.*Sauron' || echo 0)
    }
  },
  "report_files": {
    "markdown": "$(basename "$REPORT_FILE")",
    "json": "$(basename "$REPORT_JSON")"
  }
}
EOF

    echo "JSON report generated: $REPORT_JSON"
}

# Send email with report (using swaks for attachment support)
send_email() {
    echo "Sending report via swaks with attachment..."

    # SMTP credentials (Mailu relay account)
    SMTP_USER="${SMTP_USER:-no-reply@diegonmarcos.com}"
    SMTP_PASS="${SMTP_PASS:-}"

    # Generate HTML version for email body
    local REPORT_HTML="$REPORT_DIR/health-report-${TIMESTAMP}.html"
    echo "Converting markdown to HTML for email body..."
    cat "$REPORT_FILE" | /app/scripts/md-to-html-v2.sh > "$REPORT_HTML"

    # Primary: swaks via Mailu SMTPS (port 465 implicit TLS) with auth
    if [[ -n "$SMTP_PASS" ]]; then
        # Use HTML as body + attach MD and JSON files
        if swaks --to "$TO_EMAIL" \
                 --from "$FROM_EMAIL" \
                 --server "130.110.251.193" \
                 --port 465 \
                 --tlsc \
                 --auth LOGIN \
                 --auth-user "$SMTP_USER" \
                 --auth-password "$SMTP_PASS" \
                 --header "Subject: $SUBJECT" \
                 --header "Content-Type: text/html; charset=utf-8" \
                 --header "X-Report-ID: $(date +%s)" \
                 --header "X-Palantir-Monitor: true" \
                 --body "@$REPORT_HTML" \
                 --attach-type "text/markdown" \
                 --attach-name "health-report.md" \
                 --attach "@$REPORT_FILE" \
                 --attach-type "application/json" \
                 --attach-name "health-report.json" \
                 --attach "@$REPORT_JSON" \
                 --timeout 30 2>&1; then
            echo "[OK] Email sent via Mailu SMTPS with HTML body + attachments (MD + JSON + HTML)"
            return 0
        fi
    fi

    echo "[WARN] SMTP auth failed or not configured, trying HTTP proxy..."

    # Fallback: HTTP SMTP proxy with HTML body (inline, no attachments)
    # Build multipart email in a temp file to avoid "Argument list too long"
    local EMAIL_TEMP="/tmp/palantir-email-$TIMESTAMP.eml"
    local boundary="----=_NextPart_$(date +%s%N)"

    # Build email header
    cat > "$EMAIL_TEMP" <<EOF
From: $FROM_EMAIL
To: $TO_EMAIL
Subject: $SUBJECT
Date: $(date -R)
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="$boundary"
X-Report-ID: $(date +%s)
X-Palantir-Monitor: true

--$boundary
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 7bit

EOF

    # Append HTML body
    cat "$REPORT_HTML" >> "$EMAIL_TEMP"

    # Append MD attachment
    cat >> "$EMAIL_TEMP" <<EOF

--$boundary
Content-Type: text/markdown; name="health-report.md"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="health-report.md"

EOF
    base64 -w 76 "$REPORT_FILE" >> "$EMAIL_TEMP"

    # Append JSON attachment
    cat >> "$EMAIL_TEMP" <<EOF

--$boundary
Content-Type: application/json; name="health-report.json"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="health-report.json"

EOF
    base64 -w 76 "$REPORT_JSON" >> "$EMAIL_TEMP"

    # Close multipart
    echo -e "\n--$boundary--" >> "$EMAIL_TEMP"

    # Send via HTTP proxy using file input
    local response
    response=$(curl -s -X POST "${SMTP_PROXY_URL}" \
        -H "Content-Type: text/plain" \
        -H "X-API-Key: ${SMTP_PROXY_KEY}" \
        --data-binary "@$EMAIL_TEMP" \
        --max-time 30 2>&1)

    # Cleanup temp file
    rm -f "$EMAIL_TEMP"

    if echo "$response" | grep -qi "delivered\|success\|250"; then
        echo "[OK] Email sent via HTTP proxy with HTML body + base64 attachments"
        return 0
    else
        echo "[WARN] HTTP proxy failed: $response"
    fi

    # Final fallback: ntfy notification
    echo "Trying ntfy notification..."
    if curl -s -X POST "https://rss.diegonmarcos.com/palantir" \
         -H "Title: $SUBJECT" \
         -H "Priority: high" \
         -H "Tags: cloud,monitor" \
         -d "$(head -50 "$REPORT_FILE")" \
         --max-time 10 2>&1 | grep -q "id"; then
        echo "[OK] Notification sent via ntfy"
        return 0
    fi

    echo "[FAIL] All delivery methods failed"
    return 1
}

# Main execution
main() {
    echo "=========================================="
    echo "Palantir Monitor - Cloud Health Check"
    echo "Started: $(date)"
    echo "=========================================="

    mkdir -p "$REPORT_DIR"

    init_report
    run_all_checks
    add_summary
    generate_json_report

    echo ""
    echo "Reports generated:"
    echo "  - Markdown: $REPORT_FILE"
    echo "  - JSON: $REPORT_JSON"
    echo ""

    # Display markdown report
    cat "$REPORT_FILE"

    echo ""
    echo "=========================================="

    send_email

    echo ""
    echo "Completed: $(date)"

    # Keep container running if in daemon mode
    if [[ "${DAEMON_MODE:-false}" == "true" ]]; then
        echo "Daemon mode - sleeping until next run..."
        sleep "${CHECK_INTERVAL:-86400}"
        exec "$0"
    fi
}

main "$@"
