FROM foxcpp/maddy:0.9

LABEL org.opencontainers.image.source="https://github.com/diegonmarcos/cloud"
LABEL org.opencontainers.image.description="Maddy Mail Server wrapped for GHCR"
LABEL cloud.diegonmarcos.from-image="foxcpp/maddy:0.9"
LABEL cloud.diegonmarcos.registry="ghcr.io/diegonmarcos"
