## Maddy Mail Server — declarative config (nix-generated)
## Source: ~/git/cloud/a_solutions/aa-sui_tools-maddy/src/
## Secrets substituted at deploy time by init.sh from .secrets

# ── Base variables ────────────────────────────────────────────────
$(hostname) = @@MAIL_DOMAIN@@
$(primary_domain) = @@DOMAIN@@
$(local_domains) = $(primary_domain)

# TLS: Caddy handles external TLS, Maddy uses self-signed for internal
tls self_signed

# ── Local storage & authentication ────────────────────────────────
auth.pass_table local_authdb {
    table sql_table {
        driver sqlite3
        dsn credentials.db
        table_name passwords
    }
}

storage.imapsql local_mailboxes {
    driver sqlite3
    dsn imapsql.db
}

# ── SMTP endpoints + message routing ─────────────────────────────
hostname $(hostname)

table.chain local_rewrites {
    optional_step regexp "(.+)\+(.+)@(.+)" "$1@$3"
    optional_step static {
        entry postmaster postmaster@$(primary_domain)
    }
}

msgpipeline local_routing {
    destination postmaster $(local_domains) {
        modify {
            replace_rcpt &local_rewrites
        }
        deliver_to &local_mailboxes
    }
    default_destination {
        reject 550 5.1.1 "User doesn't exist"
    }
}

# ── Inbound SMTP (port 25) — from smtp-proxy ─────────────────────
smtp tcp://0.0.0.0:25 {
    limits {
        all rate 20 1s
        all concurrency 10
    }

    dmarc yes
    check {
        require_mx_record
        dkim
        spf
    }

    source $(local_domains) {
        reject 501 5.1.8 "Use Submission for outgoing SMTP"
    }
    default_source {
        destination postmaster $(local_domains) {
            deliver_to &local_routing
        }
        default_destination {
            reject 550 5.1.1 "User doesn't exist"
        }
    }
}

# ── Submission (ports 465/587) — authenticated outbound ───────────
submission tls://0.0.0.0:465 tcp://0.0.0.0:587 {
    limits {
        all rate 50 1s
    }

    auth &local_authdb

    source $(local_domains) {
        check {
            authorize_sender {
                prepare_email &local_rewrites
                user_to_email identity
            }
        }

        destination postmaster $(local_domains) {
            deliver_to &local_routing
        }
        default_destination {
            modify {
                dkim $(primary_domain) $(local_domains) default
            }
            deliver_to &remote_queue
        }
    }
    default_source {
        reject 501 5.1.8 "Non-local sender domain"
    }
}

# ── Outbound relay (OCI primary) ──────────────────────────────────
target.remote outbound_delivery {
    limits {
        destination rate 20 1s
        destination concurrency 10
    }

    # Use OCI SMTP relay for all outbound
    smart_host {
        targets tcp://@@OCI_RELAY_HOST@@:@@OCI_RELAY_PORT@@
        auth plain ${OCI_RELAYUSER} ${OCI_RELAYPASSWORD}
        require_tls yes
    }

    mx_auth {
        dane
        mtasts {
            cache fs
            fs_dir mtasts_cache/
        }
        local_policy {
            min_tls_level encrypted
            min_mx_level none
        }
    }
}

target.queue remote_queue {
    target &outbound_delivery

    autogenerated_msg_domain $(primary_domain)
    bounce {
        destination postmaster $(local_domains) {
            deliver_to &local_routing
        }
        default_destination {
            reject 550 5.0.0 "Refusing to send DSNs to non-local addresses"
        }
    }
}

# ── IMAP access ───────────────────────────────────────────────────
imap tls://0.0.0.0:993 tcp://0.0.0.0:143 {
    auth &local_authdb
    storage &local_mailboxes
}
