```
  ┌─────────────────────────────────────────────────────────────┐
  │                                                             │
  │   CLOUD HEALTH DAILY — $DATE $TIME                          │
  │   Generated in $DURATION_S s                                │
  │                                                             │
  └─────────────────────────────────────────────────────────────┘
```

## Executive Summary

- **Fleet**: $FLEET_RUNNING / $FLEET_TOTAL containers running ($FLEET_UNHEALTHY unhealthy)
- **VMs**: $TOTAL_VMS · **Services**: $TOTAL_SERVICES · **Containers**: $TOTAL_CONTAINERS · **Domains**: $TOTAL_DOMAINS
- **Status**: $EXEC_CRITICAL critical · $EXEC_WARNINGS warnings · $EXEC_OK ok

### Top Issues

$ISSUES_TABLE

---

## VMs

$VMS_TABLE

---

## Public Endpoints

$ENDPOINTS_TABLE

---

## TLS Certificates

$CERTS_TABLE

---

## DNS (mail auth)

$DNS_TABLE

---

## Databases

$DATABASES_TABLE

---

## Object Storage (buckets)

$BUCKETS_TABLE

---

## Dagu Workflows

$DAGS_TABLE

---

## GitHub Actions — Recent Runs

$GHA_TABLE

---

## GHCR Packages

$GHCR_TABLE

---

## Drift

$DRIFT_TABLE

---

## Firewalls

$FIREWALL_TABLE

---

## FinOps — Cloud Costs

$FINOPS_TABLE

---

## Mail Health

$MAIL_SUMMARY

---

## Appendix — Full 11-Layer Diagnostic

_The following section is pulled verbatim from `cloud_health_full.md` (generated by `cloud-health-full-2`). It provides the 11-layer check framework + stack topology sections that the daily summary above does not otherwise surface._

$APPENDIX
