// Profile ▸ Connect — the logic behind POST /profile/connect/{start,fetch}.
//
// The superapp fetches ONE document: cloud-vault E0_configs/profile-secrets.json
// (plaintext JSON, generated by E0_configs/emit.py) plus its schema
// (E0_configs/schema.json). Two factors guard it:
//
//   1. the Authelia bearer — validated by Caddy's forward_auth/introspect-proxy
//      before the request arrives; it stamps X-Auth-User, which is the identity
//      a code is bound to;
//   2. a one-time code mailed to the owner mailbox, which the caller must echo
//      back to /fetch. A stolen bearer alone therefore reads nothing.
//
// The bundle is served AS IS from the read-only bind mount (#589): cloud-vault is
// a private repo and the file is plaintext there — the sops layer it used to
// carry is what made the phone's file import read nothing (#585). The two
// factors above are the whole guard; no age key or sops lives on this VM.
//
// Zero local imports on purpose: test-profile-connect.ts loads this module
// directly under `node` (native TS stripping), without the Fastify runtime.
import { createHash, randomInt, timingSafeEqual } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

export interface ProfileConnectCfg {
  mailTo: string;
  mailFrom: string;
  codeTtlS: number;
  resendCooldownS: number;
  maxAttempts: number;
  bundleDir: string;
  bundleFile: string;
  schemaFile: string;
}

// ── identity ───────────────────────────────────────────────────────────────

/**
 * The bearer identity Caddy stamped (introspect-proxy → X-Auth-User; the
 * Authelia cookie path → Remote-User). null means the request did not come
 * through the gate, and a mesh source address does NOT substitute for it here.
 */
export function identity(headers: Record<string, string | string[] | undefined>): string | null {
  const h = headers["x-auth-user"] ?? headers["remote-user"];
  const v = Array.isArray(h) ? h[0] : h;
  return v && v.trim() ? v.trim() : null;
}

// ── one-time codes ─────────────────────────────────────────────────────────

interface Pending {
  hash: Buffer;
  expiresAt: number;
  issuedAt: number;
  attemptsLeft: number;
}

export type IssueResult =
  | { ok: true; code: string; expiresIn: number }
  | { ok: false; error: "cooldown"; retryAfter: number };

export type VerifyResult =
  | { ok: true }
  | { ok: false; error: "no_code" | "expired" | "too_many_attempts" }
  | { ok: false; error: "bad_code"; attemptsLeft: number };

const sha = (s: string): Buffer => createHash("sha256").update(s).digest();

/**
 * In-memory, per-identity code store. One live code per identity; a code is
 * single-use and dies on success, on expiry, or after maxAttempts wrong
 * guesses. In-memory is deliberate: a restart simply voids pending codes, and
 * nothing about a code is worth persisting.
 */
export class CodeStore {
  private pending = new Map<string, Pending>();
  private cfg: Pick<ProfileConnectCfg, "codeTtlS" | "resendCooldownS" | "maxAttempts">;

  constructor(cfg: Pick<ProfileConnectCfg, "codeTtlS" | "resendCooldownS" | "maxAttempts">) {
    this.cfg = cfg;
  }

  issue(user: string, now: number): IssueResult {
    const cur = this.pending.get(user);
    if (cur && now < cur.expiresAt) {
      const wait = cur.issuedAt + this.cfg.resendCooldownS * 1000 - now;
      if (wait > 0) return { ok: false, error: "cooldown", retryAfter: Math.ceil(wait / 1000) };
    }
    const code = String(randomInt(0, 1_000_000)).padStart(6, "0");
    this.pending.set(user, {
      hash: sha(code),
      issuedAt: now,
      expiresAt: now + this.cfg.codeTtlS * 1000,
      attemptsLeft: this.cfg.maxAttempts,
    });
    return { ok: true, code, expiresIn: this.cfg.codeTtlS };
  }

  revoke(user: string): void {
    this.pending.delete(user);
  }

  verify(user: string, code: string, now: number): VerifyResult {
    const cur = this.pending.get(user);
    if (!cur) return { ok: false, error: "no_code" };
    if (now >= cur.expiresAt) {
      this.pending.delete(user);
      return { ok: false, error: "expired" };
    }
    if (timingSafeEqual(cur.hash, sha(code.trim()))) {
      this.pending.delete(user); // single use
      return { ok: true };
    }
    cur.attemptsLeft -= 1;
    if (cur.attemptsLeft <= 0) {
      this.pending.delete(user);
      return { ok: false, error: "too_many_attempts" };
    }
    return { ok: false, error: "bad_code", attemptsLeft: cur.attemptsLeft };
  }
}

// ── mail ───────────────────────────────────────────────────────────────────

/** "me@diegonmarcos.com" → "m•@diegonmarcos.com": enough to recognise, not to harvest. */
export function maskAddress(addr: string): string {
  const at = addr.lastIndexOf("@");
  if (at < 1) return "•";
  return `${addr[0]}•${addr.slice(at)}`;
}

/** The RFC 5322 message carrying the code. The code is the whole body. */
export function codeMail(cfg: Pick<ProfileConnectCfg, "mailFrom" | "mailTo" | "codeTtlS">, code: string, user: string, now: Date): string {
  return [
    `From: Cloud SuperApp <${cfg.mailFrom}>`,
    `To: <${cfg.mailTo}>`,
    `Subject: SuperApp Connect code: ${code}`,
    `Date: ${now.toUTCString()}`,
    `Message-ID: <profile-connect-${now.getTime()}@${cfg.mailFrom.split("@")[1] ?? "localhost"}>`,
    "MIME-Version: 1.0",
    "Content-Type: text/plain; charset=utf-8",
    "",
    `Your Cloud SuperApp Connect code is ${code}.`,
    "",
    `It expires in ${Math.round(cfg.codeTtlS / 60)} minutes and works once.`,
    `Requested by bearer identity: ${user}`,
    "If you did not ask for it, someone holds a valid Authelia bearer — revoke it.",
    "",
  ].join("\r\n");
}

// ── bundle ─────────────────────────────────────────────────────────────────

/** Which declared parts are absent on this host. Empty = ready to serve. */
export function missingParts(cfg: ProfileConnectCfg): string[] {
  const miss: string[] = [];
  if (!cfg.mailTo) miss.push("mail_to");
  if (!cfg.bundleDir || !existsSync(join(cfg.bundleDir, cfg.bundleFile))) miss.push("bundle");
  if (!cfg.bundleDir || !existsSync(join(cfg.bundleDir, cfg.schemaFile))) miss.push("schema");
  return miss;
}

/** The mounted bundle is not the plaintext export the phone can read. */
export class BundleError extends Error {}

/**
 * Read the bundle and its schema from the mount. A file that is still
 * sops-encrypted (a `sops` root, `ENC[…]` values) is refused: serving it would
 * hand the phone the exact file it cannot read (#585) — the vault emits
 * plaintext (#589), so ciphertext here means the mount is stale or wrong.
 */
export function loadBundle(cfg: ProfileConnectCfg): { schema: unknown; bundle: unknown } {
  let bundle: unknown;
  try {
    bundle = JSON.parse(readFileSync(join(cfg.bundleDir, cfg.bundleFile), "utf8"));
  } catch (e) {
    throw new BundleError(`bundle unreadable: ${(e as Error).message}`);
  }
  if (typeof bundle !== "object" || bundle === null || Array.isArray(bundle)) throw new BundleError("bundle is not a JSON object");
  const root = bundle as Record<string, unknown>;
  if ("sops" in root) throw new BundleError("bundle is sops-encrypted (sops root) — the vault emits plaintext since #589; re-sync the mount");
  if (!("schema_version" in root)) throw new BundleError("bundle has no schema_version");
  const schema = JSON.parse(readFileSync(join(cfg.bundleDir, cfg.schemaFile), "utf8"));
  return { schema, bundle };
}
