// Profile ▸ Connect — the logic behind POST /profile/connect/{start,fetch}.
//
// The superapp fetches ONE document: cloud-vault configs/profile-secrets.json
// (sops-encrypted, generated by configs/emit.py) plus its schema
// (configs/schema.json). Two factors guard it:
//
//   1. the Authelia bearer — validated by Caddy's forward_auth/introspect-proxy
//      before the request arrives; it stamps X-Auth-User, which is the identity
//      a code is bound to;
//   2. a one-time code mailed to the owner mailbox, which the caller must echo
//      back to /fetch. A stolen bearer alone therefore reads nothing.
//
// Decryption happens at REQUEST time with the server's own age key (a dedicated
// recipient of profile-secrets.json, not the fleet master key), so plaintext
// never touches disk here and the response is the only place it exists.
//
// Zero local imports on purpose: test-profile-connect.ts loads this module
// directly under `node` (native TS stripping), without the Fastify runtime.
import { createHash, randomInt, timingSafeEqual } from "node:crypto";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

export interface ProfileConnectCfg {
  mailTo: string;
  mailFrom: string;
  codeTtlS: number;
  resendCooldownS: number;
  maxAttempts: number;
  bundleDir: string;
  bundleFile: string;
  schemaFile: string;
  /** The age identity itself (AGE-SECRET-KEY-1…), never a path. */
  ageKey: string;
  sopsBin: string;
}

// ── identity ───────────────────────────────────────────────────────────────

/**
 * The bearer identity Caddy stamped (introspect-proxy → X-Auth-User; the
 * Authelia cookie path → Remote-User). null means the request did not come
 * through the gate, and a mesh source address does NOT substitute for it here.
 */
export function identity(headers: Record<string, string | string[] | undefined>): string | null {
  const h = headers["x-auth-user"] ?? headers["remote-user"];
  const v = Array.isArray(h) ? h[0] : h;
  return v && v.trim() ? v.trim() : null;
}

// ── one-time codes ─────────────────────────────────────────────────────────

interface Pending {
  hash: Buffer;
  expiresAt: number;
  issuedAt: number;
  attemptsLeft: number;
}

export type IssueResult =
  | { ok: true; code: string; expiresIn: number }
  | { ok: false; error: "cooldown"; retryAfter: number };

export type VerifyResult =
  | { ok: true }
  | { ok: false; error: "no_code" | "expired" | "too_many_attempts" }
  | { ok: false; error: "bad_code"; attemptsLeft: number };

const sha = (s: string): Buffer => createHash("sha256").update(s).digest();

/**
 * In-memory, per-identity code store. One live code per identity; a code is
 * single-use and dies on success, on expiry, or after maxAttempts wrong
 * guesses. In-memory is deliberate: a restart simply voids pending codes, and
 * nothing about a code is worth persisting.
 */
export class CodeStore {
  private pending = new Map<string, Pending>();
  private cfg: Pick<ProfileConnectCfg, "codeTtlS" | "resendCooldownS" | "maxAttempts">;

  constructor(cfg: Pick<ProfileConnectCfg, "codeTtlS" | "resendCooldownS" | "maxAttempts">) {
    this.cfg = cfg;
  }

  issue(user: string, now: number): IssueResult {
    const cur = this.pending.get(user);
    if (cur && now < cur.expiresAt) {
      const wait = cur.issuedAt + this.cfg.resendCooldownS * 1000 - now;
      if (wait > 0) return { ok: false, error: "cooldown", retryAfter: Math.ceil(wait / 1000) };
    }
    const code = String(randomInt(0, 1_000_000)).padStart(6, "0");
    this.pending.set(user, {
      hash: sha(code),
      issuedAt: now,
      expiresAt: now + this.cfg.codeTtlS * 1000,
      attemptsLeft: this.cfg.maxAttempts,
    });
    return { ok: true, code, expiresIn: this.cfg.codeTtlS };
  }

  revoke(user: string): void {
    this.pending.delete(user);
  }

  verify(user: string, code: string, now: number): VerifyResult {
    const cur = this.pending.get(user);
    if (!cur) return { ok: false, error: "no_code" };
    if (now >= cur.expiresAt) {
      this.pending.delete(user);
      return { ok: false, error: "expired" };
    }
    if (timingSafeEqual(cur.hash, sha(code.trim()))) {
      this.pending.delete(user); // single use
      return { ok: true };
    }
    cur.attemptsLeft -= 1;
    if (cur.attemptsLeft <= 0) {
      this.pending.delete(user);
      return { ok: false, error: "too_many_attempts" };
    }
    return { ok: false, error: "bad_code", attemptsLeft: cur.attemptsLeft };
  }
}

// ── mail ───────────────────────────────────────────────────────────────────

/** "me@diegonmarcos.com" → "m•@diegonmarcos.com": enough to recognise, not to harvest. */
export function maskAddress(addr: string): string {
  const at = addr.lastIndexOf("@");
  if (at < 1) return "•";
  return `${addr[0]}•${addr.slice(at)}`;
}

/** The RFC 5322 message carrying the code. The code is the whole body. */
export function codeMail(cfg: Pick<ProfileConnectCfg, "mailFrom" | "mailTo" | "codeTtlS">, code: string, user: string, now: Date): string {
  return [
    `From: Cloud SuperApp <${cfg.mailFrom}>`,
    `To: <${cfg.mailTo}>`,
    `Subject: SuperApp Connect code: ${code}`,
    `Date: ${now.toUTCString()}`,
    `Message-ID: <profile-connect-${now.getTime()}@${cfg.mailFrom.split("@")[1] ?? "localhost"}>`,
    "MIME-Version: 1.0",
    "Content-Type: text/plain; charset=utf-8",
    "",
    `Your Cloud SuperApp Connect code is ${code}.`,
    "",
    `It expires in ${Math.round(cfg.codeTtlS / 60)} minutes and works once.`,
    `Requested by bearer identity: ${user}`,
    "If you did not ask for it, someone holds a valid Authelia bearer — revoke it.",
    "",
  ].join("\r\n");
}

// ── bundle ─────────────────────────────────────────────────────────────────

/** Which declared parts are absent on this host. Empty = ready to serve. */
export function missingParts(cfg: ProfileConnectCfg): string[] {
  const miss: string[] = [];
  if (!cfg.mailTo) miss.push("mail_to");
  if (!cfg.ageKey.startsWith("AGE-SECRET-KEY-1")) miss.push("age_key");
  if (!cfg.bundleDir || !existsSync(join(cfg.bundleDir, cfg.bundleFile))) miss.push("bundle");
  if (!cfg.bundleDir || !existsSync(join(cfg.bundleDir, cfg.schemaFile))) miss.push("schema");
  if (!cfg.sopsBin || !existsSync(cfg.sopsBin)) miss.push("sops");
  return miss;
}

export class DecryptError extends Error {}

/**
 * Decrypt the bundle with sops and the server's age key. Only SOPS_AGE_KEY and
 * PATH reach sops — no inherited SOPS_AGE_KEY_FILE (or a keys.txt under HOME)
 * can make it use a different identity than the one declared.
 */
export function loadBundle(cfg: ProfileConnectCfg): { schema: unknown; bundle: unknown } {
  let plain: string;
  try {
    plain = execFileSync(
      cfg.sopsBin,
      ["-d", "--input-type", "json", "--output-type", "json", join(cfg.bundleDir, cfg.bundleFile)],
      {
        encoding: "utf8",
        stdio: ["ignore", "pipe", "pipe"],
        env: { PATH: process.env.PATH ?? "/usr/bin:/bin", HOME: "/nonexistent", SOPS_AGE_KEY: cfg.ageKey },
        timeout: 15_000,
        maxBuffer: 64 * 1024 * 1024,
      },
    );
  } catch (e) {
    const err = e as { stderr?: string; message: string };
    // sops' stderr names the failing recipient/MAC, never a plaintext value.
    throw new DecryptError((err.stderr || err.message).trim().split("\n").slice(-3).join(" | "));
  }
  const schema = JSON.parse(readFileSync(join(cfg.bundleDir, cfg.schemaFile), "utf8"));
  return { schema, bundle: JSON.parse(plain) };
}
