# AUTO-GENERATED by sync-topics.sh — do not edit manually
# Source: bc-obs_ntfy/src/topic-scanner.py CONFIGURED_TOPICS
[
  "dev_commits"
  "dev_pull-requests"
  "dev_releases"
  "deploy_ship"
  "deploy_containers"
  "health_mesh"
  "health_endpoints"
  "health_dns"
  "health_resources"
  "health_containers"
  "ops_backups"
  "ops_reports"
  "sec_audit"
  "sec_tls"
  "sec_connections"
  "sec_yara"
]
