import type { ServiceDefinition } from "./types.js";

export const SERVICE_DEFINITIONS: ServiceDefinition[] = [
  // ── OpenAPI services ──────────────────────────────────────────
  {
    name: "nocodb",
    displayName: "NocoDB",
    description: "No-code database platform with spreadsheet UI",
    vm: "oci-apps-1",
    wgIp: "10.0.0.2",
    port: 8085,
    domain: "db.diegonmarcos.com",
    api: {
      type: "openapi",
      specUrl: "http://10.0.0.2:8085/api/v1/meta/info",
      endpointCount: 0,
      description: "NocoDB REST API — tables, rows, views, fields",
    },
  },
  {
    name: "gitea",
    displayName: "Gitea",
    description: "Self-hosted Git service",
    vm: "oci-apps",
    wgIp: "10.0.0.6",
    port: 3000,
    api: {
      type: "openapi",
      specUrl: "http://10.0.0.6:3000/swagger.json",
      endpointCount: 0,
      description: "Gitea REST API — repos, users, orgs, issues",
    },
  },
  {
    name: "mattermost",
    displayName: "Mattermost",
    description: "Team messaging and collaboration",
    vm: "oci-apps",
    wgIp: "10.0.0.6",
    port: 8065,
    api: {
      type: "openapi",
      specUrl: "http://10.0.0.6:8065/api/v4/opengraph",
      endpointCount: 0,
      description: "Mattermost REST API v4 — channels, posts, users, teams",
    },
  },
  {
    name: "windmill",
    displayName: "Windmill",
    description: "Developer platform for scripts, flows, and apps",
    vm: "oci-analytics",
    wgIp: "10.0.0.4",
    port: 8000,
    api: {
      type: "openapi",
      specUrl: "http://10.0.0.4:8000/api/openapi.json",
      endpointCount: 0,
      description: "Windmill REST API — scripts, flows, schedules, resources",
    },
  },
  {
    name: "vaultwarden",
    displayName: "Vaultwarden",
    description: "Bitwarden-compatible password manager",
    vm: "gcp-proxy",
    wgIp: "10.0.0.1",
    port: 80,
    domain: "vault.diegonmarcos.com",
    api: {
      type: "openapi",
      endpointCount: 0,
      description: "Vaultwarden API — vaults, ciphers, organizations",
    },
  },
  {
    name: "authelia",
    displayName: "Authelia",
    description: "Authentication and authorization server",
    vm: "gcp-proxy",
    wgIp: "10.0.0.1",
    port: 9091,
    domain: "auth.diegonmarcos.com",
    api: {
      type: "openapi",
      specUrl: "http://10.0.0.1:9091/api/openapi.yml",
      endpointCount: 0,
      description: "Authelia API — configuration, user info, OIDC",
    },
  },

  // ── Custom REST services ──────────────────────────────────────
  {
    name: "matomo",
    displayName: "Matomo",
    description: "Web analytics platform",
    vm: "oci-analytics",
    wgIp: "10.0.0.4",
    port: 8080,
    domain: "analytics.diegonmarcos.com",
    api: {
      type: "custom-rest",
      endpointCount: 5,
      description: "Matomo Reporting API — visits, sites, actions, referrers",
    },
  },
  {
    name: "mailu",
    displayName: "Mailu",
    description: "Full-featured mail server",
    vm: "oci-mail",
    wgIp: "10.0.0.3",
    port: 8444,
    domain: "mail.diegonmarcos.com",
    api: {
      type: "custom-rest",
      endpointCount: 3,
      description: "Mailu Admin API — domains, users, aliases",
    },
  },
  {
    name: "syncthing",
    displayName: "Syncthing",
    description: "Continuous file synchronization",
    vm: "oci-mail",
    wgIp: "10.0.0.3",
    port: 8384,
    domain: "sync.diegonmarcos.com",
    api: {
      type: "custom-rest",
      endpointCount: 4,
      description: "Syncthing REST API — status, folders, devices, config",
    },
  },
  {
    name: "ntfy",
    displayName: "ntfy",
    description: "Push notification service",
    vm: "gcp-proxy",
    wgIp: "10.0.0.1",
    port: 8090,
    domain: "rss.diegonmarcos.com",
    api: {
      type: "custom-rest",
      endpointCount: 2,
      description: "ntfy API — publish messages, health check",
    },
  },
  {
    name: "ollama",
    displayName: "Ollama",
    description: "Local LLM inference server",
    vm: "oci-apps",
    wgIp: "10.0.0.6",
    port: 11434,
    api: {
      type: "custom-rest",
      endpointCount: 3,
      description: "Ollama API — chat completion, model listing, generation",
    },
  },

  // ── Custom protocol services ──────────────────────────────────
  {
    name: "radicale",
    displayName: "Radicale",
    description: "CalDAV/CardDAV calendar and contacts server",
    vm: "oci-mail",
    wgIp: "10.0.0.3",
    port: 5232,
    domain: "cal.diegonmarcos.com",
    api: {
      type: "custom-protocol",
      endpointCount: 3,
      description: "Radicale CalDAV — calendars, contacts, events (XML→JSON wrapper)",
    },
  },

  // ── No-API services ───────────────────────────────────────────
  {
    name: "codeserver",
    displayName: "Code Server",
    description: "VS Code in the browser",
    vm: "oci-apps-1",
    wgIp: "10.0.0.2",
    port: 8443,
    domain: "ide.diegonmarcos.com",
    api: { type: "no-api", endpointCount: 0, description: "No programmatic API" },
  },
  {
    name: "affine",
    displayName: "AFFiNE",
    description: "Knowledge base and whiteboard",
    vm: "oci-apps-1",
    wgIp: "10.0.0.2",
    port: 3010,
    domain: "drive-notes-affine.diegonmarcos.com",
    api: { type: "no-api", endpointCount: 0, description: "No programmatic API" },
  },
  {
    name: "photoprism",
    displayName: "PhotoPrism",
    description: "AI-powered photo management",
    vm: "oci-apps-1",
    wgIp: "10.0.0.2",
    port: 3013,
    domain: "photos.diegonmarcos.com",
    api: { type: "no-api", endpointCount: 0, description: "No programmatic API" },
  },
];
