FROM node:22-bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY code /app
ENTRYPOINT []
LABEL org.opencontainers.image.source="https://github.com/diegonmarcos/cloud"
CMD ["./entrypoint.sh"]
