#!/bin/bash
# Render one engine's pipe-delimited sections (stdin) into Markdown + HTML.
#   render.sh <engine-label> <md-out> <html-out>
# Both outputs come from ONE pass over the input so they can never disagree.
set -eu

ENGINE="$1"; MD="$2"; HTML="$3"
WINDOW_H="${WINDOW_H:-24}"
NOW=$(date '+%Y-%m-%d %H:%M %Z')

# Section titles and the column headers each one carries.
hdr_for() {
  case "$1" in
    ENGINE)    echo "Component|State";;
    SITES)     echo "Website|Pageviews|Visitors|Avg session (s)";;
    APPS)      echo "App|Events|Installs seen|app_open";;
    PAGES)     echo "Page|Views";;
    COUNTRIES) echo "Country|Visitors";;
    DEVICES)   echo "OS / Browser / Device|Visitors";;
    REFERRERS) echo "Referrer|Hits";;
    HOURLY)    echo "Hour|Events";;
    *)         echo "Key|Value";;
  esac
}
title_for() {
  case "$1" in
    ENGINE)    echo "Engine health";;
    SITES)     echo "Websites";;
    APPS)      echo "Android apps";;
    PAGES)     echo "Top pages";;
    COUNTRIES) echo "Countries";;
    DEVICES)   echo "OS / Browser / Device";;
    REFERRERS) echo "Referrers";;
    HOURLY)    echo "Hourly volume";;
    *)         echo "$1";;
  esac
}

RAW=$(cat)

# ── Markdown ──────────────────────────────────────────────────────────
{
  echo "# Cloud Analytics Report — ${ENGINE}"
  echo
  echo "**Window:** last ${WINDOW_H}h  ·  **Generated:** ${NOW}"
  echo
  SUM=$(printf '%s\n' "$RAW" | awk '/^##SUMMARY/{f=1;next}/^##/{f=0}f' | head -1)
  if [ -n "$SUM" ]; then
    echo "| Metric | Value |"; echo "|---|---|"
    echo "| Pageviews / actions | $(echo "$SUM" | cut -d'|' -f1) |"
    echo "| Unique visitors | $(echo "$SUM" | cut -d'|' -f2) |"
    echo "| Sessions / sources | $(echo "$SUM" | cut -d'|' -f3) |"
    echo
  fi
  for S in ENGINE SITES APPS PAGES COUNTRIES DEVICES REFERRERS HOURLY; do
    BODY=$(printf '%s\n' "$RAW" | awk -v s="^##$S\$" '$0~s{f=1;next}/^##/{f=0}f' | sed '/^$/d')
    echo "## $(title_for "$S")"; echo
    if [ -z "$BODY" ]; then
      echo "_No data in this window._"; echo; continue
    fi
    H=$(hdr_for "$S"); N=$(echo "$H" | awk -F'|' '{print NF}')
    echo "$H" | sed 's/|/ | /g; s/^/| /; s/$/ |/'
    printf '%s' '|'; i=0; while [ $i -lt "$N" ]; do printf '%s' '---|'; i=$((i+1)); done; echo
    printf '%s\n' "$BODY" | sed 's/|/ | /g; s/^/| /; s/$/ |/'
    echo
  done
  INBOX=$(printf '%s\n' "$RAW" | awk '/^##INBOX/{f=1;next}/^##/{f=0}f' | head -1)
  [ -n "${INBOX:-}" ] && { echo "## Receiver queue"; echo; echo "\`/inbox\` holds **${INBOX}** unprocessed hit(s)."; echo; }
  echo "---"
  echo "_Generated by \`cloud-analytics-daily\` from the ${ENGINE} database._"
} > "$MD"

# ── HTML (same data, email-safe inline styles) ────────────────────────
esc() { sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g'; }
{
  cat <<EOH
<!doctype html><html><body style="margin:0;padding:24px;background:#f6f7f9;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#1c1e21">
<div style="max-width:820px;margin:0 auto;background:#fff;border-radius:8px;padding:24px;border:1px solid #e3e5e8">
<h1 style="margin:0 0 4px;font-size:20px">Cloud Analytics Report — ${ENGINE}</h1>
<p style="margin:0 0 20px;color:#65676b;font-size:13px">Last ${WINDOW_H}h · generated ${NOW}</p>
EOH
  SUM=$(printf '%s\n' "$RAW" | awk '/^##SUMMARY/{f=1;next}/^##/{f=0}f' | head -1)
  if [ -n "$SUM" ]; then
    echo '<table style="border-collapse:collapse;width:100%;margin-bottom:20px;font-size:13px">'
    i=1
    for L in "Pageviews / actions" "Unique visitors" "Sessions / sources"; do
      V=$(echo "$SUM" | cut -d'|' -f$i)
      echo "<tr><td style=\"padding:6px 8px;border-bottom:1px solid #eef0f2;color:#65676b\">$L</td><td style=\"padding:6px 8px;border-bottom:1px solid #eef0f2;font-weight:600;text-align:right\">${V:-0}</td></tr>"
      i=$((i+1))
    done
    echo '</table>'
  fi
  for S in ENGINE SITES APPS PAGES COUNTRIES DEVICES REFERRERS HOURLY; do
    BODY=$(printf '%s\n' "$RAW" | awk -v s="^##$S\$" '$0~s{f=1;next}/^##/{f=0}f' | sed '/^$/d')
    echo "<h2 style=\"font-size:15px;margin:22px 0 8px;padding-bottom:6px;border-bottom:2px solid #1877f2\">$(title_for "$S")</h2>"
    if [ -z "$BODY" ]; then
      echo '<p style="color:#8a8d91;font-size:13px;margin:0">No data in this window.</p>'; continue
    fi
    echo '<table style="border-collapse:collapse;width:100%;font-size:13px"><tr>'
    hdr_for "$S" | tr '|' '\n' | while read -r C; do
      echo "<th style=\"text-align:left;padding:6px 8px;background:#f0f2f5;border-bottom:1px solid #dcdfe3;font-weight:600\">$C</th>"
    done
    echo '</tr>'
    printf '%s\n' "$BODY" | esc | while IFS= read -r ROW; do
      echo '<tr>'
      printf '%s\n' "$ROW" | tr '|' '\n' | while read -r C; do
        echo "<td style=\"padding:6px 8px;border-bottom:1px solid #eef0f2\">$C</td>"
      done
      echo '</tr>'
    done
    echo '</table>'
  done
  INBOX=$(printf '%s\n' "$RAW" | awk '/^##INBOX/{f=1;next}/^##/{f=0}f' | head -1)
  [ -n "${INBOX:-}" ] && echo "<p style=\"margin:18px 0 0;font-size:13px;color:#65676b\"><code>/inbox</code> holds <strong>${INBOX}</strong> unprocessed hit(s).</p>"
  echo '</div></body></html>'
} > "$HTML"

echo "rendered: $MD  $HTML"
