## Maddy Mail Server — declarative config (nix-generated)
## Source: ~/git/cloud/a_solutions/aa-sui_tools-maddy/src/
## Secrets substituted at deploy time by init.sh from .secrets

# ── Base variables ────────────────────────────────────────────────
$(hostname) = @MAIL_DOMAIN@
$(primary_domain) = @DOMAIN@
$(local_domains) = $(primary_domain)

# TLS: wildcard cert from Caddy (*.diegonmarcos.com)
tls file /data/tls/fullchain.pem /data/tls/privkey.pem

# ── Local storage & authentication ────────────────────────────────
auth.pass_table local_authdb {
    table sql_table {
        driver sqlite3
        dsn credentials.db
        table_name passwords
    }
}

storage.imapsql local_mailboxes {
    driver sqlite3
    dsn imapsql.db

    # Delivery-time routing. POSIX sh script reads /data/mail-rules.json and
    # returns exactly ONE destination folder per incoming message. Maddy has
    # no Sieve/tag system — this is pure MOVE. (Replaces the former post-hoc
    # IMAP polling sorter that killed the IMAP backend under load, and the
    # earlier Python wrapper that pretended to emit IMAP keyword flags.)
    imap_filter {
        command /usr/local/bin/mail-filter {account_name} {sender} {rcpt_to} {subject}
    }
}

# ── SMTP endpoints + message routing ─────────────────────────────
hostname $(hostname)

table.chain local_rewrites {
    optional_step regexp "(.+)\+(.+)@(.+)" "$1@$3"
    optional_step static {
        entry postmaster postmaster@$(primary_domain)
    }
}

msgpipeline local_routing {
    destination postmaster $(local_domains) {
        modify {
            replace_rcpt &local_rewrites
        }
        deliver_to &local_mailboxes
    }
    default_destination {
        reject 550 5.1.1 "User doesn't exist"
    }
}

# ── Inbound SMTP (port 25) — from smtp-proxy / CF Worker ──────────
smtp tcp://0.0.0.0:25 {
    limits {
        all rate 20 1s
        all concurrency 10
    }

    # ── Security: two-tier architecture ────────────────────────────────
    # Tier 1 (IP-based) — handled by smtp-proxy (has real sender IP via CF-Connecting-IP):
    #   require_matching_rdns   — PTR record must exist for sender IP
    #   dnsbl {                 — reject IPs listed in spam blocklists
    #       zen.spamhaus.org
    #       bl.spamcop.net
    #   }
    #   spf (IP check)          — verify sender IP is authorized by domain's SPF record
    #
    # These checks CANNOT run in Maddy because smtp-proxy connects from localhost
    # (127.0.0.1). Maddy doesn't support XCLIENT or Proxy Protocol to receive
    # the real sender IP. smtp-proxy does all IP checks before forwarding.
    #
    # Tier 2 (signature-based) — handled by Maddy (no IP needed):
    check {
        dkim
        spf
    }
    # DMARC is enabled by default — aligns DKIM/SPF with From header (p=reject)

    default_source {
        destination postmaster $(local_domains) {
            deliver_to &local_routing
        }
        default_destination {
            reject 550 5.1.1 "User doesn't exist"
        }
    }
}

# ── Submission (ports 465/587) — authenticated outbound ───────────
submission tls://0.0.0.0:465 tcp://0.0.0.0:587 {
    limits {
        all rate 50 1s
    }

    auth &local_authdb

    source $(local_domains) {
        check {
            authorize_sender {
                prepare_email &local_rewrites
                user_to_email identity
            }
        }

        # Maddy signs DKIM (selector: default), OCI relay adds second signature (oci-mrs-202604)
        default_destination {
            modify {
                dkim $(primary_domain) $(local_domains) default
            }
            deliver_to &remote_queue
        }
    }
    default_source {
        reject 501 5.1.8 "Non-local sender domain"
    }
}

# ── Outbound relay (OCI SMTP) ─────────────────────────────────────
target.smtp outbound_delivery {
    targets tcp://@OCI_RELAY_HOST@:@OCI_RELAY_PORT@
    auth plain ${OCI_RELAYUSER} ${OCI_RELAYPASSWORD}
    starttls yes
}

target.queue remote_queue {
    target &outbound_delivery

    autogenerated_msg_domain $(primary_domain)
    bounce {
        destination postmaster $(local_domains) {
            deliver_to &local_routing
        }
        default_destination {
            reject 550 5.0.0 "Refusing to send DSNs to non-local addresses"
        }
    }
}

# ── IMAP access ───────────────────────────────────────────────────
imap tls://0.0.0.0:993 tcp://0.0.0.0:143 {
    auth &local_authdb
    storage &local_mailboxes
}
