@version: 4.4
@include "scl.conf"

options {
    chain_hostnames(off);
    flush_lines(0);
    use_dns(no);
    use_fqdn(no);
    dns_cache(no);
    keep_hostname(yes);
    stats_freq(0);
};

source s_network {
    network(
        transport("tcp")
        port(5514)
        flags(no-parse)
    );
};

destination d_siem_jsonl {
    file("/var/log/siem/alerts.jsonl"
        create-dirs(yes)
    );
};

log {
    source(s_network);
    destination(d_siem_jsonl);
};
