{
  description = "Caddy - Declarative reverse proxy with automatic HTTPS (replaces NPM on gcp-proxy + oci-mail)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.11";
  };

  outputs = { self, nixpkgs }: let
    forAllSystems = nixpkgs.lib.genAttrs [ "x86_64-linux" "aarch64-linux" ];

    config = {
      container_name = "caddy";
      http_port = 80;
      https_port = 443;
      admin_port = 2019;
    };

    # ntfy topics — served as static JSON at /api/topics
    ntfyTopics = [
      "syslog"
      "github-releases"
      "alerts"
      "health"
      "backups"
    ];

    title = "Caddy Reverse Proxy";

    # All service IPs resolved via Hickory DNS per-service .app zones
    # No hardcoded WireGuard IPs — use <container>.app everywhere

    # ── Dashboard ────────────────────────────────────────────────
    # dashboard.html is generated by data/collect.sh (node script)
    # from the JSON data files in data/. Nix just copies it.

    # ── Security snippets ─────────────────────────────────────────

    # 1. Security headers (HSTS, anti-clickjacking, etc.)
    securityHeaders = ''
      (security_headers) {
        header {
          Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
          X-Content-Type-Options "nosniff"
          X-Frame-Options "SAMEORIGIN"
          Referrer-Policy "strict-origin-when-cross-origin"
          Permissions-Policy "camera=(), microphone=(), geolocation=()"
          -Server
        }
      }
    '';

    # 2. Rate limiting (100 req/min per IP — requires caddy-ratelimit plugin)
    rateLimiting = ''
      (rate_limiting) {
        rate_limit {
          zone global {
            key    {remote_host}
            events 100
            window 1m
          }
        }
      }
    '';

    # 3. Bot blocking (known malicious scanners only)
    blockBots = ''
      (block_bots) {
        @bad_bots header_regexp User-Agent "(?i)(sqlmap|nikto|masscan|nmap|zgrab|scrapy|dirbuster|gobuster|nuclei|wfuzz|havij|acunetix|nessus|openvas)"
        respond @bad_bots 403
      }
    '';

    # 4. Scanner path blocking (common exploit paths)
    blockScanners = ''
      (block_scanners) {
        @blocked_paths path /wp-admin* /wp-login* /xmlrpc.php /.env /.git* /phpmyadmin* /actuator* /solr* /console* /.aws* /cgi-bin/*
        respond @blocked_paths 404
      }
    '';

    # 5. Request size limits (10MB default)
    requestLimits = ''
      (request_limits) {
        request_body {
          max_size 10MB
        }
      }
    '';

    # 6. IP blocking (placeholder — ready to activate)
    ipBlock = ''
      (ip_block) {
        # @blocked_ips remote_ip 192.0.2.0/24
        # respond @blocked_ips 403
      }
    '';

    # 7. Access logging (JSON to mounted volume for fail2ban)
    accessLog = ''
      (access_log) {
        log {
          output file /var/log/caddy/access.log {
            roll_size 10mb
            roll_keep 5
          }
          format json
        }
      }
    '';

    # Combined security snippet (imports all layers)
    securitySnippet = ''
      (security) {
        import security_headers
        import block_bots
        import block_scanners
        import rate_limiting
        import ip_block
        import access_log
      }
    '';

    # Per-site imports: sec = full security + size limit, secNoLimit = security only
    sec = ''
        import security
        import request_limits'';

    secNoLimit = ''
        import security'';

    # ── Auth snippets ────────────────────────────────────────────
    # Authelia forward_auth — resolves via Hickory per-service zone (authelia.app)
    authelia = ''
        forward_auth authelia.app:9091 {
          uri /api/authz/forward-auth
          copy_headers Remote-User Remote-Groups Remote-Email Remote-Name
        }'';

    # Bearer token auth via introspect-proxy — resolves via Hickory (introspect-proxy.app)
    bearer = ''
        forward_auth introspect-proxy.app:4182 {
          method GET
          uri /auth
          copy_headers X-Auth-User X-Auth-Subject X-Auth-Email
        }'';

    # Site-level error handler for connection failures AND HTTP errors
    handleErrors = ''
      handle_errors {
        @backend_error expression `{err.status_code} == 502 || {err.status_code} == 503 || {err.status_code} == 504`
        handle @backend_error {
          root * /srv
          rewrite * /error.html
          file_server
        }
      }'';

    # Reusable protected block: bearer token → introspect-proxy, cookie → authelia
    mkProtected = upstream: ''
      @bearer header Authorization Bearer*
      handle @bearer {
    ${bearer}
        reverse_proxy ${upstream}
      }
      handle {
    ${authelia}
        reverse_proxy ${upstream}
      }
    '';

    # GitHub Pages reverse proxy (keeps subdomain URL in browser)
    mkGithubProxy = path: ''
      rewrite * /${path}{uri}
      reverse_proxy https://diegonmarcos.github.io {
        header_up Host diegonmarcos.github.io
      }
    '';

    # Same but with custom reverse_proxy block (for tls_insecure_skip_verify etc.)
    mkProtectedCustom = upstreamUrl: transportBlock: ''
      @bearer header Authorization Bearer*
      handle @bearer {
    ${bearer}
        reverse_proxy ${upstreamUrl} {
          ${transportBlock}
        }
      }
      handle {
    ${authelia}
        reverse_proxy ${upstreamUrl} {
          ${transportBlock}
        }
      }
    '';

    # mkDashboardMd and dashboardTemplate removed — dashboard.html
    # is now a static file generated by data/collect.sh (Node.js)

    mkCaddyfile = pkgs: pkgs.writeText "Caddyfile" ''
      {
        debug
        admin localhost:${toString config.admin_port}
        order respond before handle

        layer4 {
          # IMAPS — TLS passthrough to Mailu via WireGuard
          :993 {
            route {
              proxy {
                upstream mailu.app:993
              }
            }
          }
          # SMTPS — TLS passthrough to Mailu via WireGuard
          :465 {
            route {
              proxy {
                upstream mailu.app:465
              }
            }
          }
          # SMTP Submission (STARTTLS) — TCP passthrough to Mailu via WireGuard
          :587 {
            route {
              proxy {
                upstream mailu.app:587
              }
            }
          }
        }
      }

      # ════════════════════════════════════════════════════════════
      # SECURITY SNIPPETS
      # ════════════════════════════════════════════════════════════

      ${securityHeaders}
      ${rateLimiting}
      ${blockBots}
      ${blockScanners}
      ${requestLimits}
      ${ipBlock}
      ${accessLog}
      ${securitySnippet}

      # ════════════════════════════════════════════════════════════
      # PUBLIC / BYPASS (no auth)
      # ════════════════════════════════════════════════════════════

      # Authelia itself — resolves via Hickory per-service zone (authelia.app)
      auth.diegonmarcos.com {
    ${sec}
        reverse_proxy authelia.app:9091
        ${handleErrors}
      }

      # API hub — path-based routing to backend APIs
      api.diegonmarcos.com {
    ${sec}
        @root path /
        handle @root {
          ${mkGithubProxy "api"}
        }

        # C3 Dashboard — served from GitHub Pages (front/d-Cloud/mcp-api-swagger)
        @dash path /dash
        handle @dash {
          redir {path}/ permanent
        }
        handle_path /dash/* {
          rewrite * /mcp-api-swagger/{path}
          reverse_proxy https://diegonmarcos.github.io {
            header_up Host diegonmarcos.github.io
          }
        }

        # C3 — Cloud Control Center API
        # Public: OpenAPI spec (CORS handled by upstream @fastify/cors)
        handle /c3-api/docs/json {
          uri strip_prefix /c3-api
          reverse_proxy c3-api.app:8081
        }
        # Protected: all other endpoints through Authelia/bearer
        handle_path /c3-api/* {
          ${mkProtected "c3-api.app:8081"}
        }

        # C3 Services — Unified Service API Gateway
        # Public: OpenAPI spec (CORS handled by upstream @fastify/cors)
        handle /services/docs/json {
          uri strip_prefix /services
          reverse_proxy c3-services.app:8082
        }
        # Protected: all other endpoints through Authelia/bearer
        handle_path /services/* {
          ${mkProtected "c3-services.app:8082"}
        }

        handle /crawlee/openapi.json {
          uri strip_prefix /crawlee
          reverse_proxy crawlee.app:3000
        }
        handle_path /crawlee/* {
          ${mkProtected "crawlee.app:3000"}
        }
        handle {
          ${mkGithubProxy "api"}
        }
        ${handleErrors}
      }

      # Radicale CalDAV/CardDAV
      cal.diegonmarcos.com {
    ${sec}
        ${mkProtected "radicale.app:5232"}
        ${handleErrors}
      }

      # Mattermost team chat (WebSocket upgrade handled by Caddy automatically)
      chat.diegonmarcos.com {
    ${sec}
        # Mattermost API — has its own session auth, bypass Authelia
        handle /api/v4/* {
          reverse_proxy mattermost.app:8065
        }
        # Everything else — browser access with Authelia
        ${mkProtected "mattermost.app:8065"}
        ${handleErrors}
      }

      # Affine collaborative docs (100MB uploads, long timeouts)
      drive-notes-affine.diegonmarcos.com {
    ${secNoLimit}
        request_body {
          max_size 100MB
        }
        ${mkProtectedCustom "affine.app:3010" ''
          transport http {
            read_timeout 3600s
            write_timeout 3600s
          }
        ''}
        ${handleErrors}
      }

      # ── GitHub Pages reverse proxies (URL stays as subdomain) ──

      # Landing page + WKD (Web Key Directory for PGP)
      diegonmarcos.com, www.diegonmarcos.com {
    ${sec}
        # WKD — PGP public key discovery (no auth — must be public per spec)
        handle_path /.well-known/openpgpkey/* {
          root * /srv/wkd
          file_server
        }
        handle {
          ${mkGithubProxy "landpage"}
        }
        ${handleErrors}
      }

      # Linktree
      linktree.diegonmarcos.com {
    ${sec}
        ${mkGithubProxy "linktree"}
        ${handleErrors}
      }

      # Cloud dashboard
      cloud.diegonmarcos.com {
    ${sec}
        handle /spec {
          redir /spec/ permanent
        }
        handle_path /spec/* {
          ${mkProtected "c3-spec.app:3080"}
        }
        handle {
          ${mkGithubProxy "cloud"}
        }
        ${handleErrors}
      }

      # Nexus
      nexus.diegonmarcos.com {
    ${sec}
        ${mkGithubProxy "nexus"}
        ${handleErrors}
      }

      # Suite apps dashboard
      suite.diegonmarcos.com {
    ${sec}
        ${mkGithubProxy "suite"}
        ${handleErrors}
      }

      # Maps
      maps.diegonmarcos.com {
    ${sec}
        ${mkGithubProxy "mymaps"}
        ${handleErrors}
      }

      # ════════════════════════════════════════════════════════════
      # ANALYTICS — Matomo (public tracking + protected admin)
      # ════════════════════════════════════════════════════════════

      analytics.diegonmarcos.com {
    ${sec}
        # Public tracking endpoints (no auth — called by portfolio sites)
        @tracking {
          path /matomo.js /matomo.php /piwik.js /piwik.php /collect.php /api.php /track.php
          path /js/*
        }
        handle @tracking {
          reverse_proxy matomo.app:8080
        }

        # Umami Analytics (path-based, strip /umami prefix before proxying)
        @umami_public {
          path /umami/script.js /umami/api/send
        }
        handle @umami_public {
          uri strip_prefix /umami
          reverse_proxy umami.app:3000
        }
        handle_path /umami/* {
          @umami_bearer header Authorization Bearer*
          handle @umami_bearer {
        ${bearer}
            reverse_proxy umami.app:3000
          }
          handle {
        ${authelia}
            reverse_proxy umami.app:3000
          }
        }
        @umami_root path /umami
        handle @umami_root {
          redir /umami/ permanent
        }

        # Protected Matomo admin dashboard (catch-all for non-umami, non-tracking)
        ${mkProtected "matomo.app:8080"}

        ${handleErrors}
      }

      # ════════════════════════════════════════════════════════════
      # AUTHELIA-PROTECTED (bearer token bypass for CLI/API)
      # ════════════════════════════════════════════════════════════

      # PhotoPrism
      photos.diegonmarcos.com {
    ${sec}
        # Root path → landing page (proxied, keeps our domain)
        @root path /
        handle @root {
          ${mkGithubProxy "myphotos"}
        }

        # All other paths → auth + PhotoPrism
        ${mkProtected "photoprism.app:3013"}
        ${handleErrors}
      }

      # Mailu webmail (upstream is HTTPS with self-signed cert)
      mail.diegonmarcos.com {
    ${sec}
        # Root path → landing page (proxied, keeps our domain)
        @root path /
        handle @root {
          ${mkGithubProxy "mymail"}
        }

        # All other paths → auth + Mailu
        ${mkProtectedCustom "https://mailu.app:8444" ''
          transport http {
            tls_insecure_skip_verify
          }''}
        ${handleErrors}
      }

      # Dagu workflow scheduler
      workflows.diegonmarcos.com {
    ${sec}
        ${mkProtected "dagu.app:8070"}
        ${handleErrors}
      }

      # Code Server IDE (WebSocket support is automatic in Caddy)
      ide.diegonmarcos.com {
    ${sec}
        ${mkProtected "code-server.app:8443"}
        ${handleErrors}
      }

      # NocoDB
      db.diegonmarcos.com {
    ${sec}
        ${mkProtected "nocodb.app:8085"}
        ${handleErrors}
      }

      # App hub (path-based routing)
      app.diegonmarcos.com {
    ${sec}
        handle_path /windmill/* {
          ${mkProtected "windmill-app.app:8000"}
        }
        handle_path /etherpad/* {
          ${mkProtected "etherpad.app:3012"}
        }
        handle_path /filebrowser/* {
          ${mkProtected "filebrowser.app:3015"}
        }
        handle_path /hedgedoc/* {
          ${mkProtected "hedgedoc.app:3018"}
        }
        handle_path /revealmd/* {
          ${mkProtected "revealmd.app:3014"}
        }
        handle_path /dozzle/* {
          ${mkProtected "dozzle.app:9999"}
        }
        handle_path /grafana/* {
          ${mkProtected "grafana.app:3016"}
        }
        handle_path /gitea/* {
          ${mkProtected "gitea.app:3017"}
        }
        handle_path /crawlee/* {
          ${mkProtected "crawlee-ui.app:3001"}
        }
        handle {
          respond "Not Found" 404
        }
        ${handleErrors}
      }

      # Grist Sheets
      sheets.diegonmarcos.com {
    ${sec}
        ${mkProtected "grist.app:3011"}
        ${handleErrors}
      }

      # Infrastructure dashboard (static HTML generated from flake data)
      proxy.diegonmarcos.com {
    ${sec}
        @bearer header Authorization Bearer*
        handle @bearer {
    ${bearer}
          root * /srv
          rewrite * /dashboard.html
          file_server
        }
        handle {
    ${authelia}
          root * /srv
          rewrite * /dashboard.html
          file_server
        }
        ${handleErrors}
      }

      # Vaultwarden — resolves via Hickory (vaultwarden.app), port 8880 avoids Caddy's 80
      vault.diegonmarcos.com {
    ${sec}
        ${mkProtected "vaultwarden.app:8880"}
        ${handleErrors}
      }

      # ntfy notifications — 3-tier auth:
      # 1. Authelia JWT (eyJ...) → introspect-proxy → ntfy
      # 2. ntfy native tokens (tk_...) → pass through, ntfy validates internally
      # 3. Browser cookie sessions → Authelia forward_auth → ntfy
      rss.diegonmarcos.com {
    ${sec}
        handle /setup {
    ${authelia}
          root * /srv
          rewrite * /ntfy-setup.html
          file_server
        }
        @authelia_jwt header_regexp Authorization "^Bearer eyJ"
        handle @authelia_jwt {
    ${bearer}
          reverse_proxy ntfy.app:8090
        }
        @ntfy_token header_regexp Authorization "^Bearer tk_"
        handle @ntfy_token {
          reverse_proxy ntfy.app:8090
        }
        handle {
    ${authelia}
          reverse_proxy ntfy.app:8090
        }
        ${handleErrors}
      }

      # ════════════════════════════════════════════════════════════
      # MCP — Streamable HTTP endpoints for Claude Code MCP clients
      # ════════════════════════════════════════════════════════════

      mcp.diegonmarcos.com {
    ${sec}
        handle_path /c3-mcp/* {
          reverse_proxy c3-mcp.app:3100 {
            flush_interval -1
          }
        }
        handle_path /c3-services-mcp/* {
          reverse_proxy c3-services-mcp.app:3101 {
            flush_interval -1
          }
        }
        handle_path /mattermost-mcp/* {
          reverse_proxy mattermost-mcp.app:3102 {
            flush_interval -1
          }
        }
        handle_path /mailu-mcp/* {
          reverse_proxy mailu-mcp.app:3103 {
            flush_interval -1
          }
        }
        handle_path /g-workspace/* {
          reverse_proxy g-workspace-mcp.app:3104 {
            flush_interval -1
          }
        }
        handle {
          respond "MCP Hub — use /c3-mcp/mcp, /c3-services-mcp/mcp, /mattermost-mcp/mcp, /mailu-mcp/mcp, /g-workspace/mcp" 200
        }
        ${handleErrors}
      }

      # ════════════════════════════════════════════════════════════
      # CATCH-ALL — Custom error page for unknown/unconfigured domains
      # ════════════════════════════════════════════════════════════

      *.diegonmarcos.com {
    ${secNoLimit}
        tls {
          dns cloudflare {env.CF_API_TOKEN}
        }
        root * /srv
        rewrite * /error.html
        file_server
      }

    '';

    docker = import ../../_shared/docker.nix;

    mkDockerCompose = pkgs: docker.mkCompose pkgs {
      banner = docker.banner "~/git/cloud/a_solutions/bb-sec_caddy/src/flake.nix";

      services.caddy = docker.mkService {
        name = "caddy";
        image = "ghcr.io/diegonmarcos/caddy-l4:latest";
        container_name = config.container_name;
        networkMode = "host";
        env_file = [ ".secrets" ];
        volumes = [
          "./Caddyfile:/etc/caddy/Caddyfile:ro"
          "./error.html:/srv/error.html:ro"
          "./dashboard.html:/srv/dashboard.html:ro"
          "./ntfy-setup.html:/srv/ntfy-setup.html:ro"
          "./wkd:/srv/wkd:ro"
          "./logs:/var/log/caddy"
          "caddy_data:/data"
          "caddy_config:/config"
        ];
        startAfter = [ "introspect-proxy" ];
        capAdd = [ "NET_BIND_SERVICE" ];  # needed for ports 80/443
        skipReadOnly = true;  # caddy writes to /data, /config, /var/log
      };

      services.introspect-proxy = docker.mkService {
        name = "introspect-proxy";
        build = "./introspect-proxy";
        image = "introspect-proxy:latest";
        networkMode = "host";
        environment = {
          JWKS_URL = "https://auth.diegonmarcos.com/jwks.json";
          ISSUER = "https://auth.diegonmarcos.com";
          REQUIRED_SCOPE = "authelia.bearer.authz";
          DEBUG = "\"true\"";
        };
        memLimit = "96M";
        memReservation = "48M";
        healthcheck = {
          test = ''["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:4182/health')"]'';
          interval = "30s";
          timeout = "5s";
          retries = 3;
          start_period = "10s";
        };
      };

      volumes.caddy_data = { driver = "local"; };
      volumes.caddy_config = { driver = "local"; };
    };

  in {
    packages = forAllSystems (system: let
      pkgs = nixpkgs.legacyPackages.${system};
    in let
      defaultPkg = pkgs.runCommand "caddy-configs" {} ''
        mkdir -p $out/introspect-proxy/app
        cp ${mkDockerCompose pkgs} $out/docker-compose.yml
        cp ${mkCaddyfile pkgs} $out/Caddyfile
        cp ${./error.html} $out/error.html
        cp ${./dashboard.html} $out/dashboard.html
        cp ${./ntfy-setup.html} $out/ntfy-setup.html
        mkdir -p $out/wkd/hu
        touch $out/wkd/policy
        cp ${./pgp-wkd-key.bin} $out/wkd/hu/s8y7oh5xrdpu9psba3i5ntk64ohouhga
        cp ${./introspect-proxy/Dockerfile} $out/introspect-proxy/Dockerfile
        cp ${./introspect-proxy/app/main.py} $out/introspect-proxy/app/main.py
        cp ${./introspect-proxy/app/requirements.txt} $out/introspect-proxy/app/requirements.txt
      '';
    in {
      default = defaultPkg;
      docs = docker.mkDocs pkgs { inherit title config defaultPkg; docsPath = ./docs; };
    });
  };
}
