{
  # Engine consolidation test 2026-04-15
  description = "Caddy - Declarative reverse proxy with automatic HTTPS (replaces NPM on gcp-proxy + oci-mail)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.11";
  };

  outputs = { self, nixpkgs }: let
    forAllSystems = nixpkgs.lib.genAttrs [ "x86_64-linux" "aarch64-linux" ];
    lib = nixpkgs.lib;
    ports = import ../../_shared/lib/port-enforcement.nix { buildJsonPath = ../build.json; };

    config = {
      container_name = "caddy";
      http_port = ports.valueOf "http";
      https_port = ports.valueOf "https";
      admin_port = ports.valueOf "admin";
    };

    title = "Caddy Reverse Proxy";

    # All service IPs resolved via Hickory DNS per-service .app zones
    # No hardcoded WireGuard IPs — use <container>.app everywhere

    # ── Dashboard ────────────────────────────────────────────────
    # dashboard.html is generated by data/collect.sh (node script)
    # from the JSON data files in data/. Nix just copies it.

    # ── Route data from cloud-data pipeline ─────────────────────
    # Single source of truth: build-proxy-caddy-routes.json (symlink →
    # I_cloud-data/build-proxy-caddy-routes.json). Engine resolves symlink
    # before nix build.
    caddyRoutes = builtins.fromJSON (builtins.readFile ./build-proxy-caddy-routes.json);

    # ── Security snippets (data-driven from caddyRoutes.security_snippets) ──
    # All values below are READ from build-proxy-caddy-routes.json —
    # sourced from bb-sec_caddy/build.json caddy_config.security_snippets.
    ss = caddyRoutes.security_snippets or {};

    # 1. Security headers (HSTS, anti-clickjacking, etc.)
    securityHeaders = let h = ss.security_headers; in ''
      (security_headers) {
        header {
          Strict-Transport-Security "max-age=${toString h.hsts_max_age}; includeSubDomains; preload"
          X-Content-Type-Options "nosniff"
          X-Frame-Options "${h.frame_options}"
          Referrer-Policy "${h.referrer_policy}"
          Permissions-Policy "${h.permissions_policy}"
          Access-Control-Allow-Origin "${h.cors_origin}"
          Access-Control-Allow-Methods "${h.cors_methods}"
          Access-Control-Allow-Headers "${h.cors_headers}"
          ${lib.concatMapStringsSep "\n          " (x: "-${x}") (h.hide_headers or [])}
        }
      }
    '';

    # 2. Rate limiting (requires caddy-ratelimit plugin)
    rateLimiting = let r = ss.rate_limit; in ''
      (rate_limiting) {
        rate_limit {
          zone ${r.zone} {
            key    ${r.key}
            events ${toString r.events}
            window ${r.window}
          }
        }
      }
    '';

    # 3. Bot blocking (known malicious scanners only)
    blockBots = let uas = lib.concatStringsSep "|" ss.bot_blocker.user_agents; in ''
      (block_bots) {
        @bad_bots header_regexp User-Agent "(?i)(${uas})"
        respond @bad_bots 403
      }
    '';

    # 4. Scanner path blocking (common exploit paths)
    blockScanners = let paths = lib.concatStringsSep " " ss.scanner_blocker.paths; in ''
      (block_scanners) {
        @blocked_paths path ${paths}
        respond @blocked_paths 404
      }
    '';

    # 5. Request size limits
    requestLimits = let r = ss.request_limits; in ''
      (request_limits) {
        request_body {
          max_size ${r.max_body}
        }
      }
    '';

    # 6. IP blocking (data-driven from ss.ip_block.cidrs[])
    ipBlock = let cidrs = ss.ip_block.cidrs or []; in ''
      (ip_block) {
        ${if cidrs == [] then "# no blocked CIDRs" else ''
        @blocked_ips remote_ip ${lib.concatStringsSep " " cidrs}
        respond @blocked_ips 403''}
      }
    '';

    # 7. Access logging (JSON to mounted volume for fail2ban)
    accessLog = let a = ss.access_log; in ''
      (access_log) {
        log {
          output file ${a.path} {
            roll_size ${a.roll_size}
            roll_keep ${toString a.roll_keep}
          }
          format ${a.format}
        }
      }
    '';

    # Combined security snippet (imports all layers)
    securitySnippet = ''
      (security) {
        import security_headers
        import block_bots
        import block_scanners
        import rate_limiting
        import ip_block
        import access_log
      }
    '';

    # Per-site imports: sec = full security + size limit, secNoLimit = security only
    sec = ''
        import security
        import request_limits'';

    secNoLimit = ''
        import security'';

    # ── Auth snippets (data-driven from caddyRoutes.auth + auth_upstreams) ──
    auth = caddyRoutes.auth or {};
    autheliaUpstream   = caddyRoutes.auth_upstreams.authelia or "10.0.0.1:9091";
    introspectUpstream = caddyRoutes.auth_upstreams.introspect_proxy or "10.0.0.1:4182";

    authelia = ''
        forward_auth ${autheliaUpstream} {
          uri ${auth.authelia_uri}
          copy_headers ${lib.concatStringsSep " " auth.authelia_copy}
        }'';

    bearer = ''
        forward_auth ${introspectUpstream} {
          method GET
          uri ${auth.introspect_uri}
          copy_headers ${lib.concatStringsSep " " auth.introspect_copy}
        }'';

    # Site-level error handler for connection failures AND HTTP errors
    handleErrors = let eh = caddyRoutes.error_handler or { status_codes = [502 503 504]; error_html = "/srv/error.html"; };
                       codesExpr = lib.concatMapStringsSep " || " (c: "{err.status_code} == ${toString c}") eh.status_codes;
                       errPath = eh.error_html; in ''
      handle_errors {
        @backend_error expression `${codesExpr}`
        handle @backend_error {
          root * ${lib.removeSuffix "/error.html" errPath}
          rewrite * /${baseNameOf errPath}
          file_server
        }
      }'';

    # Reusable protected block: bearer token → introspect-proxy, cookie → authelia
    mkProtected = upstream: ''
      @bearer header Authorization Bearer*
      handle @bearer {
    ${bearer}
        reverse_proxy ${upstream}
      }
      handle {
    ${authelia}
        reverse_proxy ${upstream}
      }
    '';

    # GitHub Pages reverse proxy (keeps subdomain URL in browser)
    mkGithubProxy = path: ''
      rewrite * /${path}{uri}
      reverse_proxy https://diegonmarcos.github.io {
        header_up Host diegonmarcos.github.io
      }
    '';

    # Same but with custom reverse_proxy block (for tls_insecure_skip_verify etc.)
    mkProtectedCustom = upstreamUrl: transportBlock: ''
      @bearer header Authorization Bearer*
      handle @bearer {
    ${bearer}
        reverse_proxy ${upstreamUrl} {
          ${transportBlock}
        }
      }
      handle {
    ${authelia}
        reverse_proxy ${upstreamUrl} {
          ${transportBlock}
        }
      }
    '';

    # ── Route generators ──────────────────────────────────────────

    # Generate L4 (layer4) blocks from l4_routes[]
    mkL4Block = route:
      let
        pp = route.proxy_protocol or false;
        ppLine = if pp then "\n                proxy_protocol v2" else "";
      in ''
          # ${route.comment or ""}
          :${toString route.port} {
            route {
              proxy {
                upstream ${route.upstream}${ppLine}
              }
            }
          }'';

    mkL4Section =
      if (caddyRoutes.l4_routes or []) == [] then ""
      else ''

        layer4 {
    ${lib.concatMapStringsSep "\n" mkL4Block caddyRoutes.l4_routes}
        }
    '';

    # Generate subdomain route blocks from routes[]
    mkSubdomainRoute = route:
      let
        isNoAuth = (route.auth or null) == "none";
        isWgOnly = route.wg_only or false;
        hasMaxUpload = (route.max_upload or null) != null;
        hasTimeout = (route.timeout or null) != null;
        hasTlsSkipVerify = route.tls_skip_verify or false;
        tlsServerName = route.tls_server_name or null;
        hasTlsServerName = tlsServerName != null;
        hasLandingPage = (route.landing_page or null) != null;
        hasBypassPaths = (route.bypass_paths or null) != null;

        secLine = if hasMaxUpload then secNoLimit else sec;
        uploadBlock = if hasMaxUpload then ''

        request_body {
          max_size ${route.max_upload}
        }'' else "";

        # Build the upstream URL — prepend https:// for TLS upstreams
        upstreamUrl = if hasTlsServerName || hasTlsSkipVerify then "https://${route.upstream}" else route.upstream;

        # Build the main proxy block
        proxyBlock =
          if isNoAuth && hasTlsSkipVerify then
            ''    reverse_proxy https://${route.upstream} {
          transport http {
        tls_insecure_skip_verify
      }
        }''
          else if isNoAuth then
            "    reverse_proxy ${route.upstream}"
          else if hasTlsServerName && hasTimeout then
            mkProtectedCustom upstreamUrl ''
          transport http {
            tls
            tls_server_name ${tlsServerName}
            read_timeout ${route.timeout}
            write_timeout ${route.timeout}
          }''
          else if hasTlsServerName then
            mkProtectedCustom upstreamUrl ''
          transport http {
            tls
            tls_server_name ${tlsServerName}
          }''
          else if hasTlsSkipVerify && hasTimeout then
            mkProtectedCustom upstreamUrl ''
          transport http {
            tls_insecure_skip_verify
            read_timeout ${route.timeout}
            write_timeout ${route.timeout}
          }''
          else if hasTlsSkipVerify then
            mkProtectedCustom upstreamUrl ''
          transport http {
            tls_insecure_skip_verify
          }''
          else if hasTimeout then
            mkProtectedCustom route.upstream ''
          transport http {
            read_timeout ${route.timeout}
            write_timeout ${route.timeout}
          }''
          else mkProtected route.upstream;

        # Landing page block (root path → GitHub Pages)
        landingBlock = if hasLandingPage then ''
        # Root path → landing page (proxied, keeps our domain)
        @root path /
        handle @root {
          ${mkGithubProxy route.landing_page}
        }

        # All other paths → auth + upstream'' else "";

        # Bypass paths (e.g. Mattermost /api/v4/* — direct proxy, no auth)
        bypassBlock = if hasBypassPaths then
          lib.concatMapStringsSep "\n" (p: ''
        handle ${p} {
          reverse_proxy ${route.upstream}
        }'') route.bypass_paths
        else "";

        wgBlock = if isWgOnly then ''
        @not_wg not remote_ip 10.0.0.0/24
        respond @not_wg "Forbidden" 403'' else "";

      in ''
      # ${route.comment or route.domain}
      ${route.domain} {
    ${secLine}${uploadBlock}
    ${wgBlock}
    ${bypassBlock}${landingBlock}
        ${proxyBlock}
        ${handleErrors}
      }
    '';

    # Generate GitHub Pages proxy blocks from github_pages_proxies[]
    mkGithubPagesRoute = route:
      let
        hasWkd = route.wkd or false;
        wkdBlock = if hasWkd then ''
        # WKD — PGP public key discovery (no auth — must be public per spec)
        handle_path /.well-known/openpgpkey/* {
          root * /srv/wkd
          file_server
        }
        handle {
          ${mkGithubProxy route.github_path}
        }'' else "    ${mkGithubProxy route.github_path}";
      in ''
      # ${route.comment or route.domain}
      ${route.domain} {
    ${sec}
    ${wkdBlock}
        ${handleErrors}
      }
    '';

    # Generate path-based route blocks from path_routes[]
    # Each entry generates one site block with handle_path directives
    mkPathRouteGroup = group:
      let
        hasLandingPage = (group.landing_page or null) != null;
        hasFallback = (group.fallback or null) != null;

        # Generate a single path entry
        mkPathEntry = path:
          let
            isGithubPages = (path.type or null) == "github_pages";
            hasRedirectBare = path.redirect_bare or false;
            hasPublicPaths = (path.public_paths or null) != null;

            redirectBlock = if hasRedirectBare then ''
        @${builtins.replaceStrings ["/"] [""] path.base_path}_bare path ${path.base_path}
        handle @${builtins.replaceStrings ["/"] [""] path.base_path}_bare {
          redir {path}/ permanent
        }
    '' else "";

            publicPathsBlock = if hasPublicPaths then
              lib.concatMapStringsSep "\n" (pp: ''
        handle ${pp} {
          uri strip_prefix ${path.base_path}
          reverse_proxy ${path.upstream}
        }'') path.public_paths
            else "";

            mainBlock =
              if isGithubPages then ''
        handle_path ${path.base_path}/* {
          rewrite * /${path.github_path}/{path}
          reverse_proxy https://diegonmarcos.github.io {
            header_up Host diegonmarcos.github.io
          }
        }''
              else ''
        handle_path ${path.base_path}/* {
          ${mkProtected path.upstream}
        }'';

          in "${redirectBlock}${publicPathsBlock}\n${mainBlock}";

        # Filter out stub entries (comment-only, no upstream/github_path)
        activePaths = builtins.filter (p: p ? upstream || (p.type or null) == "github_pages") group.paths;
        pathBlocks = lib.concatMapStringsSep "\n" mkPathEntry activePaths;

        landingRootBlock = if hasLandingPage then ''
        @root path /
        handle @root {
          ${mkGithubProxy group.landing_page}
        }
    '' else "";

        fallbackBlock = if hasFallback then ''
        handle {
          ${group.fallback}
        }'' else if hasLandingPage then ''
        handle {
          ${mkGithubProxy group.landing_page}
        }'' else "";

      in ''
      # ${group.comment or group.parent_domain}
      ${group.parent_domain} {
    ${sec}
    ${landingRootBlock}${pathBlocks}
    ${fallbackBlock}
        ${handleErrors}
      }
    '';

    # Generate MCP route blocks from mcp_routes[]
    mkMcpRouteGroup = group:
      let
        mkEndpoint = ep: ''
        handle_path ${ep.base_path}/* {
          reverse_proxy ${ep.upstream} {
            flush_interval -1
          }
        }'';
        endpointBlocks = lib.concatMapStringsSep "\n" mkEndpoint group.endpoints;
        fallbackMsg = group.fallback_message or "MCP Hub";
      in ''
      # ${group.comment or group.parent_domain}
      ${group.parent_domain} {
    ${sec}
    ${endpointBlocks}
        handle {
          respond "${fallbackMsg}" 200
        }
        ${handleErrors}
      }
    '';

    # Generate redirect blocks from redirects[]
    mkRedirectRoute = route: ''
      # ${route.comment or route.domain}
      ${route.domain} {
    ${sec}
        redir ${route.target} permanent
        ${handleErrors}
      }
    '';

    # ── Special route generators ──────────────────────────────────

    mkMailBlock =
      let mail = caddyRoutes.special.mail or null;
      in if mail == null then ""
      else let
        # Generate handler block for each path in paths[]
        mkMailPath = path:
          let
            isStatic = (path.type or null) == "static";
            isNoAuth = (path.auth or null) == "none";
            hasTlsSkipVerify = path.tls_skip_verify or false;
            hasAssetPaths = (path.asset_paths or null) != null;

            proxyBlock =
              if isNoAuth && hasTlsSkipVerify then
                ''reverse_proxy https://${path.upstream} {
              transport http {
                tls_insecure_skip_verify
              }
            }''
              else if isNoAuth then
                "reverse_proxy ${path.upstream}"
              else
                mkProtected path.upstream;

            mainBlock =
              if isStatic then ''
        # ${path.comment or path.base_path} (static)
        handle ${path.base_path}/config {
          root * /srv/mail
          rewrite * /servermail-config.html
          file_server
        }
        handle ${path.base_path}* {
          root * /srv/mail
          rewrite * /servermail.html
          file_server
        }''
              else ''
        # ${path.comment or path.base_path}
        handle_path ${path.base_path}/* {
          ${proxyBlock}
        }
        handle_path ${path.base_path} {
          ${proxyBlock}
        }'';

            # Additional asset path handlers (e.g., /snappymail/* for SnappyMail asset loading)
            assetBlocks = if hasAssetPaths then
              lib.concatMapStringsSep "\n" (ap: ''
        handle ${ap}/* {
          ${proxyBlock}
        }'') path.asset_paths
            else "";

          in "${mainBlock}\n${assetBlocks}";

        pathBlocks = lib.concatMapStringsSep "\n" mkMailPath (mail.paths or []);
      in ''
      # ${mail.comment or "mail"}
      ${mail.domain} {
    ${sec}
        # / → landing page (PUBLIC — no auth)
        @root path /
        handle @root {
          ${mkGithubProxy mail.landing_page}
        }

    ${pathBlocks}

        # Catch-all → landing page (serves CSS/JS assets from GitHub Pages)
        handle {
          ${mkGithubProxy mail.landing_page}
        }

        ${handleErrors}
      }
    '';

    mkNtfyBlock =
      let ntfy = caddyRoutes.special.ntfy or null;
      in if ntfy == null then ""
      else ''
      # ${ntfy.comment or "ntfy"}
      ${ntfy.domain} {
    ${sec}
        handle /setup {
    ${authelia}
          root * /srv
          rewrite * /ntfy-setup.html
          file_server
        }
        @authelia_jwt header_regexp Authorization "${auth.ntfy_jwt_pattern}"
        handle @authelia_jwt {
    ${bearer}
          reverse_proxy ${ntfy.upstream}
        }
        @ntfy_token header_regexp Authorization "${auth.ntfy_token_pattern}"
        handle @ntfy_token {
          reverse_proxy ${ntfy.upstream}
        }
        handle {
    ${authelia}
          reverse_proxy ${ntfy.upstream}
        }
        ${handleErrors}
      }
    '';

    mkAnalyticsBlock =
      let a = caddyRoutes.special.analytics or null;
      in if a == null then ""
      else let
        trackingPaths = lib.concatStringsSep " " a.public_tracking_paths;
        umamiPublicPaths = lib.concatStringsSep " " a.umami_public_paths;
      in ''
      # ${a.comment or "Analytics"}
      ${a.domain} {
    ${sec}
        # Public tracking endpoints (no auth — called by portfolio sites)
        @tracking {
          path ${trackingPaths}
        }
        handle @tracking {
          reverse_proxy ${a.matomo_upstream}
        }

        # Umami Analytics (path-based, strip /umami prefix before proxying)
        @umami_public {
          path ${umamiPublicPaths}
        }
        handle @umami_public {
          uri strip_prefix /umami
          reverse_proxy ${a.umami_upstream}
        }
        handle_path /umami/* {
          @umami_bearer header Authorization Bearer*
          handle @umami_bearer {
    ${bearer}
            reverse_proxy ${a.umami_upstream}
          }
          handle {
    ${authelia}
            reverse_proxy ${a.umami_upstream}
          }
        }
        @umami_root path /umami
        handle @umami_root {
          redir /umami/ permanent
        }

        # Protected Matomo admin dashboard (catch-all for non-umami, non-tracking)
        ${mkProtected a.matomo_upstream}

        ${handleErrors}
      }
    '';

    mkProxyDashboardBlock =
      let pd = caddyRoutes.special.proxy_dashboard or null;
      in if pd == null then ""
      else ''
      # ${pd.comment or "Proxy dashboard"}
      ${pd.domain} {
    ${sec}
        @bearer header Authorization Bearer*
        handle @bearer {
    ${bearer}
          root * /srv
          rewrite * /dashboard.html
          file_server
        }
        handle {
    ${authelia}
          root * /srv
          rewrite * /dashboard.html
          file_server
        }
        ${handleErrors}
      }
    '';

    # ── Internal HTTPS routes: portless *.app access via WireGuard ──
    # No auth, no security headers — WireGuard is the trust boundary
    # TLS via Caddy's internal CA (self-signed) — required because .app HSTS preload
    # Binds to 10.0.0.1:443 only (not public IP)
    mkInternalRoute = route: ''
      ${route.service} {
        bind 10.0.0.1
        tls internal
        reverse_proxy ${route.upstream}
      }
    '';

    # ── S3 bucket routes: proxy OCI Object Storage via .app short names ──
    # Prepends /<bucket> to the path, then proxies to OCI S3 endpoint
    mkS3Route = route: ''
      ${route.service} {
        bind 10.0.0.1
        tls internal
        rewrite * /${route.bucket}{uri}
        reverse_proxy ${route.s3_endpoint} {
          header_up Host ${route.s3_host}
        }
      }
    '';

    # ── all_app_urls: canonical per-port names {container}-{protocol}-{port}.app ──
    # Emitted alongside existing internal_routes[] so every declared port has a name.
    # HTTP/HTTPS protocols → reverse_proxy; TLS/STARTTLS/TCP/UDP are skipped here
    # (L4 passthrough handled by existing l4_routes, future pass may add SNI routing).
    # tls internal + on_demand → cert issued lazily on first request
    # (eager startup issuance for 70+ sites occasionally drops certs)
    mkCanonicalAppRoute = entry: ''
      ${entry.service} {
        bind 10.0.0.1
        tls internal {
          on_demand
        }
        reverse_proxy ${entry.upstream}
      }
    '';

    # Portless containers (workers/sidecars) → placeholder so the DNS name still resolves.
    msgs = caddyRoutes.messages or {};
    mkPortlessAppRoute = entry: ''
      ${entry.service} {
        bind 10.0.0.1
        tls internal {
          on_demand
        }
        respond "${msgs.portless_placeholder}" 204
      }
    '';

    # Filter all_app_urls[] for this pass: only HTTP/HTTPS canonical entries.
    canonicalHttpEntries = lib.filter
      (e: e.kind == "canonical" && (e.protocol == "http" || e.protocol == "https"))
      (caddyRoutes.all_app_urls or []);

    portlessEntries = lib.filter
      (e: e.kind == "portless")
      (caddyRoutes.all_app_urls or []);

    # De-duplicate against internal_routes[] so we never emit two blocks for the same hostname.
    internalRouteNames =
      let names = map (r: r.service) (caddyRoutes.internal_routes or []);
      in lib.genAttrs names (_: true);

    dedupedCanonicals = lib.filter
      (e: !(internalRouteNames.${e.service} or false))
      canonicalHttpEntries;

    dedupedPortless = lib.filter
      (e: !(internalRouteNames.${e.service} or false))
      portlessEntries;

    # ── .db zone: HTTPS catalog endpoints only ──
    # Every DB from all_db_urls[] becomes an HTTPS page describing where the actual
    # DB lives. No L4 TCP forwarding — gcp-proxy ports collide with postlite +
    # clients are better off connecting directly via WG (e.g. 10.0.0.6:5442).
    dbCatalogEntries = caddyRoutes.all_db_urls or [];

    mkDbPlaceholderRoute = e: ''
      ${e.service} {
        bind 10.0.0.1
        tls internal {
          on_demand
        }
        respond "DB catalog — container=${e.container or "?"} engine=${e.engine or "?"} port=${toString (e.port or 0)} upstream=${e.upstream or "(embedded)"} path=${e.path or "-"} vm=${e.vm or "-"}" 200
      }
    '';

    # ── Assemble the full Caddyfile ─────────────────────────────

    global = caddyRoutes.global or {};
    odt    = caddyRoutes.on_demand_tls or {};
    mkCaddyfile = pkgs: pkgs.writeText "Caddyfile" ''
      {
        # Upstreams use raw WG IPs (not DNS) — Caddy is the *.app target
        ${if (global.debug or false) then "debug" else ""}
        admin ${global.admin_bind}
        order ${global.order}
        auto_https ${global.auto_https}
        # On-demand TLS for internal .app/.db names (lazy cert issuance).
        # Ask endpoint below approves anything (WG mesh is the trust boundary).
        on_demand_tls {
          ask ${odt.ask_url}
        }
    ${mkL4Section}
      }

      # ── On-demand TLS ask endpoint ──
      :${lib.elemAt (lib.splitString ":" odt.ask_bind) 1} {
        bind ${lib.elemAt (lib.splitString ":" odt.ask_bind) 0}
        respond 200
      }

      # ════════════════════════════════════════════════════════════
      # SECURITY SNIPPETS
      # ════════════════════════════════════════════════════════════

      ${securityHeaders}
      ${rateLimiting}
      ${blockBots}
      ${blockScanners}
      ${requestLimits}
      ${ipBlock}
      ${accessLog}
      ${securitySnippet}

      # ════════════════════════════════════════════════════════════
      # SUBDOMAIN ROUTES (from routes[])
      # ════════════════════════════════════════════════════════════

    ${lib.concatMapStringsSep "\n" mkSubdomainRoute caddyRoutes.routes}

      # ════════════════════════════════════════════════════════════
      # GITHUB PAGES PROXIES (from github_pages_proxies[])
      # ════════════════════════════════════════════════════════════

    ${lib.concatMapStringsSep "\n" mkGithubPagesRoute caddyRoutes.github_pages_proxies}

      # ════════════════════════════════════════════════════════════
      # PATH-BASED ROUTES (from path_routes[])
      # ════════════════════════════════════════════════════════════

    ${lib.concatMapStringsSep "\n" mkPathRouteGroup caddyRoutes.path_routes}

      # ════════════════════════════════════════════════════════════
      # MCP ROUTES (from mcp_routes[])
      # ════════════════════════════════════════════════════════════

    ${lib.concatMapStringsSep "\n" mkMcpRouteGroup caddyRoutes.mcp_routes}

      # ════════════════════════════════════════════════════════════
      # REDIRECTS (from redirects[])
      # ════════════════════════════════════════════════════════════

    ${lib.concatMapStringsSep "\n" mkRedirectRoute (caddyRoutes.redirects or [])}

      # ════════════════════════════════════════════════════════════
      # SPECIAL ROUTES (from special{})
      # ════════════════════════════════════════════════════════════

    ${mkMailBlock}

    ${mkAnalyticsBlock}

    ${mkNtfyBlock}

    ${mkProxyDashboardBlock}

      # ════════════════════════════════════════════════════════════
      # INTERNAL ROUTES — portless *.app via HTTP:80 on WireGuard
      # No auth, no TLS — WireGuard mesh is the trust boundary
      # ════════════════════════════════════════════════════════════

    ${lib.concatMapStringsSep "\n" mkInternalRoute (caddyRoutes.internal_routes or [])}

      # ════════════════════════════════════════════════════════════
      # APP URL ALIASES — {container}-{protocol}-{port}.app canonical routes
      # Data-driven from build-proxy-caddy-routes.json → all_app_urls[]
      # HTTP/HTTPS only this pass — L4 protocols deferred to a future SNI-routed pass.
      # ════════════════════════════════════════════════════════════

    ${lib.concatMapStringsSep "\n" mkCanonicalAppRoute dedupedCanonicals}

    ${lib.concatMapStringsSep "\n" mkPortlessAppRoute dedupedPortless}

      # ════════════════════════════════════════════════════════════
      # DB ZONE — {container}-{engine}-{port}.db HTTPS catalog endpoints
      # Data source: build-proxy-caddy-routes.json → all_db_urls[]
      # Every entry returns a descriptor. TCP access goes direct (WG IPs).
      # ════════════════════════════════════════════════════════════

    ${lib.concatMapStringsSep "\n" mkDbPlaceholderRoute dbCatalogEntries}

      # ════════════════════════════════════════════════════════════
      # S3 ROUTES — OCI Object Storage via .app short names
      # ════════════════════════════════════════════════════════════

    ${lib.concatMapStringsSep "\n" mkS3Route (caddyRoutes.s3_routes or [])}

      # ════════════════════════════════════════════════════════════
      # MTA-STS — enforce TLS for inbound email delivery (data-driven)
      # ════════════════════════════════════════════════════════════

      ${(caddyRoutes.mta_sts or {}).domain} {
    ${secNoLimit}
        tls {
          dns cloudflare {env.CF_API_TOKEN}
        }
        handle ${(caddyRoutes.mta_sts or {}).policy_path} {
          header Content-Type "text/plain"
          respond "version: STSv1
mode: ${(caddyRoutes.mta_sts or {}).mode}
${lib.concatMapStringsSep "\n" (m: "mx: ${m}") ((caddyRoutes.mta_sts or {}).mx or [])}
max_age: ${toString ((caddyRoutes.mta_sts or {}).max_age or 604800)}
" 200
        }
        respond 404
      }

      # ════════════════════════════════════════════════════════════
      # CATCH-ALL — data-driven from caddyRoutes.catch_all
      # ════════════════════════════════════════════════════════════

      ${(caddyRoutes.catch_all or {}).domain} {
    ${secNoLimit}
        tls {
          dns cloudflare {env.CF_API_TOKEN}
        }
        root * ${lib.removeSuffix ("/" + baseNameOf ((caddyRoutes.catch_all or {}).page or "")) ((caddyRoutes.catch_all or {}).page or "/srv/error.html")}
        rewrite * /${baseNameOf ((caddyRoutes.catch_all or {}).page or "error.html")}
        file_server
      }

    '';

    docker = import ../../_shared/docker.nix;

    # GHCR image: bake Caddyfile + static files into caddy image
    ghcrCaddy = docker.mkGhcrBuild {
      name = "caddy";
      fromImage = "ghcr.io/diegonmarcos/caddy-l4:latest";
      configFiles = [
        { src = "Caddyfile"; dst = "/etc/caddy/Caddyfile"; }
        { src = "error.html"; dst = "/srv/error.html"; }
        { src = "dashboard.html"; dst = "/srv/dashboard.html"; }
        { src = "ntfy-setup.html"; dst = "/srv/ntfy-setup.html"; }
        { src = "servermail.html"; dst = "/srv/mail/servermail.html"; }
        { src = "servermail-config.html"; dst = "/srv/mail/servermail-config.html"; }
        { src = "wkd"; dst = "/srv/wkd"; }
      ];
    };

    mkDockerCompose = pkgs: docker.mkCompose pkgs {
      banner = docker.banner "~/git/cloud/a_solutions/bb-sec_caddy/src/flake.nix";

      services.caddy = docker.mkService {
        name = "caddy";
        image = ghcrCaddy.image;
        build = ghcrCaddy.build;
        container_name = config.container_name;
        networkMode = "host";
        env_file = [ ".secrets" ];
        volumes = [
          # Config is baked into image — only persistent data volumes remain
          "caddy_logs:/var/log/caddy"
          "caddy_data:/data"
          "caddy_config:/config"
        ];
        startAfter = [ "introspect-proxy" ];
        capAdd = [ "NET_BIND_SERVICE" ];  # needed for ports 80/443
        skipReadOnly = true;  # caddy writes to /data, /config, /var/log
        memLimit = "128M";
        memReservation = "48M";
      };

      # introspect-proxy already built+pushed by bb-sec_introspect-proxy pipeline
      services.introspect-proxy = docker.mkService {
        name = "introspect-proxy";
        image = "ghcr.io/diegonmarcos/introspect-proxy:latest";
        networkMode = "host";
        environment = {
          JWKS_URL = "https://auth.diegonmarcos.com/jwks.json";
          ISSUER = "https://auth.diegonmarcos.com";
          REQUIRED_SCOPE = "authelia.bearer.authz";
          DEBUG = "\"true\"";
        };
        memLimit = "64M";
        memReservation = "16M";
        healthcheck = {
          test = ''["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:4182/health')"]'';
          interval = "30s";
          timeout = "5s";
          retries = 3;
          start_period = "10s";
        };
      };

      volumes.caddy_data = { driver = "local"; };
      volumes.caddy_config = { driver = "local"; };
      volumes.caddy_logs = { driver = "local"; };
    };

  in {
    packages = forAllSystems (system: let
      pkgs = nixpkgs.legacyPackages.${system};
    in let
      defaultPkg = pkgs.runCommand "caddy-configs" {} ''
        mkdir -p $out
        cp ${mkDockerCompose pkgs} $out/docker-compose.yml
        cp ${mkCaddyfile pkgs} $out/Caddyfile
        cp ${./error.html} $out/error.html
        cp ${./dashboard.html} $out/dashboard.html
        cp ${./ntfy-setup.html} $out/ntfy-setup.html
        mkdir -p $out/mail
        cp ${./servermail.html} $out/servermail.html
        cp ${./servermail-config.html} $out/servermail-config.html
        mkdir -p $out/wkd/hu
        touch $out/wkd/policy
        cp ${./pgp-wkd-key.bin} $out/wkd/hu/s8y7oh5xrdpu9psba3i5ntk64ohouhga
      '';
    in {
      default = defaultPkg;
      docs = docker.mkDocs pkgs { inherit title config defaultPkg; docsPath = ./docs; };
    });
  };
}
