#!/usr/bin/env node
// Render the HTTP MCP server list into ~/.claude.json, preserving the existing
// login/config. Token comes from $AUTHELIA_OIDC_TOKEN_CLAUDE_ADMIN. Run on every
// container boot (the claude_home volume persists ~/.claude.json across restarts).
//
// Testable: pass a template path as argv[2] and set HOME to a scratch dir.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const TPL = process.argv[2] || "/app/claude-config/mcp.tpl.json";
const token = process.env.AUTHELIA_OIDC_TOKEN_CLAUDE_ADMIN || "";
if (!token) {
  console.error("[render-mcp] AUTHELIA_OIDC_TOKEN_CLAUDE_ADMIN unset; skipping MCP");
  process.exit(0);
}

const claudeJson = join(process.env.HOME || ".", ".claude.json");
// mcp.tpl.json is GENERATED by cloud-u-linux da_my-ai/data/claude/gen-mcp-tpl.sh from
// cloud-infra's derived server list, in the same {_warning, _doc, mcpServers} envelope
// the desktop and termux lists use. Read the envelope's mcpServers rather than the
// whole document: the metadata keys beside it are provenance, and treating them as
// server entries would hand Claude Code servers named _warning and _doc with no url.
const servers = JSON.parse(
  readFileSync(TPL, "utf8").replaceAll("${AUTHELIA_OIDC_TOKEN_CLAUDE_ADMIN}", token),
).mcpServers;

let cfg = {};
if (existsSync(claudeJson)) {
  try {
    cfg = JSON.parse(readFileSync(claudeJson, "utf8"));
  } catch {
    console.error("[render-mcp] existing ~/.claude.json unparseable; starting fresh");
    cfg = {};
  }
}
cfg.mcpServers = servers; // replace only mcpServers; login + all other keys preserved
// Headless agents cannot answer the workspace-trust dialog, and an untrusted
// workspace IGNORES every permissions.allow entry — the runner then reads but
// silently cannot write (hit live 2026-09-06). Trust the agent workspaces here,
// where boot already regenerates this file, so redeploys cannot lose it.
cfg.projects = cfg.projects || {};
for (const dir of [
  "/home/appuser/git",
  "/home/appuser/git/cloud-infra",
  "/home/appuser/git/cloud-u-android",
  "/home/appuser/git/cloud-u-containers",
  "/home/appuser/git/cloud-u-linux",
]) {
  cfg.projects[dir] = { ...cfg.projects[dir], hasTrustDialogAccepted: true };
}
writeFileSync(claudeJson, JSON.stringify(cfg, null, 2));
console.error(`[render-mcp] wrote ${Object.keys(servers).length} MCP servers to ${claudeJson}`);

// A headless `claude -p` cannot answer a permission prompt, so an MCP server that
// is offered but not granted is silently unusable — indistinguishable, from the
// agent's side, from a server that is down. The grants therefore have to name
// exactly the servers written above, and settings.json used to restate them by
// hand: it listed the seven invented keys and went stale the moment the list was
// derived. Deriving the grants from the same object removes the second list
// rather than correcting it.
//
// Claude Code takes `mcp__<server>` for a whole server and `mcp__<server>__<tool>`
// for one tool; `mcp__<server>__*` is NOT a supported wildcard. Non-MCP entries
// (Bash, Read, Write, …) are left exactly as settings.json declares them.
const settingsJson = join(process.env.HOME || ".", ".claude", "settings.json");
if (existsSync(settingsJson)) {
  const settings = JSON.parse(readFileSync(settingsJson, "utf8"));
  const allow = (settings.permissions?.allow ?? []).filter((rule) => !rule.startsWith("mcp__"));
  settings.permissions = {
    ...settings.permissions,
    allow: [...allow, ...Object.keys(servers).map((name) => `mcp__${name}`)],
  };
  writeFileSync(settingsJson, JSON.stringify(settings, null, 2));
  console.error(`[render-mcp] granted ${Object.keys(servers).length} MCP servers in ${settingsJson}`);
}
